### ISSUE TITLE
Linter info is not updated when file contents changed on autosave

### ISSUE THREAD

**Issue by pluff** [steelbrain/linter#1009]
When you have autosave enabled and a package which updates contents of file on save linter information is not updated.
See example gif:
![example](http://g.recordit.co/32mjAQmfZW.gif)
Packages used:
linter 1.11.2
linter-rubocop 0.4.4
atom-beautify 0.28.19
autosave 0.23.0

Atom 1.2.4
OS X 10.10.5

What's happening:
1. linter via linter-rubocop detects incorrect styling. 
2. autosave saves file on losing focus
3. On save atom-beautify removes incorrect styling.
4. File has correct styling, however "Project" status still shows an error. (minor bug)
5. File has correct styling, however linter shows errors. (major bug)
6. Editing\resaving file triggers linter checks and updates information to correct one.

**Comment by steelbrain** [comment]
@pluff I once see one bug here instead of many, that one "bug" is actually a feature, we only lint text editors that are active and it's very important for performance. Unless you have a *very* compelling reason for us to change that behavior, I would like it to stay that way :)

**Comment by pluff** [comment]
Can you add optional updating of information on save? I hope it will not be a performance decrease and linter status will show correct numbers. For some users it will be good alternative to "lint as you type" feature.

**Comment by Arcanemagus** [comment]
Another issue that might even be the core issue here is that there is no prioritization of handlers on the save event, this means that `linter` _may_ be triggering on save, but only before Beautifier runs, thus it still sees the same contents as it did before the save.
