### ISSUE TITLE
Add an ability to auto-hide linter gutter when there's no warnings to display

### ISSUE THREAD

**Issue by pluff** [steelbrain/linter#1010]
Horizontal space is crucial when you use 2 columns so every pixel counts. 
It would be great to have an option to autohide the gutter if there is no warnings to display.

**Comment by steelbrain** [comment]
I have considered this in the past but did not implement because most of the users have no errors initially and as they start writing a few errors appear that they fix, it would be a lot of visual show and hide for the user and at the end would become a very rough experience

**Comment by steelbrain** [comment]
Closing based on above argument, let me know if you have any counter
