### ISSUE TITLE
Option to stop opening other files when going to next error.

### ISSUE THREAD

**Issue by mjs7231** [steelbrain/linter#1033]
When clicking to see the next error in a file, it often switches context to a completely different file I have open which is often completely out of context and leaves me searching for the previous file I had open. I understand wanting to show errors for all files open, but taking you to errors completely out of context seems like the wrong solution.

Perhaps if we disable the "Show Project Tab" option, you should also only be iterating over the File errors (rather than project errors).

**Comment by Arcanemagus** [comment]
Are you saying that "Show next error" is moving you to errors from different files, even when:
* On the File tab, with the Project tab enabled
* On the File tab, with the Project tab _disabled_
* On the project tab, but you want it to stay on the same file anyway

**Comment by steelbrain** [comment]
This issue has already been solved in the linter ui split package, but I'll keep this open until it's published

**Comment by mjs7231** [comment]
It sounds like steelbrain understands the issue. Just to make this bug complete, here is the answer to the questions asked. Having the Project tab enabled or not should be irrelevant. I only mentioned it above because I was trying everything I could think of to make it stop changing the files on me.

* **On the File tab, with the Project tab enabled:** cycling through issues should stay on the same file.
* **On the project tab, but you want it to stay on the same file anyway:** cycling through issues should span all files.

As it is right now, with the File tab selected, its still changing files when cycling through errors.

**Comment by steelbrain** [comment]
@mjs7231 The linter commands haven't received any love in a long-long time. In the master branch, it iterates over all of the messages in a seemingly-random order, I have/would change it to iterate between a file once I'm done with the UI changes I'm working on
