### ISSUE TITLE
Provide a shortcut to jump to trace line

### ISSUE THREAD

**Issue by quilicicf** [steelbrain/linter#1039]
Hi, 

While using [linter-raml](https://atom.io/packages/linter-raml) I stumbled upon a use case where I had to fix multiple issues that were located in files referenced by the linted file. See screenshot: 

![selection_012](https://cloud.githubusercontent.com/assets/5594303/12143567/ed5dccb6-b481-11e5-8aba-4b3b216183c6.png)

I had to switch files to correct all the errors but couldn't do it keyboard-only. I had each time to switch to the mouse to click on the link in the `trace` section of the pop-up. 

I wonder if there could be a shortcut to redirect to the line of the error. That would IMO be very helpful. 

What do you think ?

**Comment by steelbrain** [comment]
What shortcut would you recommend for it? We have tons and tons of packages for atom and we're running short on keys to bind actions with

**Comment by quilicicf** [comment]
Not thought that far, my atom is not that customized so I don't have this issue. 
I'll think about that but is it mandatory to set a default key combination for the shortcut ? 
If it's not set by default but customizable in the settings, I think it may be just enough no ?

**Comment by steelbrain** [comment]
The purpose of the command is still unclear, what if there are multiple entries in trace? Which one will it teleport to then?

**Comment by quilicicf** [comment]
Well, given the fact that a trace leads to the origin of an error I was thinking about redirecting to the said error. Now you ask, another solution would be to enable to switch the focus to the error pop-up then switch focus from a link to another with conventional tab/shift tab navigation. 

Does this sound OK ?

**Comment by Standard8** [comment]
How about ctrl-cmd-e (on mac at least), that's what sublime uses.

If there's multiple issues in a file, then it would go to the first line with an issue after the current line (a bit like find-next).

**Comment by Standard8** [comment]
Although, I've just realised this issue might not be exactly what I thought it was. What I want is an easy way to cycle through all the errors within a file raised by a linter (in my case eslint).

**Comment by steelbrain** [comment]
@Standard8 Linter has different commands like next and previous error, you can bind them to the keys of your choice :)

**Comment by steelbrain** [comment]
No longer valid 'cause traces have been removed in linter v2, replaced with references and urls
