### ISSUE TITLE
Linter not working correctly when I install atom-beutify

### ISSUE THREAD

**Issue by Horray** [steelbrain/linter#1042]
I installed [atom](https://atom.io/), and I'm trying to add a eslinter. I added [linter](https://atom.io/packages/linter) and [linter-eslint](https://atom.io/packages/linter-eslint). It worked fine until I added the [atom-beautify](https://atom.io/packages/atom-beautify) package.

The linters does their jobs, but when I 'beautify' the JavaScript code, most errors in the code panel don't show, but they do show at the bottom. Here's what I mean:

**Before beautify the code:**

[![enter image description here](http://i.stack.imgur.com/hdDNO.png)](http://i.stack.imgur.com/hdDNO.png)

[![enter image description here](http://i.stack.imgur.com/RJwSA.png)](http://i.stack.imgur.com/RJwSA.png)

**After Beautify the code:**<br>
[![enter image description here](http://i.stack.imgur.com/tV60F.png)](http://i.stack.imgur.com/tV60F.png)<br>
[![enter image description here](http://i.stack.imgur.com/5DaRm.png)](http://i.stack.imgur.com/5DaRm.png)

How can I get the errors to show even after I beautify the code?

Here's a list of all Community Packages:
- atom-beautify
- linter
- linter-eslint

**Comment by Arcanemagus** [comment]
>I imagine what is going on here is atom-beautify is modifying the code in question, which means the markers placed on that code are no longer valid so they are removed. Since a lint hasn't been triggered yet the messages still show in the bottom panel.
>
>This isn't really anything that can be fixed here, you can workaround this by triggering another lint either by typing some more code, or saving the file (depending on your settings). Or by running `Linter: Lint` from the command palette.
>
>Let us know if that is what is going on here or if there is something more subtle at play.

**Comment by nesmyslny** [comment]
I just ran into this issue. It's not limited to atom-beautify, I could also reproduce this with atom-prettier.
The interesting part is, that the marks disappear at lines that weren't changed and only stay on lines that were changed (by atom-beautify, ...).
Unfortunately, running `Linter: Lint` doesn't do the trick in my case. Editing the affected lines only brings back the marks of these lines. Saving the file doesn't help either. So only reopening the file helps.

Steps:
1. Open file with warnings/errors
2. Run atom-beautify/atom-prettier/...
   -> only changed lines still have marks
3. Saving or `Linter: Lint` has no effect

**Comment by antoinerey** [comment]
I run into the exact same problem using `atom-prettier`. Two cases can happened when `prettier` reformats the code :

**1. The reformatted code is different from before**

In this case, `linter` understands the differences and triggers a new run, which display the inline-errors like always.

**2. The reformatted code is the same as before**

This happens when formatting some code which is already well-formatted. In this case, `linter` don't know that `prettier` ran, and do not trigger a new run: the inline-errors are not visible.

My question is : Is there a way to force `linter` to trigger a new run ? I tried `Linter: Lint` as mentioned above, but it does not work. It seems that it's doing nothing, since the file content didn't change.

**Comment by steelbrain** [comment]
Hi @antoinerey @Horray 

After thinking about this for some time, I think the best way to go about this is to contact your prettier package maintainers, and request them to trigger `linter:lint` command programatically after they prettify the code. The linter package itself cannot handle individual prettifiers and that's the best way that I can think of right now

Thanks!

**Comment by steelbrain** [comment]
Same as https://github.com/steelbrain/linter/issues/1345, this is an external bug
