### ISSUE TITLE
Add an option to disable lint-on-save

### ISSUE THREAD

**Issue by guiguan** [steelbrain/linter#1051]
Please add an option to disable lint-on-save so that I could use linter in an absolutely manual fashion for supreme performance.

Thanks!

**Comment by steelbrain** [comment]
What language are you using this for?

PS. We have a `linter:toggle` command which disables any kind-of linting on the active text editor

**Comment by guiguan** [comment]
I am currently using it with coffeescript. Oh, thanks. I guess that is good enough then.

**Comment by guiguan** [comment]
@steelbrain Hmm, after poking around this package, I found it would still be nice to have an option to disable lint-on-save. Linter packages, such as `linter-swiftc`, only support lint-on-save. I would rather binding a key to lint manually each time than triggering lint on save automatically. Lint-on-save just makes the saving process extremely slow. You can just put an option flag to guard this callback in `editor-linter.js`:

```coffee
    this.subscriptions.add(this.editor.onDidSave(() =>
      this.emitter.emit('should-lint', false)
    ))
```

**Comment by steelbrain** [comment]
@guiguan If you are using this package for lintings that are cpu intensive, I would advise you move away from `linter-swiftc` and try something that uses the `build` Atom package. It'll only build if you ask it to and will use linter to display it's errors

**Comment by steelbrain** [comment]
Closing based on above discussion
