### ISSUE TITLE
Error: Column start (x) greater than line length (y)

### ISSUE THREAD

**Issue by corysimmons** [steelbrain/linter#1069]
![image](https://cloud.githubusercontent.com/assets/224636/12824033/2edc9f06-cb3d-11e5-9cbf-a45646769d42.png)

I get these errors all the time in various languages. What causes them and how can I stop them?

**Comment by Arcanemagus** [comment]
They are almost always caused by the linter program (eg, `stylelint`) providing an invalid column. It could also potentially be the provider (`linter-stylelint`) not translating the ranges properly, but I don't know of any plugin that currently exhibits that bug.

In your screenshot it looks like `linter-stylelint` is the provider currently causing that to be thrown, can you put that `.scss` file up somewhere so we can verify where the issue is?

**Comment by corysimmons** [comment]
Sorry, I closed the errors and proceeded to modify the sheet a lot. Next time I get one of these errors I can post the file and the exact spot it's happening.

**Comment by Arcanemagus** [comment]
The error in your screenshot was triggered because `stylelint` reported an error as starting at column 13... on a line that only has 12 characters. Since this is past the end of the line it couldn't possibly be a valid value, so `atom-linter.rangeFromLineNumber` threw an error.

**Comment by arturparkhisenko** [comment]
@Arcanemagus and @1000ch (main contributors) i get this error often and want say (we need to fix it in linter-stylelint) that we fixed this error once and forever(i hope) in eslint-plugin-html by [this commit](https://github.com/BenoitZugmeyer/eslint-plugin-html/commit/3ebdbc95a1ffb8b24a91969bc5e8e60827847060) and here is [original issue](https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/16), maybe it helps to solve it.

**Comment by corysimmons** [comment]
lol, the issues. XD

**Comment by Arcanemagus** [comment]
@arturparkhisenko The error is merely saying the linter program (be it `stylelint` or `eslint` + `eslint-plugin-html`) is feeding invalid data back to us. The _cause_ of that varies widely, from your issue of not properly handling line endings, to things like not stopping pulling lexemes in when trying to tokenize a string when you hit an error state (`esprima` based JS linters), and coincidentally `stylelint` in this case if I remember right.

**Comment by arturparkhisenko** [comment]
@Arcanemagus ow, but when i change line endings i didn't get this error, thats why i get there with my idea :) anyway thanks for explanation, i'm agree with you about that.

**Comment by Arcanemagus** [comment]
Ah, sorry, thought you were the author of `eslint-plugin-html` till I just looked at those again in some detail :stuck_out_tongue:.

**Comment by steelbrain** [comment]
Should this be closed?

**Comment by Arcanemagus** [comment]
There hasn't been a rash of reports as the initial splurge of issues have either been fixed or silently ignored till the linter providers update, so this doesn't really need to serve as a catch-all any longer.
