### ISSUE TITLE
Add an option to only lint changes

### ISSUE THREAD

**Issue by dkniffin** [steelbrain/linter#1103]
When working on legacy projects that didn't start with linting, there can be *tons* of linting messages. I'd love an option to only lint code that has been edited since the last commit.

**Comment by florianb** [comment]
Hi @dkniffin - which linter do you use? It depends on the linter-plugin which scope a single "lint" has and i guess your issue belongs to the linter-plugin you're using for that project.

**Comment by Arcanemagus** [comment]
Actually this would need to be handled here, something like an option to check whether the project repository marks the file as changed and only lint if so.

**Comment by florianb** [comment]
Hmm.. i thought this would heavily depend on the language/linter. F.e. `javac` needs to load all project-files to solve cross-dependencies which is in fact a lint of the whole project. I have no time to prove it now.

An option to filter all linter-messages which aren't from the current file could be an alternative, too.

**Comment by Arcanemagus** [comment]
@florianb what they are asking is to not even trigger a lint in the first place if the file isn't marked as changed by the VCS.

**Comment by Arcanemagus** [comment]
IE: `atom.project.getRepositories()[0].isPathModified(filePath)` returns true.

**Comment by florianb** [comment]
Ahh i see - i think that's one part of the described problem. But as i said before, even if i'd would recognize only changed files, i'd have to feed all files of the project to the linter. Which would result in the whole bunch of linter-messages (because javac is linting all provided files).

**Comment by Arcanemagus** [comment]
Correct, as a project scoped linter `linter-javac` would probably show errors for these files if they had errors, but `linter` wouldn't _trigger_ a lint on them in the first place, so you would only get `lint()` called if a Java file was opened in that project.

**Comment by Arcanemagus** [comment]
I'm not sure whether I would consider hiding messages for files not modified in the VCS as part of this or not.

**Comment by steelbrain** [comment]
Linter already [hides VCS ignored files](https://github.com/steelbrain/linter/blob/fe5b935e366002207f698f24fe79437bce50adab/lib/helpers.js#L39)

**Comment by steelbrain** [comment]
Nevermind, misread the conversation :stuck_out_tongue:

**Comment by dkniffin** [comment]
@florianb @Arcanemagus I think I was a little unclear. What I'd like isn't what you're describing. Say I've only edited one line in a file. I'd like it to lint that one line (plus any other code that's part of that expression).

The linter I would like it for is rubocop, but it'd be awesome if it could easily be done for all files. From a little bit of investigation, the rubocop linter appears to be passing code via stdin, so maybe it could just pass code that has changed?

I honestly have no idea if this is even possible.

**Comment by Arcanemagus** [comment]
@dkniffin Ah, that's pretty impossible actually. Generally a linter needs to be able to see the entire file to check for things like unused variables.

**Comment by dkniffin** [comment]
I think the way I've seen this done before, is to lint the whole thing, then diff it with a `git diff`

**Comment by ProLoser** [comment]
I think it would be better to have an option to only lint the currently open file instead of the complexity around figuring out what lines have been touched.

**Comment by Arcanemagus** [comment]
@ProLoser That's how it currently works.

**Comment by steelbrain** [comment]
Closing as this should be handled in providers and is provider-specific. Feel free to continue discussing
