### ISSUE TITLE
Use Atom's block decorations instead of popups

### ISSUE THREAD

**Issue by r24y** [steelbrain/linter#1104]
I recognize that this represents a nontrivial amount of work and therefore may not be appropriate, but I thought I'd post it for discussion and at least let folks yay/nay it.

When I saw Atom's [Block Decorations](http://blog.atom.io/2016/02/03/introducing-block-decorations.html) feature, I immediately thought of this package. If I'm editing a line with an error and need to refer to the line immediately below, sometimes I have to click to another line because the linter popup is covering the text I need to refer to. Using block decorations instead would provide a better experience.

While not exactly identical, XCode gives a decent example of what I'm hinting at.

![](https://raw.githubusercontent.com/marklarr/mayday/master/docs/example_inline.jpg?token=760261__eyJzY29wZSI6IlJhd0Jsb2I6bWFya2xhcnIvbWF5ZGF5L21hc3Rlci9kb2NzL2V4YW1wbGVfaW5saW5lLmpwZyIsImV4cGlyZXMiOjE0MTQzOTAzMzh9--bc9abbe40843317e7b6a30a9521ebf6ae457ece2)

**Comment by steelbrain** [comment]
Thank you for your request. We have considered block decorations in the past but decided that implementing them would have a lot of moving up/down and will not be the best for user experience. Also I am afraid that you misunderstood block decorations, the photo you're showing can be achieved with normal decorations and not with block decorations.

Another thing to note is that in the upcoming versions, inline tooltips will follow the user cursor. So they'll be less blocking and more friendly to the users. If the user wants to see an error below the buffer cursor position, it'll be shown near the bottom panel
