### ISSUE TITLE
Notification when Lint error is inspected by user

### ISSUE THREAD

**Issue by noseglid** [steelbrain/linter#1106]
I'm [integrating `build` with linter](https://github.com/noseglid/atom-build/pull/354).

With build there's a lot of output from whatever command the user runs. A user can specify a regular expression to match this output for errors. If such a match is found, `build` pushes this message to Atom Linter.

So far so good.

When the user "inspects" the error (e.g. by clicking in the panel or issuing `linter:next-error` via keymap or otherwise) `build` would need to get a notification about this so that it can scroll that specific error into view in the output of the build. There may be more information here not contained in the linter message (such as stack traces, etc.).

The notification should contain the message that was pushed to Linter in the first place, and a `context` variable which is specified alongside the message (possibly on the message?) which can be any arbitrary information that may be needed to identify the error to the internal representation of the provider.

**Comment by steelbrain** [comment]
@noseglid Thank you for your request.

How about a `selected` attribute on linter messages that accepts a callback, the callback's `this` will point to the message. Do you think we should also pass the provider as a parameter or that would be unnecessary?

**Comment by noseglid** [comment]
That would work well.

Wouldn't it be better to provide the `message` as an argument, so that the callback can point to a member function of e.g. a class (where `this` is expected to be the class).

**Comment by steelbrain** [comment]
That sounds good as well

**Comment by steelbrain** [comment]
Implementation pending review in https://github.com/steelbrain/linter-ui-default/pull/62
