### ISSUE TITLE
Use Atom core VCS ignore setting?

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter#1107]
There is a setting accessible via `atom.config.get('core.excludeVcsIgnoredPaths')` that is the core setting for ignoring VCS ignored files used by `find-and-replace` and `fuzzy-finder`, among others. 

[Currently](https://github.com/steelbrain/linter/blob/fe5b935e366002207f698f24fe79437bce50adab/lib/helpers.js#L39) it seems that if a path is ignored by the VCS it is no matter what ignored, this should probably follow the core setting instead.

**Comment by steelbrain** [comment]
Good idea
