### ISSUE TITLE
How do you refresh linter provider behavior after the user changes its package settings?

### ISSUE THREAD

**Issue by GrahamHannington** [steelbrain/linter#1112]
The package configuration settings of my (soon-to-be-published) linter provider include `lintOnFly`. Here's the corresponding excerpt from the `configSchema` in `package.json`:

```javascript
    "lintOnFly": {
      "title": "Lint as you type",
      "description": "Lint files while typing (on the fly), without the need to save.",
      "type": "boolean",
      "default": true
    },
```

The `index.js` script for my linter provider refers to that setting:

```javascript
export function provideLinter() {
  return {
    ...
    lintOnFly: atom.config.get("linter-myprovidername.lintOnFly"),
    ...
  }
}
```

If `lintOnFly` is `true`, but then I change it in the package settings (by deselecting the corresponding check box in the Atom editor UI) to `false`, the linter provider continues to lint as you type (on the fly). To refresh the behavior to reflect the updated setting, I have to restart Atom.

With apologies for the newbie question (this is my first Atom Linter provider, my first Atom package), what is the best way to refresh the behavior of the linter provider after the user changes some setting that affects the linter provider properties? (I need to add some function to `index.js`, right?)

**Comment by steelbrain** [comment]
**Note**: It's not really a good idea to have a `lintOnFly` configuration in your package. Linter already provides it in one place for all providers.

If you want your setting to react to live config changes then you should do something like this
```js

provideLinter() {
  const linter = {
    scope: 'file',
    lintOnFly: true,
    grammarScopes: ['*'],
    lint() {
      return []
    }
  }
  this.subscriptions.add(atom.config.observe('my-package.lintOnFly', lintOnFly => {
    linter.lintOnFly = lintOnFly
  }))
  return linter
}
```

**Comment by steelbrain** [comment]
Here's a bigger picture of such package
```js

import { CompositeDisposable } from 'atom'

module.exports = {
  activate() {
    console.log('My cool package has been activated')
    this.subscriptions = new CompositeDisposable()
  },
  deactivate() {
    this.subscriptions.dispose()
  },
  provideLinter() {
    const linter = {
      scope: 'file',
      lintOnFly: true,
      grammarScopes: ['*'],
      lint() {
        return []
      }
    }
    this.subscriptions.add(atom.config.observe('my-package.lintOnFly', lintOnFly => {
      linter.lintOnFly = lintOnFly
    }))
    return linter
  }
}
```

**Comment by GrahamHannington** [comment]
@steelbrain,

Re:

>  It's not really a good idea to have a lintOnFly configuration in your package. Linter already provides it in one place for all providers.

Thanks very much for the clarification. My mistake. I had incorrectly assumed that the Linter `lintOnFly` property specified a default value for the [provider-specific `lintOnFly` property](https://github.com/steelbrain/linter/wiki/Linter-API#defining-a-provider).

So, the provider-specific `lintOnFly` only indicates the *eligibility* of a provider for linting as you type? That is, a linter provider will only perform linting on the fly (will only be triggered every `lintOnFlyInterval` milliseconds) if the Linter `lintOnFly` property and the provider `lintOnFly` property are both `true`?

I'll remove that configuration setting from my provider, and simply set my provider-specific `lintOnFly` property to `true`.

**Comment by steelbrain** [comment]
> the provider-specific `lintOnFly` only indicates the eligibility of a provider for linting as you type

Exactly, Linter needs that config to determine if a provider supports lint on fly. When the user mutates the text in an editor, it only notifies the editors that support it. Others are only triggered on save

**Comment by GrahamHannington** [comment]
Got it. Thanks again for the clear explanation (I'm learning :smile: ). Much appreciated.
