### ISSUE TITLE
How exactly does Linter decide when to trigger providers for linting as you type?

### ISSUE THREAD

**Issue by GrahamHannington** [steelbrain/linter#1113]
With apologies: if I had more time, I'd delve into the code and attempt to figure this out for myself.

I'm about to publish a linter provider that makes Ajax requests to a REST API ("web service"). That web service might be installed on the local computer, in which case it is referred to via a `localhost` URL, bypassing network interface hardware (in fact, I'm recommending this in the readme, for various reasons, including performance and security). Each time the linter provider is triggered, it issues a POST request; the request body contains the entire text of the current document in Atom.

I'd initially feared that Linter would trigger providers literally *every `lintOnFlyInterval` milliseconds*. In which case, my provider would, by default, send the entire current document, every 300 milliseconds, regular as clockwork.

Happily, that appears not to be the case: I've used the Atom (Chrome) developer tools to monitor XHR network activity, and I can only see requests being sent when I type.

But I can imagine users of my linter provider might share my initial fears, so I thought I'd offer an accurate explanation to allay those fears, hence this email.

How exactly does Linter decide when to trigger providers for linting as you type?

For example, how does `lintOnFlyInterval` relate to `keydown` events?

**Comment by steelbrain** [comment]
According to [the source](https://github.com/steelbrain/linter/blob/8f445d7e59b5e9833cf83f1bd76eeecfaa6f5e03/lib/editor-linter.js#L36-L38), linter only triggers it's on the fly provider once in 300ms, it only triggers them when the user is typing.

If the user keeps on typing, it discards results of previous provider invocations and uses only the result of the latest one.

We were previously using [`TextEditor::onDidStopChanging`](https://atom.io/docs/api/v1.6.0/TextEditor#instance-onDidStopChanging) API. The only downside was that we couldn't configure the interval//timeout. We are now using [`TextEditor::onDidChange`](https://atom.io/docs/api/v1.6.0/TextEditor#instance-onDidChange) with a custom debounce
