### ISSUE TITLE
Created a new Linter, request for inclusion in the full-list

### ISSUE THREAD

**Issue by smeevil** [steelbrain/linter#1114]
Hi there, 

I created a new Linter for Elixir using Credo.
It's available here : https://atom.io/packages/linter-elixir-credo

I was wondering if could  add it to the full list under the elixir category.

Gerard.

**Comment by steelbrain** [comment]
Thanks @smeevil :+1: 
Please open a PR to [`atomlinter.github.io`](https://github.com/AtomLinter/atomlinter.github.io).
