### ISSUE TITLE
Linter not triggering/updating when the same file is open in two panes

### ISSUE THREAD

**Issue by kileras** [steelbrain/linter#1115]
If I open the same file in two panes and I modify one of them the linter only triggers in one, not in the other. Its not clear to me exactly whats the logic behind which one triggers, at least for my test with some js and sass files sometimes is the right one and sometimes the left one.

Its specially annoying when you have a ton of fields open and you forget that you already have the file, you open it and you get no errors at all (maybe #1002 is related?) It's seems quite similar to #811 but in this case is not the latest saved one, so it may be some kind of regression?

I can reproduce it consistently and I'm using Atom 1.6.0 on OSX 10.11.4.

**Comment by steelbrain** [comment]
Can you please retry this in the master branch? It's very likely that this issue has already been fixed

**Comment by kileras** [comment]
Well I just tried and it is actually fixed in master. Thanks and good work!

**Comment by steelbrain** [comment]
I am glad it works, :+1: thanks for the feedback
