### ISSUE TITLE
Only lint currently open file

### ISSUE THREAD

**Issue by ProLoser** [steelbrain/linter#1117]
I'd like to be able to disable project-wide linting and instead only lint the current file. It's causing atom to run extremely slow.

**Comment by Arcanemagus** [comment]
Do you mean a toggle to disable project scoped linters?

It already only _triggers_ on the currently open file, but some linters will no matter what run on the entire project and return results for many files (and are thus project scoped).

**Comment by ProLoser** [comment]
Oh, no way to disable this? It's es6 linting, but yeah I don't want it to do the whole project like it does.

**Comment by Arcanemagus** [comment]
I'm not sure which linter plugin you mean, but none of the 3 I know of (linter-eslint, linter-jshint, linter-jscs) are project scoped, so... still not sure what you mean :confused:.

**Comment by ProLoser** [comment]
eslint

**Comment by ProLoser** [comment]
How can that be true if there's a project tab?

**Comment by ProLoser** [comment]
<img width="781" alt="screen shot 2016-03-30 at 10 35 49 am" src="https://cloud.githubusercontent.com/assets/67395/14165864/93cb65fe-f6c2-11e5-844b-2c0fa3bf5165.png">

**Comment by ProLoser** [comment]
<img width="219" alt="screen shot 2016-03-30 at 9 58 34 pm" src="https://cloud.githubusercontent.com/assets/67395/14165868/a87d04da-f6c2-11e5-991e-67e77f1da73b.png">

**Comment by Arcanemagus** [comment]
The messages are cached. The project tab shows the messages for all open files + any files project scoped linters mention, but only the active file is actively being linted.

linter-eslint is actually one of the few linters that runs in a worker thread, meaning out of all of them it has the _least_ impact on Atom's performance. (On my computer `linter-eslint` blocks the UI thread for about 11ms, even though the total lint process takes ~1.5-4.5 seconds)

Are you sure something else isn't slowing things down?

**Comment by ProLoser** [comment]
Okay yeah nevermind. it's not the project wide parsing, it's literally eslint's file parsing that is causing the IDE to lock up for me every time it runs. It's very frustrating.

**Comment by Arcanemagus** [comment]
@ProLoser that should only be possible on an _ancient_ version of `linter-eslint`, can you file an issue on that repo specifying the versions you are using and possibly providing a file that you are seeing issues on?

**Comment by steelbrain** [comment]
Closing based on discussion above
