### ISSUE TITLE
new linter that could be mentioned at atomlinter.github.io

### ISSUE THREAD

**Issue by eriklovlie** [steelbrain/linter#1119]
Hi, thanks for a wonderful package! I've made a simple ocaml linter provider (atom.io/packages/linter-ocaml) and I wonder if this could be added to the list in atomlinter.github.io?

OCaml is currently not there afaict, which is a shame (haskell has two!). I believe nuclide contains one as well from what I can see in their repo.

(I couldn't see an obvious way to do the update myself and submit a pull request, hence this issue)

**Comment by steelbrain** [comment]
Thank you for making that linter :+1: 

Please open a PR on [`atomlinter.github.io`](https://github.com/AtomLinter/atomlinter.github.io)
