### ISSUE TITLE
Linters not linting...

### ISSUE THREAD

**Issue by MiniFlames** [steelbrain/linter#112]
Just installed linter and a couple of it's plugins [linter-csslint, linter-coffelint, linter-scss-lint and linter-jshint] and well... they're not doing anything... not highlighting of errors, no 'you idiot you've missed off a semicolon', nothing...

no errors in the developer tools console or anything like that, i'm clearly missing something but can't for the life of me figure out what it is...

Running Windows  8.1 x64, atom version 0.107.0-ccb01c2

**Comment by lorenmh** [comment]
I fixed it by uninstalling Atom

**Comment by bgreenawald** [comment]
I had this same problem on Windows 8 but was able to fix it by editing the config.cson file in Atom. After you've downloaded your linters, you need to first get the full path (file location) for the linter. Then, go into the config.cson file and you should see all the linters you've downloaded somewhere in the file. For example, I was trying to get pylint to work. In the config file there should quotations containing your specific linter somewhere in the file, for example, mine has a line of code that just read:
"linter-pylint": {}

Delete the brackets and in the line under the name of your linter (keep the colon and it should auto indent the next line) add "path: " and then the full path name of your linter. So my pylint went from
"linter-pylint": {}

to 

  "linter-pylint":
    path: "C:Users/Student/.atompackageslinter-pylint"

then I restarted Atom and the linter was working just fine. The same method worked for the c++ linter clang. Note: you also might need to do the same thing for the generic linter itself i.e your file might contain a line that just says
"linter": {}

or something similar, and you just follow the same procedure. Hope this helps!

**Comment by steelbrain** [comment]
@bgreenawald be advised that I and a lot of other people are using the new linter without any kind-of `config.cson` at all. If someone else has this issue, they should try upgrading their atom or maybe resetting their atom conf
```
mv ~/.atom ~/.atom-bkp
```
