### ISSUE TITLE
Lint As You Type not working

### ISSUE THREAD

**Issue by lcarraro** [steelbrain/linter#1120]
Lint as you type isn't working at all. Tried with MATLAB, C++ and Java. I'm running Atom on Windows 10.

**Comment by steelbrain** [comment]
This only works if the providers support it, can you please tell us the providers that you're using?

**Comment by lcarraro** [comment]
Oh, that might be it. I'm using cppcheck, javac and matlab. However it seems to me that at least javac should support it.

**Comment by steelbrain** [comment]
Closing as external, please reopen this in those providers asking for lint as you type support :)
