### ISSUE TITLE
Setting for font/font size

### ISSUE THREAD

**Issue by andjd** [steelbrain/linter#1122]
Hi all,

Is there a way to set the font and font size for the lint messages.  I didn't see any such options in the settings.

The default size is very small and hard to read on my high-res monitor.

**Comment by Arcanemagus** [comment]
You would need to file this on https://github.com/steelbrain/linter-ui-default, all UI work is being done there.

**Comment by steelbrain** [comment]
Please make sure to also open a bug report in your UI theme as well because that's where linter panel inherits it's font size from

**Comment by steelbrain** [comment]
Closing as external
