### ISSUE TITLE
Inline error popups no longer show for any linters

### ISSUE THREAD

**Issue by smlombardi** [steelbrain/linter#1123]
I have a MBP 15" retina running Atom 1.7.0-beta4 and 10.11.4.

The inline errors used to work but now they do not.  They do work on my other MBP 13", though, with the same versions of Atom and OS.

The only difference that comes to mind it that the 15" we just uninstalled Node js and re-installed it using NVM, which of course changes the node path.  Not sure if that is relevant.

The 15" (non-working) one has node 5.10.0 at `~/.nvm/versions/node/v5.10.0/bin/node` and the older mac has node 4.4.0 at `/usr/local/bin`

On this Mac I also disabled jshint and jscs linters and installed linter-eslint and linter-js-standard.  The linters work, show gutter error markers and status bar errors, but not inline popups.

**Comment by steelbrain** [comment]
Can you please check your config to see if you have disabled them there?

**Comment by smlombardi** [comment]
Not that I'm aware of.

<img width="458" alt="screen shot 2016-04-05 at 9 43 28 pm" src="https://cloud.githubusercontent.com/assets/835148/14303323/ba64abf8-fb77-11e5-9fe3-4d504dc0a0ed.png">

**Comment by steelbrain** [comment]
Can you please show a screenshot where there's errors in the panel but no inline ones?

**Comment by smlombardi** [comment]
<img width="611" alt="screen shot 2016-04-06 at 7 31 26 am" src="https://cloud.githubusercontent.com/assets/835148/14315185/d59569b0-fbc9-11e5-8069-fa99cf1896e4.png">

**Comment by steelbrain** [comment]
Aha! It's painting them but `linter-scss-lint` is providing invalid ranges, can you please open a bug in `linter-scss-lint` repo with this screenshot?

**Comment by Arcanemagus** [comment]
Actually it's not providing _invalid_ ranges, just a 0 width range I'm betting, resulting in no underline. It's a common issue in linters that don't use the `rangeFromLineNumbers` helper function.
