### ISSUE TITLE
Something bad happened: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pdonias** [steelbrain/linter#1124]
Context:
Linux 4.2.0-35-generic #40-Ubuntu x86_64
Atom 1.6.2
Linter 1.11.4

Error `Something bad happened: Maximum call stack size exceeded` appears when saving a file.

**Comment by steelbrain** [comment]
This is a problem in one of your linter providers, this linter is just the base. Please re-open this in the appropriate repo, Thanks!
