### ISSUE TITLE
Overlapping warnings and errors should prioritize error tooltip, not warning

### ISSUE THREAD

**Issue by axefrog** [steelbrain/linter#1125]
On a line that has both an error and a warning, if the column index for the warning precedes that of the error, the warning will be displayed, obscuring the error. Obviously an error is always going to be of greater significance than a warning, and thus it should take priority over that of the warning tooltip.

In the image below, the warning relates to the fact that I haven't yet used the variable in question. It's forcing me to make use of the variable before fixing the error, simply so I can see what the error is. I'd prefer to fix the error before writing new code.

![image](https://cloud.githubusercontent.com/assets/298883/14401953/a5ea81e2-fe66-11e5-8ca7-80efd02b994b.png)

**Comment by Arcanemagus** [comment]
I would say that this should be filed in the `linter-ui-default` repository as that is where all UI work is being done... but it's already essentially fixed there as all warnings that have a range that encompases the current cursor are displayed.

(The _priority_ of the messages aren't taken into account, but then the current message priority isn't standardized so there isn't a good way to do that anyway.)

**Comment by steelbrain** [comment]
This particular one has already been fixed by showing all the messages under that cursor position

**Comment by hedefalk** [comment]
+1
<img width="1169" alt="screen shot 2016-04-15 at 15 40 39" src="https://cloud.githubusercontent.com/assets/116520/14563114/8717b492-0320-11e6-8086-cd48552b3c70.png">

**Comment by Arcanemagus** [comment]
I'm marking this as closed, as stated it is already fixed in the `linter-ui-package` which will be the new UI on the next release.
