### ISSUE TITLE
Error path, reference #150 

### ISSUE THREAD

**Issue by igoreliasm** [steelbrain/linter#1128]
Guys, observe this error or bug

![captura de tela de 2016-04-13 12 32 39](https://cloud.githubusercontent.com/assets/2879536/14499420/9786dffe-0174-11e6-845b-29bdf212c148.png)

Reference
#150 

I use ubuntu 15.10 
In init.coffee, I add
```
 process.env.PATH = ["/bin",
                    "/usr/bin",
                    "/usr/local/bin",
                    ].join(":")
```

Please.

**Comment by Arcanemagus** [comment]
Please make sure you actually have `flake8` installed on your computer, if you do then please file an issue on the [linter-flake8](https://github.com/AtomLinter/linter-flake8/issues) repository for further diagnosis.

**Comment by igoreliasm** [comment]
Yes.

```
$ pip install flake8
$ pip install flake8-docstrings
$ apm install linter-flake8
