### ISSUE TITLE
Suggestion: Use Block Decorations to Report Linter Messages

### ISSUE THREAD

**Issue by dahjelle** [steelbrain/linter#1131]
It occurred to me that [Atom's new block decorations](http://blog.atom.io/2016/02/03/introducing-block-decorations.html) might be perfect for reporting lint errors, perhaps better than either the tooltips (as they wouldn't obscure editing) and the error panel (as it stays next to the error in question).

Just an idea. Thanks for the great tool!

**Comment by steelbrain** [comment]
Thank you @dahjelle for your request, we have explored that option and found it to be too invasive, using it would the lines up and down too much and would be uncomfortable to the user.

TLDR; It sounds better that it looks

Thanks again for your request

**Comment by dahjelle** [comment]
Sounds great—thanks! 👍
