### ISSUE TITLE
Multiple lint messages on one line are not all displayed

### ISSUE THREAD

**Issue by eboracus** [steelbrain/linter#1132]
Not sure whether this is language specific (using `linter-clang` here) or more general, but when more than one type of lint notification (error/warning...) are on the same line only one is displayed visually (gutter/underline/pop-up). Below, on line 22, there is an error message and a warning message, but (in this case) only the warning is shown in the gutter and only the error is shown in the pop-up when on a character linked to both messages.

![linter_errorwarning](https://cloud.githubusercontent.com/assets/11758299/14589054/bb2fcf60-04d0-11e6-96a4-4ffc4d3c9419.png)

It could be made so that just that the highest priority message (error) is displayed when there is more than one. But, in order to give maximal information at a glance, I think it would be better if both were shown with a hybrid gutter icon, maybe something like this:

![linter_errorwarning_both](https://cloud.githubusercontent.com/assets/11758299/14589725/f3b0ea9e-04e0-11e6-897a-c0155352adf4.png)

and the pop-up appearing when the cursor is over more than one overlapping notifications could have two lines (error on top, followed by identically formatted warning etc. underneath).

**Comment by steelbrain** [comment]
In the latest version of `linter-ui-default`, we have made the tooltip show all the errors under that line, the gutter icon hasn't been updated to match what you proposed though, can you please reopen this in https://github.com/steelbrain/linter-ui-default

**Comment by eboracus** [comment]
Good to know the multiline tooltips are in. Re-opened in `linter-ui-default`.
