### ISSUE TITLE
Message.expanded Bool

### ISSUE THREAD

**Issue by benjick** [steelbrain/linter#1135]
Allow the linter to specify if a message should be expanded or not. Hacking around with html just to get expanded messages isn't nice 
https://github.com/steelbrain/linter/wiki/Linter-API#messages

**Comment by steelbrain** [comment]
Can you explain what you mean by expanded message? Currently we treat a message as multiline if it's text contains `\n`

**Comment by benjick** [comment]
![](http://i.imgur.com/7fvnPOv.png)

See attached screenshot where second one is expanded

**Comment by steelbrain** [comment]
Yep, these are multiline messages, one can just provide `\n` in the text to make messages appear this way

**Comment by benjick** [comment]
Yes, I have `\n` in them, but what I'm saying is that I want to be able to choose if they are expanded or not

**Comment by steelbrain** [comment]
Can you please elaborate the use case?

**Comment by benjick** [comment]
As I said, I want to show them expanded and I can do so if I put in HTML instead, but that doesn't feel like a pretty solution

**Comment by steelbrain** [comment]
I am very confused, what are you trying to say?

0. You have `text` attribute in your messages but are unable to make messages expandable?
0. You have `html` attribute in your messages but are unable to make messages expandable?
0. Like 1 but you want to make them unexpandable?
0. Like 2 but you want to make them unexpandable?

**Comment by Arcanemagus** [comment]
If I'm understanding them correctly they want to specify an `expanded` attribute on the message that sets the default state of the message for the user.

So if `message.expanded` was set to true, the message would default to being already expanded for the user.

**Comment by steelbrain** [comment]
That makes sense, Thanks @Arcanemagus. @benjick is this what you meant?

**Comment by benjick** [comment]
Yes, exactly

**Comment by steelbrain** [comment]
No longer relevant in the new UI, stay tuned
