### ISSUE TITLE
Linter path wrong (doubled path)

### ISSUE THREAD

**Issue by integrii** [steelbrain/linter#1136]
Why would this occur???  I can't seem to find any override.  Ive tried opening the file in many ways to make it stop.

![image](https://cloud.githubusercontent.com/assets/98695/14665524/a9a94eba-0688-11e6-8a29-e6287d35dbe6.png)

**Comment by steelbrain** [comment]
This would happen if the path is not in your project folders. This can happen when you're editing symlinked project folders

**Comment by integrii** [comment]
It is a symlink! I should have realized.  Thanks. You're great.
