### ISSUE TITLE
Toggle error, warning in Error Panel

### ISSUE THREAD

**Issue by dhprototype** [steelbrain/linter#1138]
It would be great if there is a button to toggle Error and Warning so it can be hidden/revealed in the Error Panel on the fly. Minimally, to hide/reveal warnings.
Maybe this can be done by listing the count of issues separately.
Currently, it just lists count of all issues.
| X 13 issues |

Maybe it should be listed as

| X 2 issues (in red) | X 11 issues in (yellow) |

And clicking the count in red only shows the error.

Another thing that might help would to bring Error to the top so they are listed first.

**Comment by pitaj** [comment]
:+1: for this

It would be amazing to be able to ignore or hide by category [warning, error], and would be twice as cool to be able to ignore certain issues altogether.

One change to your suggestion. I think it would be good to show it like this:

| x 2 errors | x 11 warnings |

Obviously this package already designates the difference between errors and warnings, so I'd assume this would be a fairly simple (though possibly long) improvement.

**Comment by steelbrain** [comment]
Please subscribe to this instead https://github.com/steelbrain/linter-ui-default/issues/59
