### ISSUE TITLE
just why i have try to like atom but it has bugs hell bugs 

### ISSUE THREAD

**Issue by Mills1** [steelbrain/linter#1142]
I have a bug and i can't fix it! I can't install any packages and the editor stops on me

**Comment by florianb** [comment]
Honestly - you don't expect any help with that title. Stop polluting the backlog.

**Comment by steelbrain** [comment]
@Mills1 Here's an old school fix that should work for you

```
mv ~/.atom ~/.atom-data
atom
```

and then try installing and all, let me know if it still doesn't work

**Comment by steelbrain** [comment]
Closing due to lack of feedback
