### ISSUE TITLE
Add a option or command to trigger project-wide linting

### ISSUE THREAD

**Issue by lukeapage** [steelbrain/linter#1145]
in my case for eslint, I'd like to see errors on the whole project within atom.

originally raised here: https://github.com/AtomLinter/linter-eslint/issues/558

**Comment by tonyxiao** [comment]
Anything I can do to help the development along here? (PR, whatevs)

**Comment by steelbrain** [comment]
We certainly could use some React + CSS skills to ship the new major version faster and then focus on this issue, Are you on Atom slack?

**Comment by tonyxiao** [comment]
Now I am, username `tonyx`.

**Comment by steelbrain** [comment]
Hi @lukeapage

There are two types of providers for the linter package, `file` and `project` scoped. What you described is already the behavior of the project scoped ones, to support this in `file` scoped ones is very hard for the base linter. For example, the base linter currently ties the result of the linter provider with the text editor, so whenever a text editor is destroyed, all the results of file-scoped linters of that editor are destroyed as well.

If we trigger a project-scoped linting from the base linter, we'll have to open all of those files in separate editors which would get ugly. So the best way for ESLint to support project-wide linting is to register itself as a indie-scoped provider, and watch all of the files within the root directory (and ignoring ones requested by `.eslintignore`) using a module like [`chokidar`](https://www.npmjs.com/package/chokidar) and sending their results back to linter.

Thank You, closing as external
