### ISSUE TITLE
After installing linter, apm is broken, what did I do wrong?

### ISSUE THREAD

**Issue by FrankenApps** [steelbrain/linter#1148]
After trying to install linter I can't instally any package anymore. I have installed linter and it worked at first so I started installing some language packages for linter and now regardless of what package I try to install or uninstall I am getting this output:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\NearCZ\AppData\Local\atom\app-1.7.3\resources\ap
p\apm\bin\node.exe" "C:\Users\NearCZ\AppData\Local\atom\app-1.7.3\reso
urces\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users
\NearCZ\.atom\.apm\.apmrc" "--userconfig" "C:\Users\NearCZ\.atom\.apmrc"
"install" "C:\Users\NearCZ\AppData\Local\Temp\d-11644-4408-bhizur\packag
e.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm v2.13.3
npm ERR! file C:\Users\NearCZ.atom.apm\brace-expansion\1.1.4\package\package.j
son
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!

npm ERR! ^
npm ERR! File: C:\Users\NearCZ.atom.apm\brace-expansion\1.1.4\package\package.
json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

I do not know how to format that output correctly so here is a screenshot, too.

![apm_error](https://cloud.githubusercontent.com/assets/17967303/15017281/40ec0b86-1215-11e6-9c4e-67b0293f8927.png)

I hope someone could help me and tell me what I must do to make apm working again. I tried searching but I did not find anything...

**Comment by Arcanemagus** [comment]
Looks like `apm` just failed to download the package properly, try running the same command again?

**Comment by FrankenApps** [comment]
After doing some research it seems like there somehow is a bom in my package.json, but I don't know how to remove them yet...

**Comment by FrankenApps** [comment]
It looks like my default text editor which I have set as a standard for .json files added the bom.

**Comment by florianb** [comment]
@FrankenApps that's a common problem - every popular Editor should have an option to leave BOMs out.

**Comment by Arcanemagus** [comment]
Ah ha, glad you found the issue, although I'm curious as to why you were manually editing that file? :stuck_out_tongue:.
