### ISSUE TITLE
Reconsider current behaviour of only linting active tab 

### ISSUE THREAD

**Issue by jesucarr** [steelbrain/linter#1160]
Imagine I open 12 tabs, and edit them. If I "Save All" and didn't have any lint errors in the active tab, but I had error in the other 11, I won't get any sort of notification.

I would need to open each tab one by one and save individually.

I think at least the 12 tabs that I have open should be linted.

And ideally add an option or a button to scan the entire opened project.

**Comment by steelbrain** [comment]
At the moment linter only lints the active tabs on change. I would be fine to change this behavior if this issue can get enough votes

**Comment by Arcanemagus** [comment]
I'd be against this, something like this should be handled by a build system (such as a grunt task or the like).

Linter is really meant for dealing with the currently active file.

**Comment by jesucarr** [comment]
Ok, @Arcanemagus maybe the entire project is a task for a build system. But @steelbrain at the moment if you make a change in a tab, select another tab, and "Save All", it won't lint the changed tab. Please consider correcting that.

**Comment by florianb** [comment]
I think overall linting should not be seen as a task dedicated to build systems only. With linting we are doing something a build system may do, too. But the build system has additional, time consuming, tasks like executing tests, cleaning, building and so on.

I think we should get more explicit about the use case of the atom linter in general.

I consider using a linter to become faster, identifying syntactical errors earlier. In that case it seems legit to me handling several tabs at once. Consider the following use case: i want to change two files, i open them at once (`atom file1 file2`), both tabs are opened, i edit, switch the tab, edit again, take a look if everything is green, save all & close.

I would vote against it, if it would be completely against the linters architecture or a fancy use case probably nobody would benefit from. But i think this is something a lot of IDEs actually in a even broader approach (by showing linting-results in the file tree) and this is something that would add some flexibility to your workflow.

**Comment by florianb** [comment]
This issue seems to be partly connected to #1145

**Comment by steelbrain** [comment]
Done (not yet released, but closing anyway to keep only unresolved issues open for easy view)
