### ISSUE TITLE
linter-indie API, setMessages, and project scope

### ISSUE THREAD

**Issue by joeroback** [steelbrain/linter#1166]
Hi.

I am trying to use the linter-indie API to push issues from an expensive parse action (libclang).

Since setMessages is a "project" scope, it seems that I have to maintain and save off all issues for all open editors and for each time that a file is reparsed, I have to recombine all the issues (*from all editors*) before sending the issues to the setMessages API...

If a project has a lot of open files and a lot of issues, each file reparse is a lot more expensive than expected. It seems like I want "file" scope here... Yes/No? That way I only have to update, copy, and set issues for the single file that was reparsed.

What is the recommended way to proceed here? Should I look at using the linter-plus-self API? Unsure at this point if that will even allow me to get access to the editor linter object...

**Comment by steelbrain** [comment]
The reason linter indie API is project-scoped is because I couldn't think of a nice way to support file specific ones, because you could have messages for text editors that haven't been opened yet and stuff

**Comment by joeroback** [comment]
hrmm.. I was thinking of something like this:

```coffeescript
indieRegistry = null
consumeLinter: (registry) -> indieRegistry = registry

# then in observeTextEditors...
atom.workspace.observeTextEditors (editor) ->
  editorLinter = indieRegistry.getEditorLinter editor
  observers = new CompositeDisposable()
  observers.add editor.onDidDave = ->
    # ... do libclang parse, returns issues in issuesArray
    editorLinter.setMessages issuesArray # at file/editor scope
```

Not really sure 100% if that is even possible. And of course, I would have to make sure that issuesArray only contains issues for file associated with editor, but that is how libclang works (and ycmd/YouCompleteMe)...

**Comment by steelbrain** [comment]
That could be done, but we'll have to get enough votes first, also can you explain all the problems in points that you face with the Project-scoped API?

**Comment by joeroback** [comment]
I guess the problem is, now I have to maintain a map of files to arrays of issues. I have to observe onDidDestory and remove from map and call setMessages. I am keeping the lists of issues around in memory. Every time a single file needs reparsing, I have rebuild the entire project's issue list.

I am doing 50% + of the work that linter provides using the providerLinter vs consumerLinter.

providerLinter is fine for web languages, but compiled languages, its sucks, and the consumer model fits. The file has to be parsed/compiled to be able to provide semantic code completion, and that parse also conveniently returns any issues.

Using the providerModel, every time the file needs re-parsing, you will have the competion side re-parse and the linter re-parse. That has a couple of problems. All should be obvious.

So back to the consumer model / linter API. It lacks, since I now have to manage the list of issues separately, in duplicate.

**Comment by david-driscoll** [comment]
Something like `setMessages(filePath: string, messages: LinterMessage[])` would be useful in the OmniSharp case as well.

We do the same thing, have Map that we keep diagnostics for each file.  As changes filter in (which is now strictly push based) I just use lodash's `_.flatten(_.toArray(map.values()))` which returns a list to hand off to linter.

In reality it would just mean that `linter` would have to manage a map of issues (which you might be already, I don't know).

**Comment by yitzchak** [comment]
:+1:

**Comment by steelbrain** [comment]
Done (not yet released, but closing anyway to keep only unresolved issues open for easy view)
