### ISSUE TITLE
VCS ignored files are still linted

### ISSUE THREAD

**Issue by mxstbr** [steelbrain/linter#1167]
A file is git ignored, I've got "Do Not Lint Files Ignored by VCS" checked in the linter base config, but `linter-eslint` is showing errors. I've ran

```JS
atom.project.getRepositories()[0].isPathIgnored(atom.workspace.getActiveTextEditor().getPath())
```
in the console and it returned `true`.

Screenshot of all of those things:

<img width="1162" alt="screen shot 2016-05-29 at 16 29 46" src="https://cloud.githubusercontent.com/assets/7525670/15634028/ade4754e-25ba-11e6-91ca-63a3cf658760.png">

In the tree view and the tab you can see that Atom recognizes the file as VCS ignored (in this case git). You can also see `linter-eslint` is still linting it, and that the JS code above returns true.

----

Originally submitted in the `linter-eslint` repo, was told to move it over here: AtomLinter/linter-eslint#437

**Comment by steelbrain** [comment]
Can you provide a way to repro this behavior?

**Comment by mxstbr** [comment]
@steelbrain hmm, let me see what I can do. Is  a `.zip` with contents where it happens sufficient?

**Comment by steelbrain** [comment]
Sure, sounds good

**Comment by steelbrain** [comment]
Closing for the lack of update
