### ISSUE TITLE
Linter tips improperly positioned in relation to panes

### ISSUE THREAD

**Issue by dcalhoun** [steelbrain/linter#1174]
It appears as though the linter tips do not play well with split panes. For example, if a line length restriction is violated and the offending line extends past the width of the pane, the linter tip will appear on top of an unrelated pane. If this issue should be opened in a different repository, my apologies, just let me know.

<img width="1440" alt="screen shot 2016-06-09 at 15 59 21" src="https://cloud.githubusercontent.com/assets/438664/15946323/004cbe82-2e5c-11e6-86a3-9a9f44eeff66.png">

#### Behavior
1. Open two panes, left and right
2. Ensure the left pane has a line that extends past the pane width and contains a linter violation
3. Place cursor within the aforementioned line

#### Current Outcome
The linter tip appears over the unrelated, second pane.

#### Expected Outcome
The linter tip appears over the related, first pane.

#### Environment
- Mac OS X 10.11.5 (15F34)
- Atom 1.8.0
- linter 1.11.5
- linter-coffeelint 1.1.2

**Comment by steelbrain** [comment]
What themes are you on?

**Comment by dcalhoun** [comment]
- **UI Theme:** One Dark
- **Syntax Theme:** One Dark

**Comment by steelbrain** [comment]
Do you always encounter this or sometimes?

**Comment by dcalhoun** [comment]
This was the first time I've encountered it, as the extreme line length is an rarity. I'll keep an look out and do some more testing with skinny panes.

**Comment by steelbrain** [comment]
Thanks 👍

**Comment by dcalhoun** [comment]
This bug does appear to happen consistently. The linter tip appears to be fixed to the end of the line (EOL). So, if the EOL appears outside of the visible area of the pane, the tip will appear floating attached to nothing.

I suppose my expectation is that the the tip would attempt to be at the EOL, but if EOL extends past the pane, the tip's horizontal placement would halt at the panes furthest edge. I have attached an image to illustrate that expectation.

What are your thoughts? Do you agree with this expectation? Do you think this is able to be accomplished?

![linter-tip-position](https://cloud.githubusercontent.com/assets/438664/15966196/b63d5342-2ee7-11e6-84e9-c77aaf5ee5db.png)

**Comment by steelbrain** [comment]
Fixed in v1.11.7

**Comment by dcalhoun** [comment]
Awesome. Positioning based on the cursor works for me. Thanks!
