### ISSUE TITLE
Tooltip on error is not removed after correcting error

### ISSUE THREAD

**Issue by jeffschwartz** [steelbrain/linter#1176]
Tooltip remains even after correcting error. Remains even after making another tab active or setting focus to another app altogether. 
![screen shot 2016-06-10 at 10 12 22 am](https://cloud.githubusercontent.com/assets/271288/15967316/2988f6c8-2ef5-11e6-86b5-0400a9baecef.png)

**Comment by steelbrain** [comment]
Investigating

**Comment by steelbrain** [comment]
Can you try the `master` branch and see if the fix works for you?

**Comment by dcalhoun** [comment]
@steelbrain I've begun experience this as well. Possibly related to the changes in #1174?

**Comment by steelbrain** [comment]
@dcalhoun I've pushed the fix to master, waiting on a confirmation before publishing

**Comment by steelbrain** [comment]
Fixed by v1.11.8

**Comment by jeffschwartz** [comment]
@steelbrain sorry I couldn't followup to this yesterday but I see that you already pushed out a release and I can confirm that it fixes the issue. Thank you very much :)
