### ISSUE TITLE
Tooltip text has dark color against dark background when using one-light-ui theme

### ISSUE THREAD

**Issue by elliottsj** [steelbrain/linter#1180]
I'm not completely sure whether this is the right place to file this issue, but I've noticed that the linter tooltip label and the rule name have a dark text color when using the One Light UI theme, which is a bit hard to read again the dark background. For example:

<img width="682" alt="screenshot 2016-06-12 13 56 07" src="https://cloud.githubusercontent.com/assets/2177366/15993034/d0f48f12-30a8-11e6-9d30-353293c932ce.png">

In this case, the label "ESLint" and rule name "import/no-unresolved".

Using:
- Atom@1.8.0
- one-light-ui@1.3.1
- one-light-syntax@1.2.0
- linter@1.11.8
- linter-eslint@7.2.2

**Comment by steelbrain** [comment]
I would personally say that this is a linter-eslint bug because it uses the html elements and classes that the theme paints incorrectly

**Comment by elliottsj** [comment]
Thanks, I've created an issue over there: https://github.com/AtomLinter/linter-eslint/issues/605
