### ISSUE TITLE
Can't read property column of undifined

### ISSUE THREAD

**Issue by LiverEatnJohnson** [steelbrain/linter#1181]
I get an error saying can't read property column of undifined it i look at helper.js line 52 there is a message.somthing.start.column there the error is.  And the version number from the repo zip is still 1.11.4 so update is not dected

**Comment by Arcanemagus** [comment]
I'm not sure what you mean by "repo zip" up there, Atom installs packages into `~/.atom/packages/linter`.

Are you getting an error message from Atom? Does it include a little clipboard icon? If so can you click that and paste the output in a comment here?

**Comment by LiverEatnJohnson** [comment]
Work blocks content through the package manager, so I go to git hub and click the clone or download button and install packages with apm from the zip file.  It's worked so far.  The error I get says cannot find property column of undefined?  Line 52:56 (I think I got the line num right not at work now) I will add more tomorrow

**Comment by steelbrain** [comment]
@LiverEatnJohnson You should be downloading zip of the `master` branch instead of the WIP branch.
