### ISSUE TITLE
[Feature request] Toggle warning messages

### ISSUE THREAD

**Issue by janosimas** [steelbrain/linter#1184]
It would be great if I could see errors and warning or toggle warnings and only see errors.

**Comment by steelbrain** [comment]
It's already possible, use `ignoredMessageTypes` config

**Comment by janosimas** [comment]
I didn't know it was possible but that's not what I meant.

a toggle button like the "file/project", so It could be done while I look at the messages.

**Comment by steelbrain** [comment]
I am sorry but we can not add that feature, mainly because it would take a lot of space and isn't as useful

**Comment by janosimas** [comment]
I was thinking of something like the [terminal-plus](https://atom.io/packages/terminal-plus) bar, over the terminal. Their images are terrible, if you can install to see what I mean.

If over the error's list would be a small bar, it could accommodate the file/project button and a toggle button for errors type. It could work as a solution to #1183.

**Comment by drawcard** [comment]
Hi, can someone please point me in the right direction as to using the **ignoredMessageTypes** config switch? Which file would that be located in, eg config.cson?

**Comment by steelbrain** [comment]
@drawcard Settings view -> packages -> linter -> `Ignored Message Types`
