### ISSUE TITLE
More tolerance to worng error positions

### ISSUE THREAD

**Issue by kachkaev** [steelbrain/linter#1188]
There is currently an issue in stylelint https://github.com/stylelint/stylelint/issues/1409 that is caused by an upstream https://github.com/webschik/postcss-less/issues/45. The result of both is that the positions of some errors are reported in a slightly wrong place when styelint is called from a command line. To be more precise, the column number becomes greater than the number of character in a line in certain cases. E.g. see line 11 here:

![atom linter](https://cloud.githubusercontent.com/assets/608862/16261956/8b98fa2e-3865-11e6-90b5-389c3db5c113.png)

It would be nice if Atom's linter was not so fragile in this situation and did not crash just because some error is reported in a wrong place. I know that this situation may happen only when there is a bug in the actual linter being used, but I still think that a bit more robustness will be a benefit. There are so many linters that can be linked to your package that the probability of the same situation in future becomes quite high. Could you please handle incorrectly reported error positions a bit nicer?

Project on the screen shot:
https://github.com/kachkaev/stylelint-less-issue-1409

**Comment by kachkaev** [comment]
BTW the same kind of problem occurs when Atom is configured to delete trailing empty lines on file save:

![linter-problem](https://cloud.githubusercontent.com/assets/608862/16264681/de096a52-3872-11e6-9991-2fbd50dc9434.png)

**Comment by steelbrain** [comment]
This is actually a detection for nasty bugs, it has helped us find bugs in software like ESLint and others. This should be fixed in the provider, cc @Arcanemagus

**Comment by kachkaev** [comment]
I can partially agree that nasty error messages for nasty bugs is a good thing since it's motivates the developers of linters. But what to do with the second case? This is no one's fault: Atom does it's job removing some extra lines and a linter does it's job linting the original file (before the lines were moved). This is clearly a UI glitch IMO.

**Comment by kachkaev** [comment]
Atom's linter currently stops showing any errors for any of the used linters if one of them fails like I mentioned above. I'm not sure this is a good way of 'punishing' a user for the bugs that linter developers haven't fixed yet. It may take a few weeks BTW.

**Comment by steelbrain** [comment]
Punishing the user is of course not the intention, in the next major release, linter is going to only halt execution of the providers with errors and the other ones will keep working without a problem.

If I recall correctly Atom core trims the strings before the linter providers are triggered, and if it does not then it's a bug in Atom core and should be fixed there. It would be improper to work this around in every package ever instead of deferring the saved event until the file is trimmed properly.

**Comment by kachkaev** [comment]
Would you like to completely hide the errors generated by faulty providers? Or will the problems that are reported correctly still show up as normal? In the current case of stylelint it often happens that a few errors are detected perfectly, just a couple of less-related ones have incorrect cols. Perhaps, an ideal scenario for a end-user would be to see as much errors as possible and some special (e.g. black-coloured) messages pointing to places when the provider failed. If a linter works totally fine via console except that a couple of messages are corrupt, why ignore all the remaining benefits it can still provide? :–)

**Comment by steelbrain** [comment]
I am in favor of showing this error in dev mode only and the `atom-linter` automatically correcting mistakes like these and covering the entire line as a fix for the faulty range

**Comment by Arcanemagus** [comment]
I'm really _not_ in favor of hiding these messages unless the user is in dev mode... _nobody_ runs Atom in dev mode normally, which means errors like this will be silently ignored by all users and never get reported.

_How_ the message is reported though I'm certainly open to, maybe instead of throwing an error it might be better to somehow have it caught and turned into an "issue" on the file. The problem I see with that is that often these bugs are due to very delicate interactions between a linter's different rules, the state of one causing the issue in another so if the user doesn't catch the message it might again never be seen.

What about an option, defaulting to `false`, to ignore invalid range errors?

**Comment by mehcode** [comment]
Just to throw in my few cents..

I recommend to add an option "debug" / "developer" / etc. mode to the linter. This option is _off_ by default. When the user first installs the linter (or updates to the version that has this mode) the linter will present a informational box asking the user to contribute to linter development by showing linter errors / etc. These are programmers/engineers/etc. you're talking to (in the general case). You will get enough people clicking "yeah sure I can willingly be annoyed by linter errors".

In the grand scheme, those sorts of people are very few. However.. the rest will just ignore the red error / disable linter altogether / be angry and write their own linter system / etc. anyway. Giving them the *option* in their face about it makes it at least feel like linter is pretending to care about (what I believe should be) the primary use case / goal for a linter, a good linter experience (not necessarily a correct linter, and auto-fixing problems with the linter plugins where possible is definitely a piece of that).

**Comment by kachkaev** [comment]
Any updates on this guys? Stylelint with less syntax is still unusable in Atom, because https://github.com/stylelint/stylelint/issues/1409 is not being fixed for several weeks. That minor bug combined with nasty error notices made me disable stylelint completely. Is there a way to handle rare _out of range_ errors nicer in order to keep enjoying the benefits of your tool?

**Comment by steelbrain** [comment]
This request of yours is very valid, can you please reopen this at the helper module repository [`atom-linter`](https://github.com/steelbrain/atom-linter), it's what's throwing this error.

Closing as external, feel free to continue discussion
