### ISSUE TITLE
Do not pop up an Error dialog!!!

### ISSUE THREAD

**Issue by warmhug** [steelbrain/linter#1189]
Suddenly a box pops up, this is very very bad. How to stop it ?
![image](https://cloud.githubusercontent.com/assets/2011119/16295321/c329acce-3958-11e6-86ac-0958155d60be.png)

**Comment by steelbrain** [comment]
This is a [`linter-eslint`](https://github.com/steelbrain/linter-eslint) error mate, the last time I checked, it was fixed by upgrading atom to latest version

**Comment by Arcanemagus** [comment]
The latest version should be telling you that your Atom is too out of date, v7.2.3 unfortunately didn't have that warning since we don't test on outdated versions and didn't catch that.
