### ISSUE TITLE
Show "xyz" Tab options not respected

### ISSUE THREAD

**Issue by 50Wliu** [steelbrain/linter#1191]
In particular, these three options:
![show-xyz-tab](https://cloud.githubusercontent.com/assets/2766036/16349231/88127fb2-3a25-11e6-80de-2636c09e06b0.png)
are no longer respected starting in at least linter@1.11.13, maybe linter@1.11.12 or even earlier (I'm not sure, sorry about that).

**Comment by steelbrain** [comment]
Interesting, does this persist after a restart?

**Comment by 50Wliu** [comment]
Yes.

**Comment by steelbrain** [comment]
I am unable to repro this on master, can we try an old school fix for this?
```
mv ~/.atom ~/.atom-backup
atom
```
and then try changing the configuration

**Comment by 50Wliu** [comment]
Negative.  Issue still occurs.

This is on Atom 1.10.0-dev-9705b3d and Windows 10 x64 by the way if that matters.

```cson
"*":
  linter:
    showErrorTabFile: false
    showErrorTabProject: false
  welcome:
    showOnStartup: false
```

**Comment by steelbrain** [comment]
Can you retry this on Atom stable?

**Comment by 50Wliu** [comment]
Atom 1.8.0 works fine.  Trying 1.9.0-beta0 now.

**Comment by 50Wliu** [comment]
1.9.0-beta0 also doesn't have any issues, but the problem persists with 1.10.0-dev-9705b3d.

**Comment by steelbrain** [comment]
It was some css issues that have now been fixed
