### ISSUE TITLE
Error panel sweat

### ISSUE THREAD

**Issue by WoodyWoodsta** [steelbrain/linter#1193]
Hey! I'm having similar frustrations as in https://github.com/steelbrain/linter/issues/1143 when typing at the bottom of a file longer than the height of the editor. As errors are linted (continuous linting) the error panel resizes the editor area so that the code jumps around which is extremely annoying. This is the most evident when I have the panel show errors based on the line the cursor is at, which is what I would like.

I'd disable the error panel, but the tootltip/bubble, as it stands, is also pretty invasive and can get in the way of the code due to it being triggered by the position of the cursor. Making the update interval longer is not a solution IMO.

https://github.com/steelbrain/linter/issues/885 would have been a great alternative, but I am unclear as to why this was closed?

**Comment by steelbrain** [comment]
@WoodyWoodsta #885 is already done in linter-ui-default, we'll publish it in a few weeks. If you wanna see it out quicker I would love to accept some PRs. Or alternatively you'll find instructions on how to make it work before it's published in it's README

**Comment by WoodyWoodsta** [comment]
@steelbrain Apologies - I didn't see that the issue was closed through a PR. Got `linter-ui-default` up and riding and works great :+1: Looking forward to the publish!
