### ISSUE TITLE
Message types should be case insensative

### ISSUE THREAD

**Issue by tonyxiao** [steelbrain/linter#1194]
So `error` should be acceptable, not just `Error`.
Ditto for `warning` vs. `Warning`. 

Linked issues
https://github.com/joefitzgerald/builder-go/pull/6#issuecomment-229624868
https://github.com/joefitzgerald/gometalinter-linter/pull/39#issuecomment-229625354

**Comment by steelbrain** [comment]
This will be fixed in the new release where we'll have `severity` :)
I'll keep this open until it's fixed

**Comment by steelbrain** [comment]
Done (not yet released, but closing anyway to keep only unresolved issues open for easy view)
