### ISSUE TITLE
can't download linter in Atom

### ISSUE THREAD

**Issue by dawnwish** [steelbrain/linter#1195]
now I can't find out "linter" in atom install panel, and https://atom.io/packages/linter can't download too

**Comment by Arcanemagus** [comment]
Are you getting any errors? Are you able to install other packages?

**Comment by steelbrain** [comment]
Please note that there's a lot of packages with the same name and it's difficult to `search` for linter, you can try opening a bug in Atom asking for a fix in their search algo or you can just use the cli like
```
apm install linter
```

Is that what you were asking?

**Comment by dawnwish** [comment]
thank you!  Maybe it's a bug in Atom's search algo, now if I search keyword "linter" it doesn't in the result list.

Steps to reproduce:
open atom -> file -> settings -> install -> input "linter" in the search bar and click "packages" button

I think Linter should be the first package in the result list.

Fortunately, linter-eslint and other plguins will install linter automaticly.

**Comment by steelbrain** [comment]
Yeah I think that too, can you please tell the Atom folks about this?
Closing as this is unrelated to this package, Thanks!

**Comment by Arcanemagus** [comment]
FYI, this is already filed here: https://github.com/atom/settings-view/issues/513
