### ISSUE TITLE
Linter does not check the entire project

### ISSUE THREAD

**Issue by tonyxiao** [steelbrain/linter#1198]
Originally thought it's an issue with Linter-eslint. Turns out it doesn't work for other atom linters either. https://github.com/AtomLinter/linter-eslint/issues/634

-- issue reported  on linter-eslint --
I'm having trouble getting eslint atom to check the entire project. I need to open each of the files I want to check individually before eslint errors would show up in issues navigator.

Result from running `npm run lint` on the console. 
![image](https://cloud.githubusercontent.com/assets/696842/16707569/a8ce96aa-45d3-11e6-8cc3-11cc96e5910a.png)

Before navigating to 'sendbird.js'
![image](https://cloud.githubusercontent.com/assets/696842/16707571/b47307de-45d3-11e6-8d66-349ea0b28a55.png)

After navigating to 'sendbird.js'
![image](https://cloud.githubusercontent.com/assets/696842/16707574/bc4a6826-45d3-11e6-969f-14eb9d7b5adb.png)

I'm using Nuclide instead of `linter`. Not sure if that changes anything. Fwiw nuclide's flow shows error for the entire project properly, not just current file.

--- 

Just disabled nuclide and tried with built in linter. It's even worse in terms of aggregating errors across the project. It would only show error for currently open tabs. As soon as I close those tabs the errors just go away.

![image](https://cloud.githubusercontent.com/assets/696842/16707600/d524b8fa-45d4-11e6-98ef-3ad224fe6fb8.png)

**Comment by steelbrain** [comment]
That project tab actually just "shows" errors from the entire project collected from opened tab. It's mainly useful when you have project scoped linters (like FlowType and stuff).

Anyways the next major release is gonna remove all these ambiguities and will make stuff simpler

**Comment by steelbrain** [comment]
If you want to get project-scoped messages in linter for flow, you should install one of the flow linters (I personally use `flow-ide`)

**Comment by tonyxiao** [comment]
Actually spoke too soon. Project scoped linting does work for linter-flow. It does not however work with linter-eslint.

Flow
![image](https://cloud.githubusercontent.com/assets/696842/16707723/078ba39a-45d9-11e6-8afb-a7ebbe62ccfa.png)

Eslint error only shows up after opening tab
![image](https://cloud.githubusercontent.com/assets/696842/16707733/496954c4-45d9-11e6-8e48-5fb1c87ac57e.png)


Edit: Doesn't work 100% of the time with linter-flow either. Not sure what conditions triggers it.

**Comment by tonyxiao** [comment]
also just realized there's `flow-ide` and `ide-flow`. LOL.

**Comment by tonyxiao** [comment]
And by personally use `flow-ide` you mean you personally developed flow ide? :P 👍 

https://github.com/steelbrain/flow-ide

**Comment by steelbrain** [comment]
Yeah `linter-flow` is buggy, therefore I use flow-ide as mentioned above. Also ESLint does not support project-scoped linting in neither Nuclide nor Linter.

Also you should subscribe to https://github.com/steelbrain/linter/issues/1145

Closing as duplicate, but feel free to continue discussing

**Comment by tonyxiao** [comment]
Hmm, flow-ide doesn't seem to work interactively, with the linter package.

**Comment by steelbrain** [comment]
Yeah it's a flow-ide thing, I personally think lint as you type is too intrusive

**Comment by tonyxiao** [comment]
Just to clarify, the reason lint current file is useful is that when developing with live reload / hot reload enabled, saving file would trigger the app to reload and state to be lost. So saving a file just to check flow / lint errors (other than the extra keystroke) is not ideal because it causes interruption in development context and might require one to navigate in the UI back to the original state again.

**Comment by tonyxiao** [comment]
That being said I can definitely see sometimes wanting to be in a "zen" mode and turn off linting to focus

**Comment by steelbrain** [comment]
Can you open an issue in flow-ide requesting lintOnFly support?

**Comment by tonyxiao** [comment]
Done.
