### ISSUE TITLE
Handle unfollowable file links correctly

### ISSUE THREAD

**Issue by alygin** [steelbrain/linter#1200]
There're situations when the correct file path cannot be provided for a Linter message. For instance, a compiler message might point to a file of the language core or a standard library that doesn't exist on the local machine. For example, [this issue](https://github.com/AtomBuild/atom-build-cargo/issues/41) is about dealing with such cases in the Rust language.

Linter requires a file path to be provided and always creates a link out of it, even if the file doesn't exist. When a user follows such a link, he or she ends up with a new empty tab which is rather confusing.

I can suggest several solutions:

 1. Check the file existence and make no link if it doesn't exist. It will work in all cases but will worsen responsiveness.
 2. Check the file existence before opening it and show a warning if it doesn't exist.
 3. Add a flag to the message that would prevent Linter from creating a link (though the file path still must be displayed, of course, with some additional style). No performance penalty here but some developers might forget to set the flag where needed.

Personally I would go with the last option. But maybe there're other ideas or workarounds that I missed. What do you think?

**Comment by steelbrain** [comment]
Hi @alygin Linter actually has an optional `filePath`, though it'll be enforced in the next version of the linter API (Linter 2.0!).

I am confused as to why the errors would be shown when the error is in the core of library, the concept of `filePath` is actually the opposite! It should point to the file where the error is so the person can check which file in their project needs to be fixed. If you are talking about the traces however, they too have optional file paths which can be omitted and in the future would be replaced by `description`s in messages

**Comment by alygin** [comment]
Hi @steelbrain! Oh, sorry, then it must be some component in between that checks the file path in my case. But since you're going to enforce the same rule, I think the discussion might be relevant here.

Regarding the situation I described, it occurs when an error happens not in the compile-time (so, the source code is ok from the point of view of the compiler) but in the run-time. I understand that Linter was not designed for handling such errors but the truth is it plays well in test scenarios and might show test failures, including those caused by some unhandled errors. Such errors are sometimes originated inside the core libraries and the error messages point to them. In case we have the core source code installed, the path might be corrected before passing to Linter and it's quite handy to be able to jump right to the the place the error was produced even if it's not our own code. But when we have no such code at hand, the file link cannot be properly prepared.

Unfortunately, the information in the error message is not enough to connect the error to our source code and use the original message as a trace element with no file link. As the result, we have two options: either not to use Linter in such scenarios or to provide it with broken file paths. Since Linter is quite handy even with broken links, I think the former is very unlikely option )  So, it would be good to find the solution for the latter.

While `filePath` is optional, I can use `message` or `html` to get the desired result. But if you make it required, such possibility will gone.

**Comment by steelbrain** [comment]
Interesting situation @alygin, if the error is at runtime and is in core libraries that have no file path, I personally would show a notification for that. I actually do that in flow-ide and similar packages.

Do you think a notification would not work for your use case?

**Comment by alygin** [comment]
I agree that notifications should be preferred over Linter messages for run-time errors in general, but Linter has an advantage in the particular scenario that I'm talking about (running automated tests and showing their failures):

There're often more than one test failure per execution. Notifications are quite bulky even with no details attached. In the case I'm talking of, an execution stack trace is also attached to the failure message. Linter allows to hide such details in trace elements that are only displayed when the user needs them, otherwise the message is quite compact or even completely hidden in case there're many of them. One can easily have dozen of Linter messages without filling half of the user's screen with red banners like notifications do.

And to clarify a bit on the error in the core libraries code: When I say that errors are thrown from the core, it doesn't mean that the core libs are the cause of those errors and we must set off the alarm. Actually, its the opposite. The core, sort of, checks the program's behaviour and if it's incorrect, throws an error. So, I've got the core as the originator of the error and a link to a core's source file, though it's my program that works incorrectly.

It also worth mentioning that not all test failures produce unfollowable file links. Actually, most of them point to the project's source code and Linter handles them perfectly. From the testing point of view, there's no difference between such failures and failures originated in the core, they both are just signs of the program malfunction. This is another reason to not use different UI elements for them.

I assume, it's not exactly what you created Linter for, but it is one of the areas where it is useful. It's hard for me to say if other people use Linter in such manner. Maybe you're right and there must be some other solution.

**Comment by steelbrain** [comment]
Thank you for the clarification @alygin. The linter project helps other projects visualize errors to the user. While It does allow it's providers to create messages that are not strictly linting results, It will change in the upcoming releases. In the next major release of linter, we are dropping `type`s in favor of severities that have only three possible values (`error`, `warning`, `info`).

This is how it looks like
<img src="https://cloud.githubusercontent.com/assets/4278113/16748848/6608e38a-477b-11e6-9b8b-46137a6e3c42.png">

Along with that, the linter panel will also be disabled by default (it's still there, no need to panic people!) in favor of the new tree-view highlights as shown in the screenshots below

<img src="https://cloud.githubusercontent.com/assets/4278113/16748893/9ad1b2fe-477b-11e6-877f-99eee945b48e.png">

As evident from the pictures above, we're on the road to making Atom look more like an IDE and less like a Text Editor and to ease the process of writing code as much as possible without unnecessary intrusions. This vision comes at a cost of course, we cannot support every possible use case ever with this. We have to let down some of the ideas and use cases to make this more elegant and simple for the general public.

Unfortunately, your use case sounds like one of these. While I'm glad that Linter can handle most of the cases, I am sorry that it can't handle all. To be frank, a LOT of users have the panel disabled from their configs anyway so without a file path they would never know about that error in their opened files. So eventually you'd have to look for a new way to show them.

It could be as a notification but as you noted, notifications are too intrusive and not so beautiful for showing several chunks of information at once. Therefore I would request you to suggest a UI for such messages, we could look into creating a package or coming up with a solution that suits your needs the best :)

**Comment by alygin** [comment]
Thank you so much for sharing your plans, the changes look very promising. I think you're right to focus on the Linter's main purpose even though it doesn't cover all the scenarios Linter is being used now.

As soon as you're moving towards an IDE it would be great to have a package to visualise test results. Something that we have in more mature IDEs. There're several test runners but no test result visualisers for Atom. But that's surely not the Linter's responsibility, so the issue might be closed.
