### ISSUE TITLE
Package won't work

### ISSUE THREAD

**Issue by yaelber** [steelbrain/linter#1201]
Hey,
New to Atom. Just downloaded the package but for some reason I don't see any notifications when I have syntax error on Javascript.

**Comment by steelbrain** [comment]
Hi @yaelber. This package is just the base, to get errors in your Javascript code, you should install `linter-eslint`, `linter-standard` or `linter-xo` too, you should also look into each one's configuration. Have fun!

**Comment by yaelber** [comment]
I have both linter-xo and eslint installed.

Any idea what the issue could be?

**Comment by steelbrain** [comment]
That's interesting

I would recommend you uninstall `eslint` and install `linter-eslint` instead, and after that make sure you have enabled the `linter` package as well, then to test if they are working, try writing some javascript that xo doesn't like or your config doesn't like (usually double quotes like `var something = "hey"` works).

If that still doesn't work then we can discuss it on Atom Slack to come up with a solution
