### ISSUE TITLE
Option to configure the execution time and show if linter is running

### ISSUE THREAD

**Issue by Costallat** [steelbrain/linter#1202]
Hello, I don't know if this is possible, but would be nice if I could configure the execution timeout, because sometimes with a big file, the "linter" never finish, because execution is stopped in the middle.

Other problem is that I can't know when "linter" is running or not, it would be nice show somewhere that "linter" is running, so I can know when it finished! Today I have to save the file and wait looking to the screen to see if something happens!

In my case I am using: linter-*
- gcc
- cppcheck
- clang

**Comment by steelbrain** [comment]
This package is actually the base package and has no power over the providers other than trigering them, Unfortunately you might want to reopen this issue in every single one of the linter providers to make this happen.

**Comment by Costallat** [comment]
Okay, thanks!

I will open in each one of them!

**Comment by steelbrain** [comment]
Great 👍 
Happy linting!

**Comment by Arcanemagus** [comment]
Is the UI issue solved in the upcoming re-write? I don't remember actually seeing that there yet.

**Comment by steelbrain** [comment]
@Arcanemagus pushed the fix in the ui repo
