### ISSUE TITLE
Less intrusive error interface

### ISSUE THREAD

**Issue by jrajav** [steelbrain/linter#1203]
Currently, if there is an error with a linter itself (that is, the linter encountered a problem with its operation and didn't simply return a linting error) at all, linter comes up with a modal dialog that covers half the editor and must be manually closed. In addition, this dialog continues to pop up if you have "Lint As You Type" on. I understand that such an error isn't usually an issue to leave unresolved, but this is extremely annoying to deal with especially when I work on forked projects with an eslint config my settings don't expect (for instance), where I'd rather stay in the flow of the change I'm making rather than deal with my linter of all things. Could this be changed to show at most once per file load, and/or to be indicated with a much less intrusive persistent error footer or status bar marker?

**Comment by steelbrain** [comment]
This has been fixed in the linter UI rewrite. You'll have to wait for next major release for this.

Or you can just use the manual installation instructions mentioned in the README [here](https://github.com/steelbrain/linter-ui-default#installation)

**Comment by jrajav** [comment]
Awesome! Thank you! This only comes up every once in awhile so I will wait.
