### ISSUE TITLE
Option to display issue list in sidebar

### ISSUE THREAD

**Issue by rugk** [steelbrain/linter#1204]
I think every object which occupies too much height is wasted space on widescreens. Therefore what about an option to display the issues in a sidebar?

**Comment by steelbrain** [comment]
It would be nice to have a screenshot explaining the issue

**Comment by rugk** [comment]
![lintersidebar](https://cloud.githubusercontent.com/assets/11966684/16969183/6234258c-4e13-11e6-8d43-89b82b04b1d2.png)

I know expressive painting...

But does it clarify what I mean with sidebar here?

**Comment by steelbrain** [comment]
Well actually, if we add it to the side bar, it'll take at least as much space as a pane and because all of the text in it is vertical (except Japanese text) it won't be a very good idea.

Alternatively you could just disable panel and install `minimap` and `minimap-linter`

**Comment by rugk** [comment]
Yeah the text is of course the same, but you could just add some line breaks, so that it fits.
And as said in the width there is enough space (at least more than in height).

Additionally it should is course only be an option.
