### ISSUE TITLE
Feature: Ignore the Command Prompt when working with REPL

### ISSUE THREAD

**Issue by MuhammadHewedy** [steelbrain/linter#1207]
I don't know if this belongs to you or to the REPL package [https://github.com/T-800/REPL-Nodejs] but I put it here first if you have any suggestions.

The Repl package mentioned above outputs the prompt of the command into the TextEditor. (for example node or python or whatever it do REPL for) 

And this prompt character (in case of node it is the > character), is considered not correct according to the linter-jshint [https://atom.io/packages/linter-jshint] which depends on you.

<img width="632" alt="screen shot 2016-07-25 at 8 12 24 pm" src="https://cloud.githubusercontent.com/assets/1086049/17110290/f6fcd6a6-52a4-11e6-8ebb-e490e00c7524.png">

As it appears above, I don't know if you could escape the prompt character (but how would you know that it is the prompt character not just an invalid character?)

I am not sure if you could help fix it from your side, but it is a problem that need to be fixed.

P.S. To Test with Node REPL, you need install the package from the github.

**Comment by Arcanemagus** [comment]
This sounds like an issue with the REPL package incorrectly marking its interpreter window as real source code.

I'm not sure why it's marking it as source code _at all_, but you might want to file an issue over there to have them mark the scope as something like `interpreted.source.js` (as an example I just came up with off the top of my head). This way other packages (like `linter-jshint`) aren't going to try to interpret it as valid source code.

**Comment by MuhammadHewedy** [comment]
Thanks for your prompt and helpful comment, I'll try to search this issue from their side.

**Comment by MuhammadHewedy** [comment]
@Arcanemagus after reading your comment for the second time, I think I understood what you mean is that, for REPL not to make use of the linter inside of the REPL window, am I correct?

**Comment by Arcanemagus** [comment]
Yes, for some reason the REPL window is being marked as regular Javascript code, instead of "something that isn't a regular Javascript file".

Since the window is being marked as regular Javascript code, Linter is doing exactly what it should be doing and running all linter plugins that say they are compatible with Javascript code. As it isn't actually JS, you run into invalid messages like the ones you have in your screenshot.
