### ISSUE TITLE
Linter doesn't lint

### ISSUE THREAD

**Issue by wetherallCode** [steelbrain/linter#1211]
I just installed the linter and haven't done anything to configure or change it in anyway. The linter has done nothing but show that there are no issues no matter what I do. How do I get the linter to lint? Also, I'm kinda new to this, so be nice in case I'm not doing something obvious. Thank you in advance.

**Comment by steelbrain** [comment]
Linter is the base package, You should install some linter providers based on the languages you use, like `linter-eslint`, `linter-write-good` and others. Search for `linter` in Atom packages and you'll see them there

**Comment by Arcanemagus** [comment]
There is also a list available at https://atomlinter.github.io/.
