### ISSUE TITLE
Show XX tab in the status bar not working on Atom beta

### ISSUE THREAD

**Issue by albireox** [steelbrain/linter#1213]
The options to show or hide File/Project/Line in the status bar do not work on Atom beta 1.10.0-beta1. The three tabs are always shown regardless of which are ticked in the settings.

**Comment by steelbrain** [comment]
Do you experience the same if you do this?
```
mv ~/.atom ~/.atom-backup
apm install linter
```

**Comment by albireox** [comment]
Yes, starting with a fresh configuration does not seem to fix the problem. BTW, atom 1.10.0-beta2 just came out and the problem remains.

**Comment by steelbrain** [comment]
I can repro, investigating

**Comment by steelbrain** [comment]
Fixed in v1.11.15
