### ISSUE TITLE
Linter shows all errors for file in error pane when "line" tab is selected

### ISSUE THREAD

**Issue by bjmiller** [steelbrain/linter#1215]
Previously, when the "Line" tab was selected, the errors section at the bottom of the pane would only show the errors on the current line.  Now, it only shows all errors for the file, if the cursor is on any line with an error, whether "Line" or "File" is selected.  I'm not sure quite where this changed.

OS: OSX El Capitan 10.11
Atom version: 1.10.0-beta3 (This has been happening since at least 1.9-beta.)

![screen shot 2016-08-08 at 9 00 35 am](https://cloud.githubusercontent.com/assets/197747/17480659/f3813592-5d46-11e6-8e77-90b954517562.png)

![screen shot 2016-08-08 at 9 00 54 am](https://cloud.githubusercontent.com/assets/197747/17480665/fa5ad97c-5d46-11e6-9b7a-aff38752ee20.png)

**Comment by steelbrain** [comment]
Ah, just another css issue introduced in the new betas (because the count on tab is correct). Fixing

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/linter/commit/e167b5f1d620bd37abb179caac9ffa2713a3cb6f in v1.11.16
