### ISSUE TITLE
Linter and rule name are basically illegible in the default "light" UI themes

### ISSUE THREAD

**Issue by albell** [steelbrain/linter#1216]
Here's a linter popup in the 'Atom Light' theme:

![atom-light](https://cloud.githubusercontent.com/assets/1142025/17488950/924e86ee-5d50-11e6-8123-15d5f236d426.png)

And here's 'One Light':

![one-light-linter](https://cloud.githubusercontent.com/assets/1142025/17488954/9564fe12-5d50-11e6-8c84-de9d53bceef2.png)

Users don't want to have to hack core themes to get a basic linter working. This should really just work out of the box. Thanks for a great tool.

**Comment by steelbrain** [comment]
Oh well, I thought we fixed that a few releases ago. Can you also post your Atom version? Atom css has changed quite a lot in the recent versions/betas

**Comment by albell** [comment]
Yeah, I'm seeing this in current build, 1.9.6.

**Comment by steelbrain** [comment]
Are you on Atom Slack?

**Comment by albell** [comment]
nah, why?

**Comment by steelbrain** [comment]
If you were on Atom Slack, the conversation and thus the resolution to the issue would have been quicker as I would be able to ask you the repro steps, try to repro and post the result instantly

**Comment by steelbrain** [comment]
Anyways this is a theming issue with linter-eslint. cc @Arcanemagus 
Closing as offtopic, feel free to continue discussion

**Comment by albell** [comment]
Thanks, I am happy to follow this up with whomever. FWIW I am seeing a similar styling error on popups when using linter-scss-lint:


![screen shot 2016-08-29 at 10 32 25 am](https://cloud.githubusercontent.com/assets/1142025/18060991/c9dc0b64-6dd5-11e6-93ac-46ddacac4eb5.png)

which suggests this might be a broader issue. (JOOC I tried typing out some gibberish using python and C++ linters but those don't seem to currently support inline popups.)

**Comment by Arcanemagus** [comment]
The linter name issue is no longer relevant once [linter-ui-default](https://github.com/steelbrain/linter-ui-default) becomes the UI, as the name is no longer themed.

The `Shorthand` in your original screenshot though will still not show very well, can you file an issue on [linter-scss-lint](https://github.com/AtomLinter/linter-scss-lint/issues) about that?
