### ISSUE TITLE
Highlight error lines differently

### ISSUE THREAD

**Issue by pudymody** [steelbrain/linter#1218]
Hi, im making this question because i didnt find anything in the docs or in previous issues. I was wondering if it is possible to highlight in a different color lines who are marked as errors/warnings, like [jshint](https://atom.io/packages/jshint) did. If currently it isnt possible, im open to try to make a PR.

![Image example](https://i.github-camo.com/ba07bf907da960531cd85f4d96175f178dd91f42/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f3137303237302f333833343236362f35346164366231632d316461662d313165342d396334362d3938653665346162616230372e706e67)

**Comment by steelbrain** [comment]
Hi, The package you are using does not use this package for highlights. Use the `linter-jshint` package for that :)

**Comment by Arcanemagus** [comment]
@steelbrain I think they were requesting a way for linter to highlight the line with the message color, and were just using that as an example.

**Comment by steelbrain** [comment]
@Arcanemagus Ohh that makes sense 😛 
Even then, this should be reopened in the linter-ui-default repo

**Comment by pudymody** [comment]
Oh, i didnt know about that repo. Ok, i will open it there then.
