### ISSUE TITLE
Failed to install linter dependencies

### ISSUE THREAD

**Issue by SirZhai** [steelbrain/linter#1219]
These packages were not installed, check your console
for more info.
  • linter-ui-default

**Comment by steelbrain** [comment]
What does the console say?

**Comment by SirZhai** [comment]
$ npm install
linter@1.11.4 C:\Users\zishu\.atom\packages\linter
+-- atom-package-deps@4.2.0
| +-- atom-package-path@1.1.0
| | `-- sb-callsite@1.1.2
| `-- sb-exec@2.0.5
|   +-- consistent-env@1.2.0
|   `-- sb-npm-path@1.0.1
|     +-- sb-memoize@1.0.2
|     `-- sb-promisify@1.3.0
+-- babel-eslint@6.1.2
| +-- babel-traverse@6.13.0
| | +-- babel-code-frame@6.11.0
| | | `-- js-tokens@2.0.0
| | +-- babel-messages@6.8.0
| | +-- babel-runtime@6.11.6
| | | +-- core-js@2.4.1
| | | `-- regenerator-runtime@0.9.5
| | +-- globals@8.18.0
| | `-- invariant@2.2.1
| |   `-- loose-envify@1.2.0
| |     `-- js-tokens@1.0.3
| +-- babel-types@6.13.0
| | `-- to-fast-properties@1.0.2
| +-- babylon@6.8.4
| +-- lodash.assign@4.2.0
| `-- lodash.pickby@4.6.0
+-- coffee-script@1.10.0
+-- eslint@2.13.1
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- concat-stream@1.5.1
| | +-- inherits@2.0.1
| | +-- readable-stream@2.0.6
| | | +-- core-util-is@1.0.2
| | | +-- process-nextick-args@1.0.7
| | | +-- string_decoder@0.10.31
| | | `-- util-deprecate@1.0.2
| | `-- typedarray@0.0.6
| +-- debug@2.2.0
| | `-- ms@0.7.1
| +-- doctrine@1.2.2
| | +-- esutils@1.1.6
| | `-- isarray@1.0.0
| +-- es6-map@0.1.4
| | +-- d@0.1.1
| | +-- es5-ext@0.10.12
| | +-- es6-iterator@2.0.0
| | +-- es6-set@0.1.4
| | +-- es6-symbol@3.1.0
| | `-- event-emitter@0.3.4
| +-- escope@3.6.0
| | +-- es6-weak-map@2.0.1
| | `-- esrecurse@4.1.0
| |   `-- estraverse@4.1.1
| +-- espree@3.1.7
| | +-- acorn@3.3.0
| | `-- acorn-jsx@3.0.1
| +-- estraverse@4.2.0
| +-- esutils@2.0.2
| +-- file-entry-cache@1.3.1
| | +-- flat-cache@1.2.1
| | | +-- circular-json@0.3.1
| | | +-- del@2.2.2
| | | | +-- globby@5.0.0
| | | | | +-- array-union@1.0.2
| | | | | | `-- array-uniq@1.0.3
| | | | | `-- arrify@1.0.1
| | | | +-- is-path-cwd@1.0.0
| | | | +-- is-path-in-cwd@1.0.0
| | | | | `-- is-path-inside@1.0.0
| | | | +-- pify@2.3.0
| | | | +-- pinkie-promise@2.0.1
| | | | | `-- pinkie@2.0.4
| | | | `-- rimraf@2.5.4
| | | +-- graceful-fs@4.1.5
| | | `-- write@0.2.1
| | `-- object-assign@4.1.0
| +-- glob@7.0.5
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.5
| | | `-- wrappy@1.0.2
| | `-- once@1.3.3
| +-- globals@9.9.0
| +-- ignore@3.1.5
| +-- imurmurhash@0.1.4
| +-- inquirer@0.12.0
| | +-- ansi-escapes@1.4.0
| | +-- ansi-regex@2.0.0
| | +-- cli-cursor@1.0.2
| | | `-- restore-cursor@1.0.1
| | |   +-- exit-hook@1.1.1
| | |   `-- onetime@1.1.0
| | +-- cli-width@2.1.0
| | +-- figures@1.7.0
| | +-- readline2@1.0.1
| | | +-- code-point-at@1.0.0
| | | | `-- number-is-nan@1.0.0
| | | +-- is-fullwidth-code-point@1.0.0
| | | `-- mute-stream@0.0.5
| | +-- run-async@0.1.0
| | +-- rx-lite@3.1.2
| | +-- string-width@1.0.2
| | `-- through@2.3.8
| +-- is-my-json-valid@2.13.1
| | +-- generate-function@2.0.0
| | +-- generate-object-property@1.2.0
| | | `-- is-property@1.0.2
| | +-- jsonpointer@2.0.0
| | `-- xtend@4.0.1
| +-- is-resolvable@1.0.0
| | `-- tryit@1.0.2
| +-- js-yaml@3.6.1
| | +-- argparse@1.0.7
| | | `-- sprintf-js@1.0.3
| | `-- esprima@2.7.2
| +-- json-stable-stringify@1.0.1
| | `-- jsonify@0.0.0
| +-- levn@0.3.0
| | +-- prelude-ls@1.1.2
| | `-- type-check@0.3.2
| +-- lodash@4.15.0
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- optionator@0.8.1
| | +-- deep-is@0.1.3
| | +-- fast-levenshtein@1.1.4
| | `-- wordwrap@1.0.0
| +-- path-is-absolute@1.0.0
| +-- path-is-inside@1.0.1
| +-- pluralize@1.2.1
| +-- progress@1.1.8
| +-- require-uncached@1.0.2
| | +-- caller-path@0.1.0
| | | `-- callsites@0.2.0
| | `-- resolve-from@1.0.1
| +-- shelljs@0.6.1
| +-- strip-json-comments@1.0.4
| +-- table@3.7.8
| | +-- bluebird@3.4.1
| | +-- slice-ansi@0.0.4
| | +-- tv4@1.2.7
| | `-- xregexp@3.1.1
| +-- text-table@0.2.0
| `-- user-home@2.0.0
|   `-- os-homedir@1.0.1
+-- eslint-config-airbnb@6.2.0
+-- eslint-plugin-react@4.3.0
+-- jasmine-fix@1.0.1
+-- minimatch@3.0.3
| `-- brace-expansion@1.1.6
|   +-- balanced-match@0.4.2
|   `-- concat-map@0.0.1
`-- sb-debounce@1.0.2

**Comment by SirZhai** [comment]
is this it?

**Comment by steelbrain** [comment]
I actually meant your dev console, you can access it in toolbar (view -> developer tools -> developer console)

**Comment by SirZhai** [comment]
Error: gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp http GET https://atom.io/download/atom-shell/v0.37.8/SHASUMS256.txt
gyp http GET https://atom.io/download/atom-shell/v0.37.8/x64/node.lib
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node.lib
gyp WARN install got an error, rolling back install
gyp

**Comment by steelbrain** [comment]
Wow, that's weird. Any ideas how to repro this behavior on a fresh install?

**Comment by SirZhai** [comment]
I have reinstalled once, but still so.

**Comment by SirZhai** [comment]
I was installed plug-in by local.

**Comment by steelbrain** [comment]
Can you try with a completely fresh profile?
```
mv ~/.atom ~/.atom-bkp
mkdir -p ~/.atom/packages
git clone https://github.com/steelbrain/linter
cd linter
apm install
```
and then open Atom. Also this will install the experimental version, you should just do
```
apm install linter
```
and you'll get the latest stable version

**Comment by SirZhai** [comment]
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp WARN install got an error, rolling back install
gyp

**Comment by SirZhai** [comment]
Still not

**Comment by steelbrain** [comment]
There is no reason for it to be installing `atom-shell`, because it was renamed to `electron` a while ago, are you sure you're on the latest version of Atom?

**Comment by SirZhai** [comment]
1.9.8

**Comment by steelbrain** [comment]
Well your setup is messed up man, it shouldn't, in any case, be downloading `atom-shell`, because it's `electron` now.

If you can provide repro steps, detailed with os information and screenshots I can debug further and try to repro it locally

**Comment by SirZhai** [comment]
I is based on you give me the steps to re-install the plug-ins. My computer operating system is win10 64-bit

**Comment by steelbrain** [comment]
Can you remove the git repo path and stuff and just install from the settings view? Or if you install any linter dependent package, it'll automatically install the base linter

**Comment by steelbrain** [comment]
Closing as no info provided for two weeks

**Comment by stivlead** [comment]
Hi, steelbrain,
I tried installing linter-jscs which didn't signal any mistakes which I visibly saw were wrong.
On the other hand, I installed linter-jshint and it said: Failed to install linter-jshint dependencies
These packages were not installed, check your console
for more info.
  • linter

This is what the console says: 
text-editor-component.coffee:734 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
text-editor-component.coffee:734 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
task.coffee:84 spell-check:en-us Can't load en_US: Cannot find dictionary for en_US.
message-registry.js:41 Uncaught (in promise) Error: Given editor is not really an editor(…)
4package-card.coffee:143 No available version compatible with the installed Atom version: 1.12.9(anonymous function) @ package-card.coffee:143
C:\Users\stiva\.atom\packages\linter-jshint\node_modules\atom-package-deps\lib\view.js:64 [Package-Deps] Unable to install linter, Error: TypeError: spawnedProcess.start is not a function
    at C:\Users\stiva\.atom\packages\linter-jshint\node_modules\atom-package-deps\lib\helpers.js:161:20
    at exec (C:\Users\stiva\.atom\packages\linter-jshint\node_modules\atom-package-deps\lib\helpers.js:144:10)
    at C:\Users\stiva\.atom\packages\linter-jshint\node_modules\atom-package-deps\lib\helpers.js:168:12
    at Array.map (native)
    at Object.apmInstall (C:\Users\stiva\.atom\packages\linter-jshint\node_modules\atom-package-deps\lib\helpers.js:167:35)
    at C:\Users\stiva\.atom\packages\linter-jshint\node_modules\atom-package-deps\lib\index.js:25:32
    at next (<anonymous>)
    at step (C:\Users\stiva\.atom\packages\linter-jshint\node_modules\atom-package-deps\lib\index.js:66:191)
    at C:\Users\stiva\.atom\packages\linter-jshint\node_modules\atom-package-deps\lib\index.js:66:361complete @ C:\Users\stiva\.atom\packages\linter-jshint\node_modules\atom-package-deps\lib\view.js:64
8text-editor-component.coffee:422 TextEditorScrollView scrolled when it shouldn't have.

I don't understand anything. Please help me, 
Thank you!

**Comment by Arcanemagus** [comment]
@stivlead For future reference commenting on an unrelated issue 2.5 years after the last message is a _terrible_ way to get support.

You version of Atom is old enough that it broke telling you that it was too old:
> No available version compatible with the installed Atom version: 1.12.9

Please update to the latest version of Atom.
