### ISSUE TITLE
CLI installed package fails update in Atom app

### ISSUE THREAD

**Issue by AndreAmo** [steelbrain/linter#1220]
Hi everyone, a couple of months ago I installed the package via CLI and as far as I can remember it requested me to use the sudo command before it. Now, today I was trying to update it in the app but it always failed giving me permission errors. I solved it updating it via CLI and using sudo again.
I'm aware that it's a fairly edge case and I'm not even sure if it's an intended behaviour but as for my experience with other packages I never had issue mixing the two methods (CLI and App). I'm also not sure why it required me to use sudo and I don't know if it's an issue that depends by my system or presents to everyone. Anyway I thought it would help to report it.

Info:
- Current package version 1.11.14, updating to 1.11.16 via package updater
- Atom 1.9.8 on Mac OS X 10.11.6

Here's a gif showing the issue, as you can see it happens immediately
![issue](https://cloud.githubusercontent.com/assets/7353869/17665500/b3f5d2e2-62fb-11e6-9f70-6d0eaa1f8f9a.gif)

The dev console throws the following error:
> /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:717 Updating package linter to v1.11.16 failed:
>  Error: Updating to “linter@1.11.16” failed.(…) EACCES, unlink '/Users/Andre/.atom/packages/linter/.editorconfig'

While there isn't anything related to it in the Console.app.

**Comment by steelbrain** [comment]
Sounds like a weird Atom issue, do this instead
```
$ rm -rf ~/.atom/packages/linter
$ apm install linter
```

**Comment by AndreAmo** [comment]
It was definitely something wrong on my end or as you said in Atom. Just for future reference:
I've deleted it (sudo required) as you suggested and reinstalled 1.11.14 via apm (without sudo), now it upgrades smoothly.
