### ISSUE TITLE
'function' in namespace 'std' does not name a type

### ISSUE THREAD

**Issue by MidoAssran** [steelbrain/linter#1222]
I have this line of code:
`std::function<String(String)> _callback; 
`
So everything compiles fine because in the .gcc-flags.json file in platformIO "-std=c++11" is included, but the linter still shows the warning:
`'function' in namespace 'std' does not name a type`

**Comment by steelbrain** [comment]
This report actually belongs to the platform io linter provider :)
This repo is just the base linter, please reopen this there
