### ISSUE TITLE
Linter errors showing even if already fixed

### ISSUE THREAD

**Issue by sk22** [steelbrain/linter#1227]
This does not happen always, but sometimes.

In my case, it happened when using ESLint:

The bottom bar says "No Issues", however there is a floating atom-overlay showing and the counter at the bottom left says "File 5", as you can see in the screenshot.

This happens just while coding, I didn't do anything special. It goes away when reopening the file.

![Screenshot](http://i64.tinypic.com/2h2jf48.png)

**Comment by steelbrain** [comment]
Fixed in master, wait for next release

**Comment by steelbrain** [comment]
Also if I recall correctly this had been fixed in v1 as well, can you make sure you're on the latest v1 of linter?

**Comment by 22sk** [comment]
I'm running `linter` 1.11.16 by `atom-community`.

**Comment by steelbrain** [comment]
Well it's the latest in v1, not sure why you're still seeing it, well it's fixed anyway in the new version anyway 😄

**Comment by 22sk** [comment]
Well, okay, thanks! ;)

**Comment by steelbrain** [comment]
Linter v2 is finally out people. You can read more about it in the [release post](http://steelbrain.me/2017/03/13/linter-v2-released.html).
