### ISSUE TITLE
inline popup misplaced with minimap on the left

### ISSUE THREAD

**Issue by jacekkopecky** [steelbrain/linter#1230]
Hi, as shown in the attached screenshot, when I have minimap on the left, the linter popup is misplaced. (my cursor is green, the popup should be close to it)

<img width="745" alt="screen shot 2016-09-01 at 14 01 23" src="https://cloud.githubusercontent.com/assets/807315/18168264/c27e01b4-704c-11e6-88ec-4236b2131017.png">

**Comment by Arcanemagus** [comment]
What do you have the tooltip set to follow? Keyboard or mouse?

**Comment by jacekkopecky** [comment]
I have linter v1.11.16 and it only follows the editing cursor; can't find a way to choose that it would follow the mouse. Atom 1.10.0.

**Comment by steelbrain** [comment]
Linter v2 is finally out people. You can read more about it in the [release post](http://steelbrain.me/2017/03/13/linter-v2-released.html).

**Comment by Arcanemagus** [comment]
![image](https://cloud.githubusercontent.com/assets/427137/23923608/85547b86-08c4-11e7-8456-1e0d8b03640b.png)

This is definitely still a bug, reopening on `linter-ui-default`.

**Comment by Arcanemagus** [comment]
Hmmm, actually, this seems like an odd transitionary bug, after switching it to the left I could reproduce this for a bit, but on trying to get more information I can't. It might be an Atom bug, or just a side effect of how minimap moves itself around.

**Comment by jacekkopecky** [comment]
I may be able to have a look if I can reliably reproduce it with linter 2; but possibly not before next week.
