### ISSUE TITLE
Cannot get linter to work

### ISSUE THREAD

**Issue by demisx** [steelbrain/linter#1238]
Hi,

I am new to Atom and just downloaded the latest 1.10.2 for Mac OS X. For some reason, I cannot get linter to start showing errors. For example, when I introduce errors intentionally to `package.json` they get highlighted in red (perhaps by some core plug-in), but the status bar still reports "No Issues" (please see attached image). Am I missing something?

![screen shot 2016-09-10 at 8 58 12 am](https://cloud.githubusercontent.com/assets/4452412/18411835/2bb051a2-7735-11e6-8362-254498cda18d.jpg)

**Comment by steelbrain** [comment]
This is the base linter package. You also have to install language-specific providers, You can find them on http://atomlinter.github.io

**Comment by demisx** [comment]
Sorry, didn't realize that. Thank you for your prompt response and solution to the problem.
