### ISSUE TITLE
Errors Get Stuck After Language Change

### ISSUE THREAD

**Issue by JamesCoyle** [steelbrain/linter#1239]
Any errors present before the language is changed seem to get stuck in the linter panel. You have to change the language back and fix the errors to remove them. It seems to me like the linter package needs to clear any errors on language change and relint the file for the new language.

**Comment by steelbrain** [comment]
Good catch

**Comment by steelbrain** [comment]
**Workaround**: Close and reopen the text editor.

I'll push a fix soon.

**Comment by ryanjbonnell** [comment]
I can confirm this bug exists when using Atom 1.12.9 and Linter 1.11.18 on macOS 10.12.2 "Sierra.

I'm also able to confirm the workaround -- of closing and re-opening the editor window -- temporarily resets the Linter language.

**Comment by steelbrain** [comment]
@ryanjbonnell you shouldnt need to restart the window, just the tab whose grammar has changed.

Fixed as of https://github.com/steelbrain/linter-ui-default/commit/e03b473e55cefaafd32758e2d973e8da09788301 will be released as part of v2
