### ISSUE TITLE
Linter finds no issues

### ISSUE THREAD

**Issue by barbalex** [steelbrain/linter#1240]
I am completely lost. No Idea how to solve this. No idea where to place an issue.

A few months ago I changed from sublime text to atom. Seems like in atom you can`t show linter errors in the console? Or have I just not found this functionality?

I am running:
- atom 1.10.2
- linter 1.11.6
- linter-eslint 7.3.1
- jsonlint 1.1.4

In package.json are:
- "eslint": "3.5.0"
- "eslint-config-airbnb": "11.1.0"
- "eslint-plugin-import": "1.15.0"
- "eslint-plugin-jsx-a11y": "2.2.2"
- "eslint-plugin-react": "6.2.1"

Suddenly I get no more linting warnings, in all my projects:
- none inline
- a green "No Issues" in the bottom right of atom

This happens even if I write complete crap in a .js file.

This issue is driving me nuts: It is hard to work productively without a linter...

**Comment by steelbrain** [comment]
Yo, this is not actually a linter issue but a provider **feature**. ESLint will only activate if you have `.eslintrc.json` in your project root. Try adding that and then it'll lint your js files.

Alternatively you could just write some invalid syntax stuff in a json file to confirm that it works.

**Comment by barbalex** [comment]
I DID have an `eslintrc.json` file. But without the leading `.` :-(
Sorry for bugging you and thanks for helping!

**Comment by steelbrain** [comment]
No problem, glad you figured it out. 👍
