### ISSUE TITLE
Error: spawn ruby ENOENT

### ISSUE THREAD

**Issue by Abz2604** [steelbrain/linter#1241]
Error: spawn ruby ENOENT
Error: 'rubocop' is not recognized as an internal or external command, operable program or batch file.

I saw the previous issue for this however, the solutions there did not solve my problem and the issue is closed now.

I'm using atom 1.6.0 on my Windows 10.
I have also installed the bash for windows, with which i intend to work on ruby on rails.

Please help

**Comment by steelbrain** [comment]
You need to install `ruby` on windows and make sure it's in your `PATH` environment variable

**Comment by Abz2604** [comment]
I have ruby installed in my bash for windows. Any help with how to configure that into my path?
Much appreciated.

**Comment by steelbrain** [comment]
Bash on Windows doesn't play well with external programs at the moment, see https://github.com/Microsoft/BashOnWindows/issues/2
Even if it did, you'd have to rewrite the `linter-rubocop` to spawn `cmd.exe` to spawn `bash.exe` to spawn `rubocop`

**Comment by Abz2604** [comment]
Alright. I'll look into this further.
Thanks brains-of-steel.
