### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by smelukov** [steelbrain/linter#1247]
Hello!
https://github.com/steelbrain/linter/blob/master/docs/examples/indie-linter-v2.md
This example does to work.
`activate`-method is performed, but `consumeIndie`-method is not.
What's wrong with it?

**Comment by Arcanemagus** [comment]
Are you using the development version of Linter that supports API v2? The currently released version is documented [here](https://github.com/steelbrain/linter/wiki/Linter-Indie-API).

The Indie API is where most of the v2 changes are happening though...

**Comment by smelukov** [comment]
Oh, you're right.
I'm using current released version 😳
