### ISSUE TITLE
When line is indented with tabs, the undeline is inccorect

### ISSUE THREAD

**Issue by surdu** [steelbrain/linter#1249]
linter: `v1.11.16`
linter-jshint: `v2.1.0` (if it matters)
atom: both `v1.11.0 - beta5` and `v1.10.2`

When the line is indented with spaces, the warning undeline looks ok:
<img width="314" alt="screen shot 2016-09-26 at 19 33 16" src="https://cloud.githubusercontent.com/assets/11520795/18843282/c609cbf0-8420-11e6-89b9-9645404ca16c.png">

Not when indented with tabs:
<img width="333" alt="screen shot 2016-09-26 at 19 33 25" src="https://cloud.githubusercontent.com/assets/11520795/18843288/cf17dd54-8420-11e6-9ed1-516238ebda1d.png">

**Comment by Arcanemagus** [comment]
It's extremely likely this is a bug in `jshint` itself. Can you file this on `linter-jshint` with a file that shows this issue, and the `.jshintrc` file you are using? We can trace down exactly what is going on there.
