### ISSUE TITLE
Question: Linter runs only on file save?

### ISSUE THREAD

**Issue by amilajack** [steelbrain/linter#1251]
I am developing an ESLint plugin and I'm having trouble understanding why my plugin isn't updating errors while typing.

![flow_on_the_fly_save](https://cloud.githubusercontent.com/assets/6374832/19016823/0ff581fc-87da-11e6-8180-3e00a99c8d4b.gif)

Other rules like `no-comma-dangle` work just fine. [Here is](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/src/index.js) the file that reports errors to eslint. It does run while typing but errors aren't reported before file save--only after.

Any ideas?

**Comment by steelbrain** [comment]
Are you sure you have enable "Lint on Fly" or "Lint as you type" from the config?

**Comment by amilajack** [comment]
Is this an ESLint configuration?

**Comment by steelbrain** [comment]
It's an Atom configuration

**Comment by amilajack** [comment]
<img width="449" alt="screen shot 2016-10-01 at 2 29 09 pm" src="https://cloud.githubusercontent.com/assets/6374832/19017094/70e12e5e-87e3-11e6-84e3-b9659105e1fc.png">

**Comment by steelbrain** [comment]
What's the value of the config below? (the interval)

**Comment by amilajack** [comment]
It is the default (300). Does `linter` rely on some kind of eslint caching mechanism?

**Comment by steelbrain** [comment]
I don't remember having any caching mechanism. Does lint on fly work with jshint? If it works with jshint then it might be an eslint-only issue

**Comment by amilajack** [comment]
I'm close this and open an issue in `linter-eslint`. Thanks!
