### ISSUE TITLE
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by monski** [steelbrain/linter#1252]
npm i -g eslint eslint-plugin-react

Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.module.exports.load (C:\Users\Monski\.atom\packages\linter-eslint\node_modules\eslint\lib\config\plugins.js:114:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (C:\Users\Monski\.atom\packages\linter-eslint\node_modules\eslint\lib\config\plugins.js:136:21)
    at Object.load (C:\Users\Monski\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:505:21)
    at loadConfig (C:\Users\Monski\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:64:33)
    at new Config (C:\Users\Monski\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:197:38)

**Comment by steelbrain** [comment]
This is actually being thrown from `linter-eslint`, and is because you have

1. An invalid configuration or
2. Have not installed the plugin you reference in your config in your project

**Comment by monski** [comment]
Hi,
Here's my config

{
    "env": {
        "browser": true,
        "es6": true
    },
    "settings": {
      "react": {
        "createClass": "createClass",
        "pragma": "React",
        "version": "15.0"
      }
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
    "react/jsx-uses-react": "error",
    "react/jsx-uses-vars": "error",
    "no-console": 0
  }
}

**Comment by steelbrain** [comment]
Have you installed `eslint-plugin-react` in your project? (like with `npm install --save-dev eslint-plugin-react`?)

**Comment by monski** [comment]
yes i have

**Comment by monski** [comment]
i have done this also: npm i -g eslint eslint-plugin-react

**Comment by steelbrain** [comment]
okay can you post a dump of these?
```
$ ls node_modules | grep eslint
$ eslint --version # <-- don't worry if this throws an error
```

**Comment by monski** [comment]
hi sorry, im using windows...

i have done this.. eslint --v and got
v3.7.0

**Comment by steelbrain** [comment]
I am not much experienced with the workings of eslint. I would however advise you to uninstall the global version and reinstall everything locally. If the problem still persists, please reopen this in `linter-eslint` repo

**Comment by monski** [comment]
ok thanks alot..

**Comment by monski** [comment]
i got it worked now...thanks for the suggestions..got it all uninstalled and installed only locally...wew i was stuck in hour for this.... works fine now after re-installing locally only

**Comment by Arcanemagus** [comment]
It's highly recommended to always install it locally in your project, global installations, although they can be made to work, just lead to all sorts of issues. :wink:
