### ISSUE TITLE
Changes required for upcoming CoffeeScript upgrade

### ISSUE THREAD

**Issue by maxbrunsfeld** [steelbrain/linter#1253]
Hi! I see you've stopped using CoffeeScript. I'm giving you this heads up anyway because the current release of `linter` still uses CoffeeScript.

In Atom v1.12, we are going to [upgrade CoffeeScript](https://github.com/atom/atom/pull/12780) to the latest version. This upgrade entails one potentially breaking change to the language:

> Changed strategy for the generation of internal compiler variable names. Note that this means that @example function parameters are no longer available as naked example variables within the function body.

The current release (1.11.16) will be affected by this upgrade, in the following places:

* The `state` variable [here](https://github.com/steelbrain/linter/blob/d5cbf6beac983e008dbd068bf8c2a299c7bbbc86/lib/main.coffee#L131)

I think as long as you do a new release before Atom v1.12 ships (next week) everything will be fine. Otherwise, Atom Beta users won't be able to use linter. Thanks!

**Comment by steelbrain** [comment]
Taken care in v1.11.17
Thank You! Appreciate the heads up 🌹

**Comment by maxbrunsfeld** [comment]
Hey, sorry for not giving an exhaustive list. I see one other case of this pattern:

https://github.com/steelbrain/linter/blob/360d7dbea8e69eed4cdcf1b43799b4a1e5195013/lib/linter.coffee#L26

**Comment by steelbrain** [comment]
Oh that `@state` is actually a property on the class instance, not a static property on the package object so I think it would be fine (unless I am misunderstanding)

**Comment by maxbrunsfeld** [comment]
On line 26 it's referred to as `state` (not `@state`). I'm seeing the error `state is undefined` on Atom master.

**Comment by Arcanemagus** [comment]
Ouch, this makes me glad I'm converting the `linter-*` providers to JS as I go through them...

**Comment by steelbrain** [comment]
Wow, sorry, fixing

**Comment by steelbrain** [comment]
Fixed in v1.11.18
and manually confirmed this time
