### ISSUE TITLE
When I slide the page, the message is still displayed in the floating layer information display area

### ISSUE THREAD

**Issue by waitnoww** [steelbrain/linter#1256]
When I slide the page, the message is still displayed in the floating layer information display area
http://7xw4pa.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20161007105213.jpg

**Comment by steelbrain** [comment]
This is an Atom css issue. We can't really solve it here, it's been brought up several times.

@Arcanemagus might have the issue id in atom that you should watch

**Comment by Arcanemagus** [comment]
I can't find it easily, from what I remember the resolution was that tooltips _should_ be at the top, so them showing above the panel was "working-as-intended"... even if it looks retarded.
