### ISSUE TITLE
Option to only show underline when the cursor is on that line

### ISSUE THREAD

**Issue by josh18** [steelbrain/linter#1257]
I personally find the underline a bit distracting but it is useful to pinpoint the error (and to know where to click to display the inline error bubble). As a compromise it would be nice if I could get it to only show up when my cursor is on that line.

Initially I was trying to do it via css using the `cursor-line` class but I don't believe this is possible due to the underline being inside the lines block rather than individual lines?

**Comment by steelbrain** [comment]
Hi @josh18 

I've thought about it, experimented with it and found it to be counter-productive because the only way for the user to know an error is on the line is to move their cursor over it. We try to make the errors as visible to the user as possible (eg. our new tree view feature in v2). Sadly, we cannot support what you have requested. But thanks for the request!

**Comment by josh18** [comment]
Sorry I don't quite understand, how would having an option to only underline when on that line be less visible that hiding the underlines completely?

For example I have underlines turned off because if I open a page with a lot of errors the amount of red lines is very distracting. Using the gutter I can still see which lines contain errors but at the moment it can be difficult to pinpoint which part of the line contains the error (usually I just click on different parts of the line until the popup shows).

Of course this is your package so I fully respect if you don't want to implement this feature.

**Comment by steelbrain** [comment]
I'm sorry, I'm not trying to be rude :) I think what you experienced was a temporary reaction to a file that had to be migrated from a non-linted setup to a properly linted setup. What I personally do during those transitions is disable underlines and use the bottom panel only, you could try using that and see if it works for you. Again, it's only a temporary issue when migrating files as mentioned above, once you have linting setup and properly configured, you shouldn't see files with lots of linting errors. You should only have a few linting errors at max.

**Comment by josh18** [comment]
Don't worry I didn't think you were rude at all :smile: Yeah I just really don't like the red underlines unless I am specifically looking for that error. Don't worry my "blind" click is actually pretty good now, I can usually guess where the error will be on a line.
