### ISSUE TITLE
Linter not working with c++

### ISSUE THREAD

**Issue by marc-mendoza** [steelbrain/linter#1266]
Installed linter 1.11.18 and linter-gcc 0.6.15 and all it says is "no issues" at the bottom. Atom version is 1.12.2

**Comment by steelbrain** [comment]
Hi @marc-mendoza. This package is the base package. It doesn't by default know anything specific about the file types.
You should install any of the [available linters for your filetype](http://atomlinter.github.io/) for this package to work with that file type

**Comment by marc-mendoza** [comment]
I have linter-gcc, I've tried linter-clang too but they didn't work.

**Comment by steelbrain** [comment]
Check your dev console for any errors, if you see any, try to resolve them.
But if you do not see any errors related to the linter providers you've specified, try opening this bug on those provider repos as this is just the base linter and those providers are maintained by different people :)
