### ISSUE TITLE
Gutter decorators look elongated

### ISSUE THREAD

**Issue by surdu** [steelbrain/linter#1267]
Atom: v1.13.0-beta2
linter: v1.11.19

<img width="572" alt="screen shot 2016-11-14 at 11 40 09" src="https://cloud.githubusercontent.com/assets/11520795/20259772/5c339944-aa5f-11e6-98c5-d9baee634c9a.png">

**Comment by steelbrain** [comment]
I was on the same beta when I published the update. I didn't get this.

Anyways, I'll investigate it soon and post my findings

**Comment by steelbrain** [comment]
I don't see it on the same version of both linter and Atom

<img src="https://cloud.githubusercontent.com/assets/4278113/20264859/76a9026a-aa22-11e6-9b68-347b1168f0c9.png">


Which theme are you using?

**Comment by hultberg** [comment]
I'm also observing the same issue. I thought this was related to line height settings in the editor, but the "circle" is still in an oval shape.
![screen shot 2016-11-14 at 13 58 47](https://cloud.githubusercontent.com/assets/1257913/20265795/59c1c244-aa73-11e6-8ca1-75d176ce41bc.png)

Using atom beta 1.13, One Dark ui theme, and Atom Material Dark syntax theme.

**Comment by surdu** [comment]
I use One Light theme.

**Comment by mattaschmann** [comment]
I'm also experiencing this issue.  Atom Beta 1.13.0-beta2, using One Dark for both ui and syntax.  One thing I've noticed is that if I change the element.style from 21px to 7px, it looks correct.

![developer_tools_-_file____applications_atom_20beta_app_contents_resources_app_asar_static_index_html_and_limited_rb_ ___workspace_scout_apm](https://cloud.githubusercontent.com/assets/13682706/20277377/7b619840-aa5d-11e6-860c-4f2e41bf6036.png)
![limited_rb_ ___workspace_scout_apm](https://cloud.githubusercontent.com/assets/13682706/20277431/cc5f5b4c-aa5d-11e6-9a95-c0fc389138b6.png)


I'm pretty new to Atom, but it doesn't seem like the theme itself would be setting element level styles.

**Comment by steelbrain** [comment]
@mattaschmann Thank You, that was a lot of useful information. Will fix real soon

**Comment by steelbrain** [comment]
Fixed in v1.11.20
