### ISSUE TITLE
Gutter decorators are top-aligned

### ISSUE THREAD

**Issue by mattaschmann** [steelbrain/linter#1268]
This is a followup to the fix from #1267, the decorators are 'flex-start', which puts them at the top of the row.

![image](https://cloud.githubusercontent.com/assets/13682706/20364533/bdce4b52-ac00-11e6-80bf-3f2dc60d920b.png)

Removing the 'align-self' style fixes the issue.

![image](https://cloud.githubusercontent.com/assets/13682706/20364586/eb05a25a-ac00-11e6-99dd-d3c2d1484390.png)

![image](https://cloud.githubusercontent.com/assets/13682706/20364598/f61bc9da-ac00-11e6-9a95-c499c53c9a75.png)

Using Atom Beta 1.13.0-beta3

**Comment by steelbrain** [comment]
Thank You

**Comment by steelbrain** [comment]
Fixed in v1.11.21
