### ISSUE TITLE
Idea: Add an action to fix source code.

### ISSUE THREAD

**Issue by leesdolphin** [steelbrain/linter#1271]
Many linters have an option to fix source code. It would be good if this was exposed as an option inside the linter plugin.

The [ESLint plugin](https://github.com/AtomLinter/linter-eslint/) has this functionality exposed inside Atom as a menu item.

**Comment by steelbrain** [comment]
We already have `fix` in Linter v1 and `solutions` in Linter v2. Thanks for the request though
