### ISSUE TITLE
In the status bar, color "N Issues" differently (orange) if there are just warnings and no errors

### ISSUE THREAD

**Issue by sompylasar** [steelbrain/linter#1276]
It's very confusing when the linter screams in red while there are just warnings underneath.

![screen shot 2016-12-01 at 3 19 44 pm](https://cloud.githubusercontent.com/assets/498274/20816916/a7f26aae-b7d9-11e6-8fec-c7ac9fcaf4fe.png)

**Comment by steelbrain** [comment]
We are gonna fix this in linter-ui-default when we add that bottom status bar. It'll have counts of all three severities For example

`0 Errors 5 Warnings 0 Infos`

**Comment by sompylasar** [comment]
What's "linter-ui-default"?

**Comment by steelbrain** [comment]
In the upcoming v2 of Linter, the UI has been separated into another package [`linter-ui-default`](https://github.com/steelbrain/linter-ui-default)

**Comment by sompylasar** [comment]
Oh, I see, thank you!

**Comment by akuji1993** [comment]
Another thing that's kind of an issue for me personally. I would like to only see errors in the error panel. I couldn't find a setting like "show only issues with severity this high or higher" or something. Am I just blind or is this not supported yet?

**Comment by steelbrain** [comment]
Linter v2 is finally out people. You can read more about it in the [release post](http://steelbrain.me/2017/03/13/linter-v2-released.html).
