### ISSUE TITLE
update to newer version of cpplint

### ISSUE THREAD

**Issue by didito** [steelbrain/linter#1278]
https://github.com/google/styleguide/blob/gh-pages/cpplint/cpplint.py

**Comment by didito** [comment]
i just copied the files from https://github.com/google/styleguide/blob/gh-pages/cpplint/ into ~/.atom/packages/linter-cpplint and made them executable. Works!

**Comment by steelbrain** [comment]
Thanks for the solution @didito but I am afraid this package is only the base linter, you should open this in `linter-cpp` or the linter provider you're using

**Comment by johnking** [comment]
@didito 

I tried but failed. 

1. I copied the cpplint.py from google into  ../packages/linter-cpplint/bin 
2. chmod +x cpplint.py

but did not work. 

thanks for any hints. 

-John

**Comment by didito** [comment]
@johnking did you copy all files in https://github.com/google/styleguide/tree/gh-pages/cpplint ?
