### ISSUE TITLE
I have no idea

### ISSUE THREAD

**Issue by Natipare** [steelbrain/linter#1282]
I've installed it, i even did download linter-clang for c++, restarted atom. I do not have any message, i dont have this little dot when im doing mistake, nottifications on the bottom always states that there is "no issues" even if i have wrong code. I dont know what im doing wrong.

**Comment by steelbrain** [comment]
Can you please send a screenshot of that little dot?

**Comment by Natipare** [comment]
Yes, a seccond

**Comment by Natipare** [comment]
I even did some mistakes. I have meant this little dot that you have on your gif.

![bez tytulu](https://cloud.githubusercontent.com/assets/24441552/21020172/98eb62e6-bd73-11e6-88bf-43e953cdc7f2.png)

**Comment by steelbrain** [comment]
Nope, your linter is not working. By what I see you are on windows, you might have to configure your linter provider before using it.

Closing as off-topic (this repo is just the base linter) but feel free to continue discussing :)

**Comment by Natipare** [comment]
Okay so how do i configure it ? Ive searched for it but i dont see any guide ?

**Comment by steelbrain** [comment]
There should be a README or a guide in the linter provider you use (in this case, linter-clang)

**Comment by Natipare** [comment]
Thanks!!
