### ISSUE TITLE
Gutter marks not showing up

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/linter#1284]
Follow up to conversation with @kevhill

**Comment by steelbrain** [comment]
@kevhill are you able to repro the error on any linter provider other than flake8?

**Comment by ThomasJClark** [comment]
I don't get gutter marks either.  This happens with both `linter-eslint` and `linter-clang`

This is in a fresh install of Atom 1.12.7 with no additional packages or themes besides linter/linter-eslint/linter-clang

**Comment by steelbrain** [comment]
Hi @ThomasJClark, `linter-eslint` by default doesn't show anything, you have to add a configuration etc. Just to be sure, you have an eslint configuration in you project, right?

**Comment by ThomasJClark** [comment]
Yeah I still get errors in the bottom pane, just not the red dots in the gutter

**Comment by steelbrain** [comment]
Screenshots and a file (with it's eslint config) that we can use to reproduce the error would be extremely helpful

**Comment by ThomasJClark** [comment]
![gutter](https://cloud.githubusercontent.com/assets/3964980/21442644/2f8dfd04-c86d-11e6-99c1-e7a41a08666c.png)

**Comment by steelbrain** [comment]
Hi @ThomasJClark, I am unable to repro this on Atom Beta v1.13.0-beta8 with neither Linter stable nor Linter next on Linter-ESLint v8 on macOS Sierra

<img src="https://cloud.githubusercontent.com/assets/4278113/21466071/1149ff60-c970-11e6-8209-7c4ddb441755.png">

**Comment by ThomasJClark** [comment]
Atom beta is working for me too.

Undoing [this change](https://github.com/steelbrain/linter/commit/98a63e1d280a753edbb2f4c9549eee9f686b78b6) makes it work in the current stable Atom.  Maybe the `::shadow` selectors should stick around until Atom 1.13 is out of beta?

**Comment by steelbrain** [comment]
Wait, how did you install v1.11.21 of linter? (the version that has the referenced commit) when I've clearly written it in the requirements, that [you need Atom v13 to run it](https://github.com/steelbrain/linter/blob/d4ea5b2a48c674ca7c74a9b4e0e21881258ec43c/package.json#L13)

**Comment by ThomasJClark** [comment]
I'm not sure, I didn't have atom beta installed until today.

`apm remove linter && apm install linter` got me on the right version and it seems to be working

**Comment by steelbrain** [comment]
Case closed :)
