### ISSUE TITLE
feature request: add option to leave gutter open even when there's no errors/warnings

### ISSUE THREAD

**Issue by Roger-Heathcote** [steelbrain/linter#1285]
I'm happy to dedicate a few pixels of height to the gutter permanently but what irks me daily is the gutter appearing and disappearing. It's especially annoying when working at a line toward the bottom of the screen as the gutter pops up completely obscuring the code I'm half way through writing!

Apologies if this already exists and I have missed the setting for it, or if there is a style.less snippet to do this mentioned in the docs somewhere.

**Comment by steelbrain** [comment]
Hi @Roger-Heathcote I am pretty confused about what you mean, IIRC the gutter is never hidden and stays in place to reduce the UI clutter.

Can you please post a photo explaining what you mean?

**Comment by Roger-Heathcote** [comment]
Whoops sorry, I got the terminology wrong, I meant the Error Panel at the bottom. I can make it a fixed height but I find it annoying that it autohides when empty. The code hiding problem is less of an issue if you set the Error Panel height very low but only because I'm not that often editing on the very last line of a long file. I guess this is quite literally an edge case. If you carry on typing the line leaps back into view so it's not the end of the world, just a quick space then backspace does the trick, but it would be nice to not have to do that. Thanks for awesome work by the way, having access to live linting is really helping me write better code!

**Comment by steelbrain** [comment]
Moved to https://github.com/steelbrain/linter-ui-default/issues/163
