### ISSUE TITLE
feature request: add option to make inline errors appear above the line in question.

### ISSUE THREAD

**Issue by Roger-Heathcote** [steelbrain/linter#1286]
Quite often I want to do a multi-cursor select on the line (or two) below where my cursor currently is. When there is an inline error showing I can't do this as the error popup is obscuring the line below. I do not have so much call to multi select lines above where I am so this option would be useful to me. I understand it can be mitigated to by increasing the Tooltip interval or disabling inline tool tips but I like them - they just seem to get in my way quite often!

Apologies if this is already possible and I have missed the setting for it, or if there is a style.less snippet to do this mentioned in the docs somewhere.

**Comment by steelbrain** [comment]
That's a good idea, thank you!

Moved to https://github.com/steelbrain/linter-ui-default/issues/151
