### ISSUE TITLE
Clicking Top Of Errors Panel Changes Cursor

### ISSUE THREAD

**Issue by cnyarx** [steelbrain/linter#1290]
This issue is a clone of [1102](https://github.com/steelbrain/linter/issues/1102). 
I don't know how to reopen an issue. So just create a new one.

The point down event should not modify the default cursor if user click the link text.
Is it possible to abandon the resize event while clicking the link text?
Or can you set the point curse while mouse hover/leave, instead of point down/up?

**Comment by steelbrain** [comment]
Linter v2 is finally out people. You can read more about it in the [release post](http://steelbrain.me/2017/03/13/linter-v2-released.html).
