### ISSUE TITLE
Sort issues by severity

### ISSUE THREAD

**Issue by mlitvin** [steelbrain/linter#1291]
When there are several issue it is helpful if the important issues are displayed first. That way errors are not hidden by warnings.

**Comment by steelbrain** [comment]
It is actually already done in the new linter-ui-default. You can headover to it's repository to know how to install it before it's released to general public.

**Comment by steelbrain** [comment]
See [linter-ui-default docs](https://github.com/steelbrain/linter-ui-default#installation) for installation instructions, this will be released as part of v2
