### ISSUE TITLE
Clarify in the docs that file and filePath are absolute paths

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter#1294]
It seems the documentation doesn't currently mention that the paths in messages must be absolute paths to a file, otherwise Linter is unable to properly associate them with an editor.

**Comment by steelbrain** [comment]
Fix for v1 is up in https://github.com/steelbrain/linter/pull/1303
Fix for master is up in https://github.com/steelbrain/linter/pull/1302

**Comment by Arcanemagus** [comment]
Fixed on both branches.
