### ISSUE TITLE
Use GitHub pages doc generator

### ISSUE THREAD

**Issue by fulldecent** [steelbrain/linter#1296]
GitHub pages has a new feature to publish a documentation website based on a `docs` folder in the `master` branch.

Information: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

 - [x] Enable this feature to render https://github.com/steelbrain/linter/tree/v1/docs into html
 - [ ] Create a project link (shows directly after "A Base Linter with Cow Powers"  on https://github.com/steelbrain/linter) to this new HTML documentation

**Comment by steelbrain** [comment]
Thank You. Sounds like an interesting idea

**Comment by steelbrain** [comment]
Thanks @fulldecent

Linter docs are now up on http://steelbrain.me/linter
