### ISSUE TITLE
Improve the Standard Linter v2 example

### ISSUE THREAD

**Issue by TeroFrondelius** [steelbrain/linter#1299]
Please see the discussion here: https://discuss.atom.io/t/help-on-linter-standard-linter-v2-example

I have uploaded the example package to: https://github.com/TeroFrondelius/linter-example

Any help to fix (probably a trivial mistake) is appreciated. 

I have tried to follow: https://github.com/steelbrain/linter/blob/master/docs/examples/standard-linter-v2.md but I cannot get this example to work.

**Comment by steelbrain** [comment]
Linter v2 is not yet published, you will not be able to get it to work. You can either write your package with v1, or install v2 manually, or help us with the bugs so we can release v2 sooner :)

**Comment by TeroFrondelius** [comment]
Thanks a lot. I tried to change version 1 of the example and copied it from here:
https://github.com/steelbrain/linter/blob/v1/docs/examples/standard-linter-v1.md

Here is the full package:
https://github.com/TeroFrondelius/linter-example/commit/bc984064f3b7f4a5d90998065f893a903397d2fc

I am a newbie, thus the mistake can be very trivial.

**Comment by steelbrain** [comment]
Hi @TeroFrondelius You wrote a correct API consumer this time but did another mistake, in your `package.json` you have written an invalid value for `main` field, your main file is `lib/linter-example.js` but in your manifest it's `index.js`, that should be updated. I also recommend adding `source.js.jsx` to your grammarScopes to support language-babel

**Comment by TeroFrondelius** [comment]
Thanks a lot for your help.
