### ISSUE TITLE
Allow programmatic specification of linting conditions

### ISSUE THREAD

**Issue by zepalmer** [steelbrain/linter#1307]
Presently, it seems that the `linter` package will call the standard linting functions only under two circumstances:

* When the file is saved
* When the editor buffer changes and `lintOnFly` is `true`

There are other circumstances under which a linter may want to update its message list.  For instance, I am using `ocaml-merlin` to lint `.ml` files.  Merlin, the tool that does the real work of linting, relies upon compiled files from other modules; when these files change, I want the linter to re-run.

The [Standard API](https://github.com/steelbrain/linter/blob/v1/docs/types/standard-linter-v1.md) could add to the Linter type an optional function e.g. `onNeedRelint`, the argument of which is a callback to the `linter` package that will do whatever the package currently does when the buffer is changed.  This way, linter providers can invoke that callback (either directly or by registering it elsewhere) to trigger the same per-buffer error registration that editing the buffer does.  In my case, for instance, I could modify my `ocaml-merlin` plugin to monitor file changes in my build directory and relint when those files are updated.  It looks like this proposed callback would merely need to emit a `'should-lint'` signal, but I'm not sure.

Thank you for the excellent plugin!

**Comment by steelbrain** [comment]
Hi @zepalmer

Have you explored the [Linter Indie](https://github.com/steelbrain/linter/blob/v1/docs/types/indie-linter-v1.md) API yet? You would be able to solve the issues you're experiencing using that API. Though you would have to keep a map of the messages for each file path yourself, to update each time but that has been changed in [Linter Indie v2](https://github.com/steelbrain/linter/blob/master/docs/types/indie-linter-v2.md) (unreleased at the moment).

Let me know if you have any further questions

**Comment by zepalmer** [comment]
Hello, @steelbrain!  :)  Thanks for the surprisingly fast response.  :)

I saw the Indie API but I wasn't clear on the motivation for separating the two APIs based upon messaging method.  The standard API provides rather useful features (e.g. lint on save) that consumers of the Indie API would have to replicate, right?  The `ocaml-merlin` package, for instance, already uses the Standard API, so rewriting it to use the Indie API would require a reimplementation of any update mechanism the `linter` package already has (or may have in the future).

That said, I think I may have misunderstood the scope of the Indie API when I saw it.  If you're confident of a stark distinction between the two APIs, I can investigate an `ocaml-merlin` adjustment to use the Indie API.  :)

Again, thank you much!

**Comment by steelbrain** [comment]
Hi @zepalmer, I see that you don't want to do a lot of code duplication and just want to trigger the linting, in which case, you can just focus the text editor you want to relint and trigger the `linter:lint` atom command programatically, linter will do the rest

**Comment by zepalmer** [comment]
That sounds quite nice; thank you!  I'm teaching a course on compilers using OCaml and it may even be sufficient to set up a keystroke for my students so they can invoke the `linter:lint` action themselves.  (I didn't realize it existed.)

It doesn't appear that there's a nice way to do this for an editor which is not in focus.  For that, I suppose we'd need the Indie API.

Thanks again!
