### ISSUE TITLE
Linter writing deprecated highlight classes

### ISSUE THREAD

**Issue by tjkohli** [steelbrain/linter#1308]
Linter is writing deprecated classes to highlight code, such as the `error` in:
```html
<div class="highlights">
  <div class="highlight linter-highlight error">
    <div class="region" style="..."></div>
  </div>
</div>
```

Other classes include `warning`, `trace`, and `info`.

These all need to be prefixed with `syntax--`.

---

This will resolve a [much-discussed issue in this theme](https://github.com/tjkohli/nebula-syntax/issues/3).

**Comment by steelbrain** [comment]
This has been fixed in the unreleased v2

**Comment by tjkohli** [comment]
When will that be released? If we don't want to rush it, is there a compelling reason we can't get just these updates out there?

**Comment by steelbrain** [comment]
It's stuck on some css fixes, if you could lend a hand we could release it more quickly

**Comment by tjkohli** [comment]
Help me get up to speed on what needs to happen, and I'll gladly help out.

**Comment by steelbrain** [comment]
@tjkohli The important things are mentioned in the [issue tracker](https://github.com/steelbrain/linter-ui-default/issues) of [linter-ui-default](https://github.com/steelbrain/linter-ui-default). It's README has instructions on how to install v2 of both linter and the ui provider. I'm available on slack all day under the same username to provide more specifics

**Comment by steelbrain** [comment]
Linter v2 is finally out people. You can read more about it in the [release post](http://steelbrain.me/2017/03/13/linter-v2-released.html).
