### ISSUE TITLE
Line number greater than maximum line with Trace type

### ISSUE THREAD

**Issue by mschuchard** [steelbrain/linter#1309]
I am using the `trace` type and am returning a range on line 9 in another file. My current file has 6 lines in it. The error being returned is:

>Line number (9) greater than maximum line (6)

So `trace` seems to be attempting to return a line in the current file instead of the other file, unless I am mistaken on the API.

**Comment by steelbrain** [comment]
Hi @mschuchard, if you are using trace to point to another line then make sure that you are providing path of the other file in `trace.filePath`

**Comment by mschuchard** [comment]
I am linting from this file: https://github.com/mschuchard/linter-ansible-linting/blob/master/spec/fixtures/include_has_issues.yml
and tracing to this file: https://github.com/mschuchard/linter-ansible-linting/blob/master/spec/fixtures/include_with_issues.yml
with this code:

```javascript
{
  type: 'Trace',
  severity: 'warning',
  // range is resolving to integer 9
  range: helpers.rangeFromLineNumber(activeEditor, Number.parseInt(lint_matches[1] - 1)),
  text: lint_matches[2],
  filePath: '/home/matt/git_repos/linter-ansible-linting/spec/fixtures/include_with_issues.yml',
}
```
`filePath` is being hardcoded for now since I am iteratively coding this new `trace` functionality.

Let me know any other helpful info I can provide.

**Comment by Arcanemagus** [comment]
`rangeFromLineNumber` uses the `TextEditor` provided to it to validate the given values, you would need to either use an editor that already has that file open, open a new editor on that file (spendy), or just create a single character range at the start of the line.

**Comment by mschuchard** [comment]
Ok so sounds like I need to look in to another API doc.

For now I changed to this:

```javascript
{
  type: 'Trace',
  severity: 'warning',
  range: Number.parseInt(lint_matches[1]),
  text: lint_matches[2],
  filePath: '/home/matt/git_repos/linter-ansible-linting/spec/fixtures/include_with_issues.yml',
}
```

and it redirects to the other file correclty, except with line 1 col 1. So I think I got past this and just need to keep working on it.

Thanks @steelbrain and @Arcanemagus for the help!
