### ISSUE TITLE
Consider integrating busy-signal

### ISSUE THREAD

**Issue by Gozala** [steelbrain/linter#1315]
I know it's planned for v2 but that it has being a long time coming and isn't really clear when it's actually gonna arrive. In the meantime I would really like to have flowtype plugin with would be able to signal if it's still type-checking or if it has type checked code successfully.

Existing plugins do not want to add dependency on busy-signal as they expect this to be done by linter instead, so I'm stuck  running a forked flowplugin for quite some time now.

Thanks for considering.

**Comment by steelbrain** [comment]
It's not just planned it's implemented in v2 and working perfectly

I'm sorry you're stuck on a forked flowplugin, the work for the linter isn't much. It's just that I have so many public and private projects, it's been getting hard for me to spare time for linter. But linter is still, by far, my favorite project. I'll keep this open so it's up for grab if someone from the community wants to work on it but linter v2 isn't that far away, linter itself is done completely, only things left are in the ui consumer

**Comment by steelbrain** [comment]
[Sneak Peek of the Linter v2](https://www.youtube.com/watch?v=Ek7p49sf8Eo)

All main issues resolved, pending on docs and specs

**Comment by steelbrain** [comment]
Linter v2 is finally out people. You can read more about it in the [release post](http://steelbrain.me/2017/03/13/linter-v2-released.html).
