### ISSUE TITLE
Possible Coloring Issue?

### ISSUE THREAD

**Issue by pingshunhuangalex** [steelbrain/linter#1317]
Hi @steelbrain 
I just noticed the text in warning tooltips in linter-flake8 ([Issue](https://github.com/AtomLinter/linter-flake8/issues/347#issuecomment-279191496)) is really hard to see when using `material-ui` theme.
Just wonder if there is a reason why you forced the text to be white in [here](https://github.com/steelbrain/linter/blob/v1.11.21/styles/linter-plus.less#L165)?

![image](https://cloud.githubusercontent.com/assets/17170199/22859187/8e8fa496-f127-11e6-8a16-f336f3083422.png)

**Comment by steelbrain** [comment]
Hi @pingshunhuangalex, The linter package reuses color variables from your themes. Can you change your theme and see if this error is resolved?

**Comment by pingshunhuangalex** [comment]
Thanks for the reply @steelbrain 
Other default themes do look fine as they all use dark yellow/brown for the warning rectangle. I've already reported the same issue to the theme provider. Thanks.

**Comment by steelbrain** [comment]
Great, thanks @pingshunhuangalex. Also tell your theme provider that the variable in question is `background-color-warning`. Best of luck 👍

**Comment by Arcanemagus** [comment]
Btw, the v1 Linter actually [forces](https://github.com/steelbrain/linter/blob/v1.11.21/styles/linter-plus.less#L165) the text color to `white` instead of using a theme variable.

**Comment by steelbrain** [comment]
Thanks @Arcanemagus I didn't notice the text color, thought the background color was uncomfortable (which indeed comes from the theme), will re-use the theme color var for text as well

**Comment by steelbrain** [comment]
A fix has been released in v1.11.22
