### ISSUE TITLE
Can't find linter in install package search

### ISSUE THREAD

**Issue by danielpetrica** [steelbrain/linter#1322]
Hi today I tried to install linter from the _install package_ pane inside atom. 
I tried to search linter but atom displayed only the language packages like linter-php and not the base package. 
I finally found it using **`"linter"`**, so i'm suggesting you to an explanation in the installing section which tell the user to search for **`"linter"`** (with the **""**) so they can find the package.

**Comment by steelbrain** [comment]
@danielpetrica please have a look at https://github.com/steelbrain/linter/pull/1323 and tell me if that fixes your issue

**Comment by danielpetrica** [comment]
@steelbrain Yep! With Base Linter the first results it's the right one.
