### ISSUE TITLE
Any way to make the linter display the errors first?

### ISSUE THREAD

**Issue by c10b10** [steelbrain/linter#1327]
Is there a way to configure it in order to get the erros first in the bottom panel, and then the warnings? (Currently they seem to show up in the order they are detected).

**Comment by steelbrain** [comment]
Hi @c10b10 

This has been implemented in v2, and was demoed in [Atom Linter v2 Sneak Peak](https://www.youtube.com/watch?v=Ek7p49sf8Eo).
To install it early see [`linter-ui-default` README](https://github.com/steelbrain/linter-ui-default#installation)

**Comment by c10b10** [comment]
That's awesome. When will the final new version be out?

**Comment by steelbrain** [comment]
I can't give you an exact date but I'm really personally hoping for within 30 days

**Comment by c10b10** [comment]
![](http://hoarding.s3-eu-west-1.amazonaws.com/Screen-Shot-2017-02-24-13-52-34)

Any clues anywhere on what the four Flow Coverage percentages refer to? Is that still work in progress?

**Comment by steelbrain** [comment]
@c10b10 That flow coverage actually refers to the output of `flow coverage $fileName` from CLI

**Comment by steelbrain** [comment]
Linter v2 is finally out people. You can read more about it in the [release post](http://steelbrain.me/2017/03/13/linter-v2-released.html).
