### ISSUE TITLE
Error on running Linter

### ISSUE THREAD

**Issue by xukai92** [steelbrain/linter#1328]
```
Error: connect ENOENT /tmp/lintserver152921VYBsTiNMTVusock
Error: connect ENOENT /tmp/lintserver152921VYBsTiNMTVusock
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

I got this error on running Linter. What's the cause?

**Comment by steelbrain** [comment]
Hi @xukai92

Could you give us the list of installed linter packages you have?

**Comment by xukai92** [comment]
@steelbrain Sure.

I have linter, linter-julia and linter-write-good installed.

**Comment by xukai92** [comment]
I realised that this error was caused by the fact that I didn't install a separate package for Julia which is used by linter-julia.

**Comment by steelbrain** [comment]
Props on figuring out the error 🎉
