### ISSUE TITLE
Possible to have linter output underneath the affected line?

### ISSUE THREAD

**Issue by i-am-the-slime** [steelbrain/linter#1333]
Is it possible to show the problem in a block underneath the affected line instead of just a tooltip? It would be cool to not have to move my eyes back and forth.

**Comment by Arcanemagus** [comment]
Have you tried setting the tooltips to follow the keyboard?

**Comment by i-am-the-slime** [comment]
Woah, what a response time. I have not. I am new to Atom (30 minutes). I will try now.

**Comment by Arcanemagus** [comment]
Sorry, looks like that's actually only available in the v2 version that isn't quite ready for release yet!

Unfortunately I think in v1 tooltips only follow the mouse cursor.

**Comment by i-am-the-slime** [comment]
I'm using vim mode and the error shows up when I am exactly at the right line and column with the keyboard cursor. Is there any way to expand this to the entire line?

**Comment by steelbrain** [comment]
@i-am-the-slime You could try enabling the linter panel and telling it to only show the errors on the selected line. As a side note, we already underline the affected range in red so you know where to click

**Comment by steelbrain** [comment]
Linter v2 is out, it should be fixed for you now
