### ISSUE TITLE
Lint Preview Tabs stops all linting

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter#1334]
It seems that the "Lint Preview Tabs" setting is broken, if it is disabled then _all_ linting is stopped, not just on preview tabs.

**Comment by steelbrain** [comment]
Investigating

**Comment by steelbrain** [comment]
Thanks for the report @Arcanemagus but it seems to be an Atom bug, in the latest releases, it doesn't seem to setting `hasTerminatedPendingState` to `true` anymore

<img src="https://cloud.githubusercontent.com/assets/4278113/23532770/19f221fc-ffcf-11e6-9906-4e5a55444802.png">

**Comment by steelbrain** [comment]
After some private discussion with @Arcanemagus, we discovered that Atom has actually changed it's pending state API so going to upgrade linter to use that

**Comment by Arcanemagus** [comment]
Changed their undocumented, non-public pending state API to be fair 😛.
