### ISSUE TITLE
Add linter:debug command

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/linter#1337]
This command should output debug information like the scopes of the active text editor, the loaded linter providers and the scope they work for and if they support lint on fly or not

**Comment by Arcanemagus** [comment]
As an example, here is the generic information in the `linter-eslint` debug command:
```raw
Atom version: 1.15.0-beta4
linter-eslint version: 8.1.2
Hours since last Atom restart: 0
Platform: win32
Current file's scopes: [
  "source.js",
  "string.quoted.template.js",
  "source.js.embedded.source",
  "meta.method-call.js",
  "meta.arguments.js",
  "variable.other.property.js"
]
```
