### ISSUE TITLE
contributing ...

### ISSUE THREAD

**Issue by msbajammal** [steelbrain/linter#1338]
Hi,

Great project 👍! I've been using it for sometime and would like to contribute. I'm trying to experiment with implementing varying levels of underlining to overlay more information on the hints.

Which part of the code instructs atom to underline specific ranges in the text editor's buffer range? I was checking the Atom API under the mark range and decoration, but you don't seem to be using it in this project, no?

Thanks. Awesome project 😄 👍

**Comment by steelbrain** [comment]
Hi @msbajammal 

Thank you so much for your offer to contribute, we need all the people we can get! The linter project has split it's UI into a separate package, which is where all the changes are happening and will be published soon. Please have a look at http://github.com/steelbrain/linter-ui-default

It's the new repository of the UI, it should have installation instructions in the README. If you are looking for issues to contribute to in that repository, I would greatly appreciate some steelbrain/linter-ui-default#139 and steelbrain/linter-ui-default#151

Thanks again!

**Comment by msbajammal** [comment]
Sure, would love to 👍 
So is linter-ui-default *already* being used with the latest release of linter?

**Comment by steelbrain** [comment]
It's not being used with the latest release, but will be with the upcoming release, if you install the master branch of linter as docs of the ui package suggest, you'll see what I mean :)

**Comment by Arcanemagus** [comment]
It's being used with the `master` branch here, but not the `v1` branch that releases on APM use.

**Comment by steelbrain** [comment]
Linter v2 is finally out people. You can read more about it in the [release post](http://steelbrain.me/2017/03/13/linter-v2-released.html).

Closing as this is more of a meta issue, but feel free to continue discussing :)!
