### ISSUE TITLE
install linter-ui-detault 0.0.3  encounter issues

### ISSUE THREAD

**Issue by ZSI2017** [steelbrain/linter#1342]
after install linter `1.99.0  and linter-ui-default 0.0.3 :

show warnning :
    These issuses were encountered while registering the UI named 'Linter'
--  UI.render must be a function 

OS: win10

**Comment by steelbrain** [comment]
I've just published v0.0.4 of linter-ui-default on APM.

Please keep in mind that before v1.0 of linter ui, I will not push regular updates to APM. You will, instead, have to git clone the repository. You can find more about the installation in linter-ui-default's README
