### ISSUE TITLE
Non-existent files kept in memory by linter after file rename

### ISSUE THREAD

**Issue by skylize** [steelbrain/linter#1343]
Simple case below using linter and linter-eslint, when open files get renamed, linter keeps reference to a copy of the file that no longer exists and continues reporting errors if any existed before changing the file name.

* Open new file
* Type `{}`
* Save as `test.js`
* _Linter reports error because of empty block statement_
&nbsp;
* Open tree view and rename `test.js` to `test.json`
* Close either `test.js` or `test.json—`, whichever appears, leaving open `test.json`
* _Linter continues to show error even though this is a json doc_
&nbsp;
* Type anything into the document
* _Error indicator disappears from the document but remains in the statusbar_
&nbsp;
* Click the error indicator on the statusbar
* _An empty document opens with document error indicators and tab named `test.js`_
&nbsp;
* Hit `Ctrl-S` to save
* _We now even have an actual empty file named `test.js`, but linter is still reporting empty block from the old file in memory and showing error indicators on the open document tab._
&nbsp;
* Close `test.json`
* _Error finally disappears_

**Comment by steelbrain** [comment]
Hi @skylize!

The concern you have is very valid but has already been taken care of by v2 (that we're aiming to release before next week!!)

**Comment by skylize** [comment]
Exellent. Thanks.
