### ISSUE TITLE
Saving the file causes gutter errors to disappear

### ISSUE THREAD

**Issue by ryancole** [steelbrain/linter#1345]
I'm using latest versions of `linter` and `linter-eslint` for Atom v 1.14.4 x86, on Windows 10. There seems to be many situations in which I do not see eslint errors appear in the line number gutter, or inline in the code itself. I do always see eslint errors at the bottom of the document, though, in the error pane.

One scenario in which I've noticed is when I save a document. As I'm typing, I can see eslint errors appear in the gutter, and at the bottom in the error pane. Once I save (CTRL+S), the gutter icons disappear. If I continue typing again they'll reappear, but once I save they go away again.

I hardly ever see the gutter errors, or inline errors.

**Comment by steelbrain** [comment]
I'm a confused, @Arcanemagus thoughts?

**Comment by Arcanemagus** [comment]
My only guess is that you have enabled fix-on-save in `linter-eslint`, and when you save it is fixing the issues, then when you continue typing you introduce more errors? Without a screencast or files to reproduce each step I'm not entirely sure what you are saying here.

**Comment by ryancole** [comment]
Ah, actually now that you bring that up I did pinpoint the cause. I do not use fix-on-save via eslint, but I do use fix-on-save via prettier-atom. Saving, with prettier-atom, does indeed cause the gutter errors to disappear. Disabling prettier-atom does seem to fix the issue.

Is there something that prettier-atom could do that would help the linter plugins properly resume displaying these gutter errors, etc?

I'm not knowledgeable about how atom works, etc, but perhaps I could help relay some information about this issue over to the prettier-atom repo.

**Comment by steelbrain** [comment]
Yeah, `prettier-atom` could make sure to trigger `linter:lint` command on the text editors it executes **after** it's done with them

**Comment by steelbrain** [comment]
Closing as external based on above discussion, feel free to continue discussing
