### ISSUE TITLE
Linter >= 2.0 throwing misleading warning

### ISSUE THREAD

**Issue by mschuchard** [steelbrain/linter#1359]
See info here: mschuchard/linter-ansible-syntax#2.
Linter consumer is returning an array, so warning is triggering on something else.
Linter consumer is using Standard Linter v1 API.
Please let me know what really is triggering the warning so I can make changes on my end and update the warning message/logic in Linter accordingly.

**Comment by Arcanemagus** [comment]
Looking into this.

**Comment by Arcanemagus** [comment]
Commented on the linked issue, in short it's possible for this plugin to return `undefined` currently.
