### ISSUE TITLE
Decorations don't indicate current line

### ISSUE THREAD

**Issue by lordjavac** [steelbrain/linter#1360]
The gutter decorations do not blend with current-line highlighting creating a visual gap. You can see what I mean in the image below on line 4. I've tried changing the syntax and UI themes. The inspector shows that there is not special classes on the current (or selected) lines. It would be nice to use @syntax-theme-gutter-background-selected for the background color to match the line numbers in the gutter.

The built-in module git-diff adds its mark to the existing line-number gutter. I'm not sure if they're cheating by being built-in, but could we add the linter decoration to the end of the existing line number gutter?

![screen shot 2017-03-14 at 10 26 12 am](https://cloud.githubusercontent.com/assets/58458/23913586/b33f5972-08a0-11e7-9c42-be4631d3dbc6.png)

**Comment by steelbrain** [comment]
Hi @lordjavac

The git diff doesn't add it's marks to the existing line number gutter, it has a very thin but a gutter of it's own. We previously used to paint the same gutter but then it started conflicting with other packages because they too want to pain the same gutter. I think the problem here is that UI seems a little off, for which you could contact your theme author to make it more comfortable.

Thanks again for taking the time to report this!

**Comment by lordjavac** [comment]
The issue shows up with several syntax themes including the built-in Atom Light. Several other syntax themes show that linter's decorations are not pulling the same background color as the line numbers. Further exacerbated by not tagging the current line to color accordingly based on the syntax styling. I see this as not fulling implementing the syntax theme's color scheme. Here's a picture of Atom Light showing the broken current line highlight. Several syntax themes work differently as they don't try to create a single highlight including the line numbers. This is obviously a style choice, but it would be nice for linter to respect that choice with its gutter.

![screen shot 2017-03-14 at 2 08 58 pm](https://cloud.githubusercontent.com/assets/58458/23922753/cffc71f6-08c0-11e7-9a10-f38d50d8a93f.png)

Also, git-diff does add the marker to the line-numbers. It's adding the class git-line-modified to modified lines which sets the left border and reduces the padding to compensate:

```css
border-left: 2px solid #e2b93d;
padding-left: calc(0.5em - 2px);
```

**Comment by lordjavac** [comment]
I guess this actually belongs in linter-ui-default as that's what's drawing the gutter UI. Should we move the issue there?

**Comment by steelbrain** [comment]
Moved to https://github.com/steelbrain/linter-ui-default/issues/186
