### ISSUE TITLE
Text on buttons is hard to read with a non-default atom theme

### ISSUE THREAD

**Issue by johnhaley81** [steelbrain/linter#1361]
Thanks for all of your hard work on this plugin!

I have https://atom.io/packages/seti-ui as my theme for atom and after updating to the latest linter@2.0.0.

![image](https://cloud.githubusercontent.com/assets/867780/23917591/2325990c-08ad-11e7-843e-a3a1d9761671.png)

Note that the buttons on the bottom notification are hard to read.

**Comment by steelbrain** [comment]
That's correct @johnhaley81 

But we're using the default API for constructing buttons, the bug is in your theme not providing correct colors for them. Please reopen this bug in the theme :)

Thanks!

**Comment by johnhaley81** [comment]
Thanks so much for the quick response! I'll go repost this over in `seti-ui`.

**Comment by Arcanemagus** [comment]
I've had to give up on seti-ui due to this exact issue... buttons were just plain unreadable all over the place.
