### ISSUE TITLE
Hide link icon in Linter Provider v1

### ISSUE THREAD

**Issue by halohalospecial** [steelbrain/linter#1364]
Hi!  Is there a way to hide the [link icon](https://octicons.github.com/icon/link) when using Linter Provider v1?

**Comment by steelbrain** [comment]
Any particular reason you want to hide that icon?

**Comment by halohalospecial** [comment]
Just to save space basically :-)  Also, correct me if I'm wrong, there's no way right now to set the "url" in Linter Provider v1?

**Comment by steelbrain** [comment]
Not in v2, it's been added in v2

**Comment by halohalospecial** [comment]
I'm using the "html" property available in v1, so I cannot migrate to v2 yet.  Will setting "url" to `null` in v2 hide the link icon?

**Comment by steelbrain** [comment]
Dude, it takes like 5px or something, why do you dislike it so much? Plus it's really useful when searching for an error online 😄

**Comment by steelbrain** [comment]
Fixed as of https://github.com/steelbrain/linter-ui-default/pull/249
