### ISSUE TITLE
Show/Hide tooltip with keybinding

### ISSUE THREAD

**Issue by mattaschmann** [steelbrain/linter#1366]
First of all, great work on v2 @steelbrain.  I'm a vim-style user, and dislike using my mouse if possible.  I love the ability to have the tooltips off by default, but find it unwieldy to switch to the mouse to view the tooltips.  Any chance we could get a keybinding to show/hide the tooltips?

**Comment by Arcanemagus** [comment]
With v2 `linter` has been trimmed down to _just_ the logic of managing providers, all UI is handled as a service now, with the default UI implemented in [linter-ui-default](https://github.com/steelbrain/linter-ui-default).

If you check the settings for that package one of them is the new ability for the tooltips to follow the cursor. This isn't _exactly_ what you are asking for here, but it certainly removes the need to use the mouse. Also note that there is [a command](https://github.com/steelbrain/linter-ui-default/pull/169) to expand/contract tooltips that have additional content, which you can bind to a key of your choosing if you desire.

If those options aren't sufficient feel free to file an issue over there describing what you want accomplished 😉.

**Comment by steelbrain** [comment]
In case you meant that you want to get rid of the tooltips following the mouse entirely, you can change your linter-ui-default's `Tooltip Follows` from `Mouse` to `Keyboard`

**Comment by mattaschmann** [comment]
@steelbrain No I'm aware of the setting, and love it by the way.  Was just looking for a quick way to toggle it.  I'll put it over in the ui project.
