### ISSUE TITLE
Where did the project level linting panel go?

### ISSUE THREAD

**Issue by Cosmo439** [steelbrain/linter#1367]
I really enjoy this package, but I miss the project level linting panel that was in the previous version.  Is there a way to enable that in v2?

**Comment by steelbrain** [comment]
@Cosmo439 The Panel still supports project level linting, but it was confusing for some users so we've moved it to a config. You can change `Panel Represents` and `Statusbar Represents` in `linter-ui-default` config to `Project`

**Comment by Cosmo439** [comment]
I changed my config to

```
"linter-ui-default":
  "Panel Represents": "Project"
  "Statusbar Represents": "Project"
  showPanel: true
```

but still not seeing this work correctly.  I'm assuming I have the keys wrong.

**Comment by steelbrain** [comment]
Please use the settings view, what I said was the titles not the keys :)

**Comment by Cosmo439** [comment]
Ah, thanks, was looking at the wrong package.

**Comment by marnen** [comment]
Fair enough, but I still miss the feature in the previous version: having _both_ project-level and file-level counts on the statusbar. Can we bring that back somehow?

**Comment by Arcanemagus** [comment]
@marnen Can you file that as a new feature request for discussion?

**Comment by marnen** [comment]
@Arcanemagus Sure, although it feels a bit odd to file a "feature request" for a feature that used to exist.

**Comment by marnen** [comment]
Put request in #1406.
