### ISSUE TITLE
linter:next-error is no longer available when updated to linter v2

### ISSUE THREAD

**Issue by hpfdf** [steelbrain/linter#1368]
I used to have a key bind to "linter:next-error" so I can quickly explore through all errors. After I updated the linter today, this no longer works.

I did a search in linter project source dir and found nothing about next-error commands. I assume the command is removed, since the linter has changed substantially. But if someone add this back it would be great.

**Comment by Arcanemagus** [comment]
The UI has been split off into a separate project, you'll need to update that to `linter-ui-default:next-error`.
