### ISSUE TITLE
Linter issue opening Atom

### ISSUE THREAD

**Issue by CMTietgen** [steelbrain/linter#1369]
I started up Atom tonight (v1.15.0) and keep getting the following message. It goes away when I disable Linter 2.1.0.

![atom-linter-error](https://cloud.githubusercontent.com/assets/13341574/23977924/7c87e408-09c7-11e7-8d50-5f6181642f63.png)

Any thoughts on why and can it be fixed?

**Comment by steelbrain** [comment]
Hi @CMTietgen 

Can you please provide us the list of community packages you have installed? One of them is faulty :)

**Comment by CMTietgen** [comment]
I disabled all packaged and re-enabled a few at a time until I got the error again.

Turns out the issue with with json-schema by OmniSharp. Should I open a bug with them?

**Comment by steelbrain** [comment]
Yes please

**Comment by jsayres** [comment]
FYI for anyone else having this issue, in my case the culprit was ionide-fsharp. There's already a pull request at their repo to fix.

**Comment by steelbrain** [comment]
This is going to be fixed in the upcoming release of linter, I've made linter 2.x compatible with linter v1.x in terms of API validation

**Comment by Arcanemagus** [comment]
This has been fixed in v2.1.1.
