### ISSUE TITLE
[Linter] Error running JSHint See console for more info

### ISSUE THREAD

**Issue by gopakumar001** [steelbrain/linter#1370]
Hi,

Getting multiple atom notification the following error is showing up in developer console.

version details are given below 
atom : 1.15.0 X 64
linter: 2.10
linter-jshint : 3.0.3

Console error is given below
linter-registry.js:144 [Linter] Error running JSHint Error: Process execution timed out(…)(anonymous function) @ linter-registry.js:144

**Comment by steelbrain** [comment]
The error is quite clear, execution times out. Please reopen this in linter-jshint repo
