### ISSUE TITLE
High CPU usage by tclsh8.5

### ISSUE THREAD

**Issue by albireox** [steelbrain/linter#1378]
Since v2 I'm seeing multiple tclsh8.5 processes spawned that consume 100% of the CPU. The only solution is to close Atom and manually kill the processes. I'm using linter, linter-ui-default, and linter-flake8

**Comment by Arcanemagus** [comment]
Sounds like you have an issue with your shell init script that is causing it to launch that in non-interactive shells and it is crashing.

**Comment by albireox** [comment]
I'm using fish shell but I'm not aware of any change in my init script in the last few days. This was not happening with v1. Any clue of what may be the problem and how to fix it?

**Comment by steelbrain** [comment]
@Arcanemagus This is fixed by the `uniqueKey` right?

**Comment by Arcanemagus** [comment]
No, `linter-flake8` has nothing to do with `tclsh8.5`. I'm assuming this is from `consistent-env` attempting to determine the fixed environment myself.

**Comment by albireox** [comment]
This ended up being a problem with GNU modules and some code I used to make it work with fish shell. Since then I have moved to use the TCL version of modules, which seems to play better with fish, and the problem has disappeared. I never completely understood the reason why. Note also that this problem was not happening before v2, even if I was using the same code and modules version.

**Comment by steelbrain** [comment]
Closing based on above discussion. Tho I still have no idea why a linter upgrade would crash a shell (and only with GNU modules and not with tcl modules)
