### ISSUE TITLE
Can't copy linter output

### ISSUE THREAD

**Issue by clozach** [steelbrain/linter#1382]
Whether it's for doing a targeted google search or to ask for help in a forum, I frequently want to copy linter's output.

Confusingly, I can _select_ text in linter's output, but there doesn't seem to be any way to act on the selection. As a result, I seem to forget at least twice a week that the output isn't copyable until pasting fails. Enabling `copy` would be a huge time saver for me and, I suspect, almost everyone who uses linter.

Fwiw, I'm currently using linter with [Elm](https://github.com/mybuddymichael/linter-elm-make).

**Comment by steelbrain** [comment]
You won't be able to right click on it because of the way Electron works (until Atom adds support for it). But ctrl-c and cmd-c shortcuts should work fine.

Can you please confirm that they are working for you?

**Comment by clozach** [comment]
Doh! I just updated `linter-elm-make`, which in turn updated `linter` to v2, which in turn seems to support ⌘C. Thanks for this awesome tool, folks!

**Comment by wesinator** [comment]
cmd-c from the linter warnings pane works, but text in the previews cannot be selected or copied , even though there is a hover cursor 

![image](https://user-images.githubusercontent.com/5124946/64981544-4d91d480-d88a-11e9-899c-25ef22c6d840.png)
