### ISSUE TITLE
Hide tooltip when focus leaves window

### ISSUE THREAD

**Issue by bronson** [steelbrain/linter#1384]
It's easy to get confusing overlapping tooltips when navigating buffers.  It seems like only one tooltip should be visible at a time?

![bug3](https://cloud.githubusercontent.com/assets/1776/24146921/2bd3bb4a-0df5-11e7-87a8-383454e923e0.gif)

**Comment by steelbrain** [comment]
Moved to https://github.com/steelbrain/linter-ui-default/issues/225
