### ISSUE TITLE
sb-config-file missing from v2.1.1

### ISSUE THREAD

**Issue by brad-jones** [steelbrain/linter#1392]
Just updated to v2.1.1 and it would appear so though the package "sb-config-file" is not installed.

Manually running `npm install sb-config-file` inside `~/.atom/packages/linter` fixed the issue.

**Comment by Arcanemagus** [comment]
Looks like it got removed in https://github.com/steelbrain/linter/pull/1391, apparently @steelbrain forgot he was using it elsewhere in this package? 😛

**Comment by steelbrain** [comment]
Totally my fault people, I'm sorry

Fixed in v2.1.2
