### ISSUE TITLE
Error running Python Linter TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [steelbrain/linter#1394]
Hi, 

I am getting following error "**[Linter] Error running Python Linter TypeError: Cannot read property 'getPath' of undefined(…)(anonymous function) @ /Users/<username>/.atom/packages/linter/lib/linter-registry.js:177**" in the Console.

Atom 1.15.0 x64
Version: linter 2.1.1

Installed Packages:
atom-beautify
atom-clock
atom-runner
autocomplete-python
busy-signal
file-icons
git-plus
git-time-machine
intentions
linter
linter-eslint
linter-jscs
linter-jshint
linter-jsonlint
linter-python
linter-python-pep8
linter-shellcheck
linter-ui-default
minimap
minimap-split-diff
platformio-ide-terminal
python-autopep8
script
split-diff

Thanks

**Comment by steelbrain** [comment]
This issue belongs in the python linter repo, please reopen this issue there! Thank You!
