### ISSUE TITLE
turn on/off linter indicator

### ISSUE THREAD

**Issue by dagolinuxoid** [steelbrain/linter#1397]
Linter 2 has an ability to enable/disable itself by typing linter disable/enable in command palette. Isn't would be nice also to have a visual cue either linter at enable/disable state. Changing color of a mini-circle which placed at status bar panel  from red/orange to green/blue for example respectively and adding an indicate message to history pop up ( when mouse cursor on this circle ) eslint - enabled / eslint - disabled for instance. Do you guys will consider implementing such a feature or you think it is redundant and will be focused on more crucial things? Cheers :)

**Comment by Arcanemagus** [comment]
Please re-file this on the [ui project](https://github.com/steelbrain/linter-ui-default), this project is now solely an intermediary between the linter providers and any UI's you have installed.

Thanks!
