### ISSUE TITLE
No Linting at all on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by chriskerley78910** [steelbrain/linter#1400]
No Linting occurs upon install,  tried manually setting the lint directory in config.cson, with no success.

**Comment by steelbrain** [comment]
Hi @chriskerley78910 

This package is just the base package, you have to install the language specific linting providers afterwards. You can find a reference to a list to them in this package's README or you can just go directly to [`atomlinter.github.io`](http://atomlinter.github.io/)

Closing as answered but feel free to continue discussing

**Comment by chriskerley78910** [comment]
Okay thank you, I mixed up.  I was was under the impression that Javascript was supported out of the box.
