### ISSUE TITLE
linter needs to install dependencies

### ISSUE THREAD

**Issue by Edge00** [steelbrain/linter#1401]
![qq 20170326110534](https://cloud.githubusercontent.com/assets/23715779/24328138/42252f32-1214-11e7-928a-bc2f7897a020.jpg)
Last time when i installed linter and linter-eslint, my atom editor works fine
But when i updated these two, linter didn't work and remind me to install dependencies

**Comment by steelbrain** [comment]
I am not sure what the issue is in this report

**Comment by Edge00** [comment]
linter doesn't work ...

**Comment by Edge00** [comment]
When i install linter-ui-default, it responends with 404

**Comment by steelbrain** [comment]
Oh that 404 error would be because your Atom is too old, please upgrade your Atom Editor! :)

**Comment by Edge00** [comment]
Okay, I am dowloading now. Thank you!
