### ISSUE TITLE
atom linter is not working

### ISSUE THREAD

**Issue by Princeraul** [steelbrain/linter#1405]
![image](https://cloud.githubusercontent.com/assets/5966186/24393703/a83bf464-13cb-11e7-91fa-4c0ece6b3a72.png)

package：
![image](https://cloud.githubusercontent.com/assets/5966186/24393769/ee284d4c-13cb-11e7-91d7-c7be0e7a6570.png)
please help me

**Comment by steelbrain** [comment]
Please reopen this in linter-eslint repo, bonus tip: check your dev tools
