### ISSUE TITLE
Display both project- and file-level warning counts in status bar

### ISSUE THREAD

**Issue by marnen** [steelbrain/linter#1406]
In older versions of this package, I could see both project-level and file-level counts on the statusbar simultaneously. Can we bring that back somehow? The current version only lets me see one or the other, and doesn't provide any visual clue as to which one it's displaying.

(See https://github.com/steelbrain/linter/issues/1367#issuecomment-289603006 for more.)

**Comment by steelbrain** [comment]
Moved to https://github.com/steelbrain/linter-ui-default/issues/234
