### ISSUE TITLE
Ignore a specific File

### ISSUE THREAD

**Issue by Bersacker** [steelbrain/linter#1409]
Hey I got an Problem with the ignoring a specific File.
I found this Issue #519 But I'm not really satisfied.
I tryed this: 
![2017-03-30_12-27-30](https://cloud.githubusercontent.com/assets/16068109/24500239/df61ba6c-1544-11e7-9f9a-0f7310d191a6.png)
And with a differente Version 
![2017-03-30_12-30-43](https://cloud.githubusercontent.com/assets/16068109/24500258/f05231da-1544-11e7-9f32-871bee83e972.png)
But no Result
![2017-03-30_12-26-03](https://cloud.githubusercontent.com/assets/16068109/24500265/f59605f4-1544-11e7-8a58-ee09ee2734a9.png)

In Issue #519 the Last Comment is that the Providers should handle that not the Base. 
But i want to Turn off the Base (With all Providers) in some specific Files. 
Is this not supported or am I doing it wrong?

**Comment by steelbrain** [comment]
To ignore a specific file, you can do the `linter:toggle-active-editor` command. Have fun 👍
