### ISSUE TITLE
Linter not working

### ISSUE THREAD

**Issue by horcrux2301** [steelbrain/linter#1411]
I am trying to make a cpp file and even when I type gibberish the linter shows me no errors.

I have linter(2.1.2), linter-clang(4.1.0) and linter ui-default(1.2.2) installed. I am using MacOS. Can anybody please help me in fixing this?

**Comment by whitexvadim** [comment]
Same problem, but OS is Ubuntu 16.04 LTS.

**Comment by steelbrain** [comment]
If both of you are on clang, see Landon's reply on https://discuss.atom.io/t/linter-not-working/41332/4

PS. This is an external bug and has nothing to do with base linter, closing but feel free to continue discussing
