### ISSUE TITLE
How to change colors on counter status bar

### ISSUE THREAD

**Issue by darahak** [steelbrain/linter#1415]
Hi,

I have a minor issue with the colors that are used for the error count (and possibly warning/info too).
I'm using the [Material](https://atom.io/themes/atom-material-ui) theme for Atom, and it's displayed like this:
![Linter status bar][screenshot]

It's really hard to read from my point of view, and I expected it to look like the GIF from the project's `README`.
It might not even be an issue with Linter, but I'm don't know where to look if I want to change these colors.
Your help would be much appreciated.

My environment details:
```
Atom 1.15.0
Windows 7 x64
Linter 2.1.2
```

[screenshot]: http://i.imgur.com/bjZyf17.png

**Comment by steelbrain** [comment]
Dupe of https://github.com/atom-material/atom-material-ui/issues/369
