### ISSUE TITLE
Assistance Requested: MacOSX issue

### ISSUE THREAD

**Issue by mschuchard** [steelbrain/linter#1419]
Have someone mschuchard/linter-terraform-syntax#3 who has issues using a linter. Note the only differences I can tell between his environment and the test environment is Linux versus MacOSX. Did something happen recently with MacOSX, Atom, etc. that is causing issues with linting in Atom in MacOSX?

Please take a look and offer an opinion.

**Comment by steelbrain** [comment]
Hi @mschuchard 

In linter 2.x, I've added a new command `linter:debug`, it contains some information that might help debug the issue

**Comment by mschuchard** [comment]
Thanks. Is this accessible from the `command palette`?

**Comment by steelbrain** [comment]
Yep!

<img src="https://cloud.githubusercontent.com/assets/4278113/24797958/167f1e2c-1bad-11e7-8aa7-9f0185f2245f.png">

<img src="https://cloud.githubusercontent.com/assets/4278113/24797968/20e2daac-1bad-11e7-9ad8-c2cc7fbfa3c5.png">

**Comment by mschuchard** [comment]
Thanks, I should be good from here.
