### ISSUE TITLE
Almost impossible to click links in tooltips before they dissapear

### ISSUE THREAD

**Issue by ssbarnea** [steelbrain/linter#1421]
It seems that the linter tooltips are configured to disappear as soon your mouse cursor moves away from the highlighted text or from the tooltip itself.

Because the links from the tooltip are at the end of the the text the user will struggle to click the link without ever crossing outside the tooltip box. That's... awful. 

![bash_profile__dotfiles_2017-04-07_14-07-41](https://cloud.githubusercontent.com/assets/102495/24801340/b5ecfd6a-1b9b-11e7-8117-aeb3681b91ac.png)

**Comment by steelbrain** [comment]
That's hard, yep. We have to come up with a smarter way to hide them. Thanks for reporting 👍

**Comment by ssbarnea** [comment]
I think that 1-2 seconds delay should be enough for avoiding this. Please note that I am not really a JS guy, so I doubt I will be able to find a solution myself. But I could help with testing and providing a safe range for default timings.  I know that getting them right is not always easy.

**Comment by steelbrain** [comment]
Totally forgot to tell you this but this issue belonged in `linter-ui-default` and not the base `linter`.

A fix is up in https://github.com/steelbrain/linter-ui-default/pull/244
