### ISSUE TITLE
Error running JSHint

### ISSUE THREAD

**Issue by pbrocker** [steelbrain/linter#1424]
Error running JSHint Error: /Users/USERNAME/.atom/packages/linter-jshint/node_modules/jshint-json/json.js:4(…)(anonymous function) @ /Users/USERNAME/.atom/packages/linter/lib/linter-registry.js:177

**Comment by steelbrain** [comment]
Hi @pbrocker 

This is an error in `linter-jshint`. Can you please reopen this over to their repo? Also when you do, make sure to include the contents (or screenshot) of Atom's Developer Tools' console
