### ISSUE TITLE
No linter interface in Atom on Mac

### ISSUE THREAD

**Issue by SKempin** [steelbrain/linter#1430]
Successfully using this on Windows, but on Mac I am not even getting an interface in Atom?
Running Atom 1.16 on Sierra 10.12.4. Are there more dependencies?

<img width="1170" alt="screen shot 2017-04-14 at 01 17 33" src="https://cloud.githubusercontent.com/assets/10877466/25028918/38be9a8c-20b0-11e7-9747-11c003a5e738.png">

**Comment by steelbrain** [comment]
Hi @SKempin 

This package is just the base linter, you have to install one of the many providers out there to get linting for Typescript. You can find a list of them on [`atomlinter.github.io`](http://atomlinter.github.io/)
