### ISSUE TITLE
name is no longer allowed

### ISSUE THREAD

**Issue by mschuchard** [steelbrain/linter#1431]
In the standard linter v2 migration guide, there is a line that says:

> name is no longer allowed

but that type appears in more than one standard v2 API example.

Is there a typo or am I missing something here?

**Comment by steelbrain** [comment]
There's actually two types of names, `name` on `linterProvider` and on `message`. It's required on `linterProvider` and no longer allowed on the `message`

**Comment by mschuchard** [comment]
Oh right, I completely forgot you could even do that. Thanks!
