### ISSUE TITLE
Error: spawn terraform ENOENT

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [steelbrain/linter#1436]
Hi, 
I am getting the following Error in Atom (1.15.0 x64) on Linux:

> [Linter] Error running Terraform Error: spawn terraform ENOENT(…)(anonymous function) @ /home/<username>/.atom/packages/linter/lib/linter-registry.js:15

Please let me know if you require more information and I'll provide it.

Regards

**Comment by steelbrain** [comment]
Hi @c2xbrhdj6u4qs15 

Please reopen this issue in linter-terraform. This repository is just the base linter.

Thanks!
