### ISSUE TITLE
Issue with standard linter v2

### ISSUE THREAD

**Issue by RohanVB** [steelbrain/linter#1439]
```
atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
OS: Mac OSX Sierra, Ubuntu
Reproducible on atom v1.15.0

We recently updated our linter to v2 standard linter, but then we get: 

![screen-shot-2017-04-21-at-11 26 19-pm](https://cloud.githubusercontent.com/assets/15197846/25309669/8d7eb984-27f0-11e7-9607-62aaf7300362.png)

Even though our [package.json](https://github.com/binore/coala-atom/blob/bd99cfc56a0d6e0a88eabd229441f7ba36667d04/package.json) is configured correctly. 

[Here](https://github.com/coala/coala-atom) is the link to our repo.
[Here](https://github.com/coala/coala-atom/pull/63/files) is the link to the breaking change.

Note that our release version works as desired, the recent upgrade patch to v2 when run by `apm link -d`, `atom -d` produces the error.

**Comment by steelbrain** [comment]
Did you forget to do `npm install` in that repository? Also the version of `atom-linter` in `package.json`::`dependencies` is super-old, not that it's causing the issue but you should upgrade to the latest version to include bugfixes and stuff

**Comment by RohanVB** [comment]
> Did you forget to do npm install in that repository?

Yes! This is what I was missing.

> version of atom-linter in package.json::dependencies is super-old, not that it's causing the issue but you should upgrade to the latest version to include bugfixes and stuff

I'll do this, thank you.
