### ISSUE TITLE
Dash causes linter to not underline whole error

### ISSUE THREAD

**Issue by OmgImAlexis** [steelbrain/linter#1440]
If there's an issue with importing a js package only the first half of the package name is highlighted when there's a dash in it. I'm not sure if this is an issue with this package or [atom-linter-xo](https://github.com/sindresorhus/atom-linter-xo).

![screen shot 2017-04-23 at 8 14 23 pm](https://cloud.githubusercontent.com/assets/6525926/25312818/8aa9a874-2861-11e7-96fc-6c36f8bfc8c5.png)

**Comment by steelbrain** [comment]
Hi @OmgImAlexis 

Thank you for opening the issue. This package is actually just the base linter, this is an issue in the provider so I would recommend you reopen this in `atom-linter-xo`
