### ISSUE TITLE
Linter doesnt work.

### ISSUE THREAD

**Issue by T1MOXA** [steelbrain/linter#1443]
![image](https://cloud.githubusercontent.com/assets/19938629/25392074/632e58fa-29e0-11e7-8bc1-72638ec7c6ac.png)

Linter Ui Default:
![image](https://cloud.githubusercontent.com/assets/19938629/25391931/0884a86e-29e0-11e7-994f-449d42c9eb70.png)
![image](https://cloud.githubusercontent.com/assets/19938629/25391941/0e6c63e8-29e0-11e7-93cf-39f30e57ed2d.png)

Linter:
![image](https://cloud.githubusercontent.com/assets/19938629/25391978/2369365e-29e0-11e7-984e-747739093281.png)

OS - Windows 10

**Comment by steelbrain** [comment]
Hi @T1MOXA,

Have you installed any of the Linter Providers? You can find a full list of them at [atomlinter.github.io](https://atomlinter.github.io)

**Comment by T1MOXA** [comment]
I'm so sorry.
I totally missed that...

My apologies!

**Comment by steelbrain** [comment]
It's okay, Thank you for using linter!

**Comment by T1MOXA** [comment]
Just a small question...
There are so many different packages, what is the right package for node JS ?

I put the JS Linter Standard but I was given strange results.
For example it seems to be necessary at the end of the line to put ;
But the Linter says it's not true.
(Extra semicolon)

So the same indentation
(Expected indent of 2 spaces but found 4 tabs.)

But if you make the gaps, then the code would look bad.

**Comment by Arcanemagus** [comment]
`standard` is designed to be a very restricted style. At it's core all that it is is a pre-packaged set of plugins and configurations for [ESLint](http://eslint.org/). If `standard` alone doesn't match the style you want for your code you might want to look into one of the many [shared configs](https://www.npmjs.com/search?q=eslint-config-&page=1&ranking=popularity) for it to find one that matches your desired style.

I would recommend finding one that is close, then tweaking the enabled rules to your liking. For example you can use [eslint-config-standard](https://www.npmjs.com/package/eslint-config-standard) to get the same base that `standard` gives you, then tweak the rules related to indentation.

**Comment by T1MOXA** [comment]
And another question, is it possible to hide certain warnings ?

**Comment by steelbrain** [comment]
In ESLint, you can, the ESLint syntax for disabling rules is

```json
{
  "extends": "some-config-name",
  "rules": {
    "rule-i-dont-like": "off"
  }
}
```

**Comment by T1MOXA** [comment]
I too "problematic" :)
How to configure ESLINT to get everything working ?
I put the Linter Eslint and after that to the folder with the bot (node) installed Eslint.
All right ?

**Comment by steelbrain** [comment]
Ha! Get that asked way too often

I've setup a repository with properly configured ESLint, you can find it at https://github.com/steelbrain/eslint-minimal-setup
