### ISSUE TITLE
Uncaught TypeError: _editorLinter2.default is not a constructor

### ISSUE THREAD

**Issue by thanaxix** [steelbrain/linter#1444]
[Enter steps to reproduce:]

1. Installed linter-htmlhint without having linter
2. Tried to install linter as a dependancy for the previous package.
3. Error came out

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.4

### Stack Trace

Uncaught TypeError: _editorLinter2.default is not a constructor

```
At /Users/thanaxix/.atom/packages/linter/lib/editor-registry.js:36

TypeError: _editorLinter2.default is not a constructor
    at EditorRegistry.createFromTextEditor (/packages/linter/lib/editor-registry.js:36:20)
    at /packages/linter/lib/editor-registry.js:25:12
    at Workspace.observeTextEditors (/app.asar/src/workspace.js:305:53)
    at EditorRegistry.activate (/packages/linter/lib/editor-registry.js:24:43)
    at Linter.registryEditorsInit (/packages/linter/lib/main.js:157:26)
    at Linter.registryEditorsIdleInit (/packages/linter/lib/main.js:128:14)
```

### Commands

```
  2x -2:52.7.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:44 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.7 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
autocomplete-html-entities 0.1.0 
busy-signal 1.4.0 
intentions 1.1.2 
linter 2.1.4 
linter-bootlint 1.0.4 
linter-htmlhint 1.3.3 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
```

**Comment by steelbrain** [comment]
This is an Atom internal issue. Restart should fix this. If it doesn't, uninstall/reinstall the linter package

**Comment by steelbrain** [comment]
Closing as no more info provided for months

**Comment by datesss** [comment]
I'm getting this issue ! :-( 
linter 2.2.0
atom 1.18.0
macOS 10.12.5

tried uninstalling / reinstalling

**Comment by Arcanemagus** [comment]
Can you post the output of running the `Linter: Debug` command from the Command Palette? Do you have steps to reproduce this?

**Comment by datesss** [comment]
Thanks for responding so fast!

Steps to reproduce:
The error shows up every time I open atom.

Output:
```
Platform: darwin
Atom Version: 1.19.0
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
  - stylelint
Disabled Linter Providers: 
Standard Linter Providers: 
  - ESLint
  - stylelint
Indie Linter Providers: 
  - Build
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: false
Current File Scopes: 
  - *
  - source.css.scss
  - meta.property-list.scss
  - punctuation.section.property-list.begin.bracket.curly.scss
```

**Comment by Arcanemagus** [comment]
@steelbrain Do you think maybe Atom isn't transpiling the files? It _should_ be, but I notice you only have `/* @flow */` at the top and no `'use babel'`.

**Comment by steelbrain** [comment]
@Arcanemagus Atom transpiles files with flow as well as use babel 😉

**Comment by Arcanemagus** [comment]
I know it _should_ be, but that's the only reason I can think of that this error would trigger.

**Comment by datesss** [comment]
i tried uninstalling/reinstalling atom, deleting my packages folder from the hard drive and re-installing plugins. Not sure what else to try :-(

**Comment by datesss** [comment]
I deleted a few random folders in my `/Users/{username}/.atom` directory (blob-store, compile-cache, recovery, storage), restarted atom, and it worked.  My guess is at some point atom got killed unexpectedly while compiling a plugin file and then got hung up on the bad version, or something like that?

**Comment by Arcanemagus** [comment]
Maybe? From the code here it should be impossible, hence why we are confused as to how this is happening 😉.
