### ISSUE TITLE
linter-highlight after downgrade

### ISSUE THREAD

**Issue by sluchznak** [steelbrain/linter#1446]
Linter:
v1.11.19

![2017-04-26_17-01-55](https://cloud.githubusercontent.com/assets/4091442/25431372/2f3482f0-2aa2-11e7-8f49-b2ce1a5efeb5.png)

My own `styles.less` is empty

**Comment by steelbrain** [comment]
Hi @sluchznak 

The latest in v1 series is actually v1.11.23

You might want to install that! :)
