### ISSUE TITLE
Build flags

### ISSUE THREAD

**Issue by chappy1978** [steelbrain/linter#1448]
Linter 2.1.4 Has started reporting an GCC error when I have build_flags set to --verbose in platformio.ini There are no real errors just warnings. Also it doesn't appear right away just some time later. 

Using built-in specs. Reading specs from /Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/device-specs/specs-attiny85 COLLECT_GCC=/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/avr-g++ COLLECT_LTO_WRAPPER=/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../libexec/gcc/avr/4.9.2/lto-wrapper Target: avr Configured with: ../gcc/configure --enable-fixed-point --enable-languages=c,c++ --prefix=/Users/jenkins/jenkins/workspace/avr-gcc/label/mac-mini/objdir --enable-long-long --disable-nls --disable-checking --disable-libssp --disable-libada --disable-shared --enable-lto --with-avrlibc=yes --with-dwarf2 --disable-doc --target=avr Thread model: single gcc version 4.9.2 (GCC) COLLECT_GCC_OPTIONS='-fsyntax-only' '-fno-exceptions' '-fno-threadsafe-statics' '-fpermissive' '-std=gnu++11' '-g' '-Os' '-Wall' '-ffunction-sections' '-fdata-sections' '-flto' '-v' '-D' 'F_CPU=8000000L' '-D' 'PLATFORMIO=30300' '-D' 'ARDUINO_ARCH_AVR' '-D' 'ARDUINO_AVR_ATTINY85' '-D' 'ARDUINO=10617' '-fmax-errors=15' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/cores/tiny' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/variants/tinyX5' '-I' '/Users/mrspriggs1/Documents/Arduino/Robot1/Digispark/RobotDebug/src' '-I' '/Users/mrspriggs1/Documents/Arduino/Robot1/Digispark/RobotDebug/lib/Filter' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/EEPROM' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/SPI' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Servo/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/SoftwareSerial' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Wire' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Wire/utility' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground/utility' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Bridge/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/EEPROM/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Esplora/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Ethernet/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Firmata' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Firmata/utility' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/GSM/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/HID/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Keyboard/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/LiquidCrystal/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Mouse/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/RobotIRremote/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Robot_Control/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Robot_Motor/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SD/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SPI/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SPI1/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Scheduler/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Servo/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SoftwareSerial/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SpacebrewYun/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Stepper/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/TFT/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Temboo/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/USBHost/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/WiFi/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Wire/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Wire1/src' '-I' '/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/avr/include' '-I' '/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include' '-I' '/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include-fixed' '-specs=device-specs/specs-attiny85' '-mmcu=avr25' /Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../libexec/gcc/avr/4.9.2/cc1plus -quiet -v -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/cores/tiny -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/variants/tinyX5 -I /Users/mrspriggs1/Documents/Arduino/Robot1/Digispark/RobotDebug/src -I /Users/mrspriggs1/Documents/Arduino/Robot1/Digispark/RobotDebug/lib/Filter -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/EEPROM -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/SPI -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Servo/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/SoftwareSerial -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Wire -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Wire/utility -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground/utility -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Bridge/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/EEPROM/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Esplora/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Ethernet/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Firmata -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Firmata/utility -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/GSM/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/HID/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Keyboard/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/LiquidCrystal/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Mouse/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/RobotIRremote/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Robot_Control/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Robot_Motor/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SD/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SPI/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SPI1/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Scheduler/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Servo/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SoftwareSerial/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SpacebrewYun/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Stepper/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/TFT/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Temboo/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/USBHost/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/WiFi/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Wire/src -I /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Wire1/src -I /Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/avr/include -I /Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include -I /Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include-fixed -imultilib avr25 -iprefix /Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/ -D__AVR_ATtiny85__ -D__AVR_DEVICE_NAME__=attiny85 -D F_CPU=8000000L -D PLATFORMIO=30300 -D ARDUINO_ARCH_AVR -D ARDUINO_AVR_ATTINY85 -D ARDUINO=10617 /var/folders/n5/h0kzv92x77ndnf5dkk_2wtzw0000gn/T/7dc68404-629c-4a1d-b2c3-747c2c002807.cpp -mn-flash=1 -mno-skip-bug -quiet -dumpbase 7dc68404-629c-4a1d-b2c3-747c2c002807.cpp -mmcu=avr25 -auxbase 7dc68404-629c-4a1d-b2c3-747c2c002807 -g -Os -Wall -std=gnu++11 -version -fsyntax-only -fno-exceptions -fno-threadsafe-statics -fpermissive -ffunction-sections -fdata-sections -flto -fmax-errors=15 -o /dev/null -mn-flash=1 -mno-skip-bug -fno-rtti -fno-enforce-eh-specs -fno-exceptions GNU C++ (GCC) version 4.9.2 (avr) compiled by GNU C version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00), GMP version 5.0.2, MPFR version 3.0.0, MPC version 0.9 GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072 ignoring nonexistent directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/../../../../avr/include/c++/4.9.2" ignoring nonexistent directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/../../../../avr/include/c++/4.9.2/avr/avr25" ignoring nonexistent directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/../../../../avr/include/c++/4.9.2/backward" ignoring nonexistent directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/../../../../avr/sys-include" ignoring nonexistent directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/../../lib/gcc/avr/4.9.2/../../../../avr/include/c++/4.9.2" ignoring nonexistent directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/../../lib/gcc/avr/4.9.2/../../../../avr/include/c++/4.9.2/avr/avr25" ignoring nonexistent directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/../../lib/gcc/avr/4.9.2/../../../../avr/include/c++/4.9.2/backward" ignoring duplicate directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/../../lib/gcc/avr/4.9.2/include" ignoring duplicate directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/../../lib/gcc/avr/4.9.2/include-fixed" ignoring nonexistent directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/../../lib/gcc/avr/4.9.2/../../../../avr/sys-include" ignoring duplicate directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/../../lib/gcc/avr/4.9.2/../../../../avr/include" ignoring duplicate directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/avr/include" as it is a non-system directory that duplicates a system directory ignoring duplicate directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include" as it is a non-system directory that duplicates a system directory ignoring duplicate directory "/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include-fixed" as it is a non-system directory that duplicates a system directory #include "..." search starts here: #include <...> search starts here: /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/cores/tiny /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/variants/tinyX5 /Users/mrspriggs1/Documents/Arduino/Robot1/Digispark/RobotDebug/src /Users/mrspriggs1/Documents/Arduino/Robot1/Digispark/RobotDebug/lib/Filter /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/EEPROM /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/SPI /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Servo/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/SoftwareSerial /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Wire /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Wire/utility /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground/utility /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Bridge/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/EEPROM/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Esplora/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Ethernet/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Firmata /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Firmata/utility /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/GSM/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/HID/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Keyboard/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/LiquidCrystal/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Mouse/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/RobotIRremote/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Robot_Control/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Robot_Motor/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SD/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SPI/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SPI1/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Scheduler/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Servo/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SoftwareSerial/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SpacebrewYun/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Stepper/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/TFT/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Temboo/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/USBHost/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/WiFi/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Wire/src /Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Wire1/src /Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/include /Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/include-fixed /Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/../../../../avr/include End of search list. GNU C++ (GCC) version 4.9.2 (avr) compiled by GNU C version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00), GMP version 5.0.2, MPFR version 3.0.0, MPC version 0.9 GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072 Compiler executable checksum: ec61072030ec869b25f1b5729d08dcfb COMPILER_PATH=/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../libexec/gcc/avr/4.9.2/:/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../libexec/gcc/:/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ LIBRARY_PATH=/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/avr25/:/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/../../../../avr/lib/avr25/:/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/:/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/:/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/4.9.2/../../../../avr/lib/ COLLECT_GCC_OPTIONS='-fsyntax-only' '-fno-exceptions' '-fno-threadsafe-statics' '-fpermissive' '-std=gnu++11' '-g' '-Os' '-Wall' '-ffunction-sections' '-fdata-sections' '-flto' '-v' '-D' 'F_CPU=8000000L' '-D' 'PLATFORMIO=30300' '-D' 'ARDUINO_ARCH_AVR' '-D' 'ARDUINO_AVR_ATTINY85' '-D' 'ARDUINO=10617' '-fmax-errors=15' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/cores/tiny' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/variants/tinyX5' '-I' '/Users/mrspriggs1/Documents/Arduino/Robot1/Digispark/RobotDebug/src' '-I' '/Users/mrspriggs1/Documents/Arduino/Robot1/Digispark/RobotDebug/lib/Filter' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/EEPROM' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/SPI' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Servo/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/SoftwareSerial' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Wire' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/__cores__/tiny/Wire/utility' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Adafruit_CircuitPlayground/utility' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Bridge/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/EEPROM/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Esplora/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Ethernet/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Firmata' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Firmata/utility' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/GSM/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/HID/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Keyboard/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/LiquidCrystal/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Mouse/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/RobotIRremote/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Robot_Control/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Robot_Motor/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SD/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SPI/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SPI1/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Scheduler/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Servo/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SoftwareSerial/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/SpacebrewYun/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Stepper/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/TFT/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Temboo/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/USBHost/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/WiFi/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Wire/src' '-I' '/Users/mrspriggs1/.platformio/packages/framework-arduinoavr/libraries/Wire1/src' '-I' '/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/avr/include' '-I' '/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include' '-I' '/Users/mrspriggs1/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include-fixed' '-specs=device-specs/specs-attiny85' '-mmcu=avr25'	
PIO Buildsrc/Robot1_debug.ino10075:1
LFUTF-8C++

**Comment by steelbrain** [comment]
Hi @chappy1978

Thank you so much for reporting this error, this is just the base linter repo, I would recommend you move it over to platform-io package's repository.

Thank you for using linter!
