### ISSUE TITLE
Keymap for toggle

### ISSUE THREAD

**Issue by DanielAndreasen** [steelbrain/linter#1452]
Thanks for this package.
I'm having troubles using my keymap for toggle, something I feel is essential. I can't find anything on this. Previously I had this snippet which worked just perfect:

    'atom-text-editor':
        'f5': 'linter:toggle'

Is there no way to make this work again?
Sorry if this is a duplicate, bit I can't find any recent issues on this.

I'm using Atom 1.16.0 and linter 2.1.4

**Comment by steelbrain** [comment]
Hi @DanielAndreasen 

Since v2 the command has been renamed to `linter:toggle-active-editor` to make it's purpose clear. Let me know if this fixes your issue

**Comment by DanielAndreasen** [comment]
Much better. Thanks a lot!
