### ISSUE TITLE
Linter attempts to read config files for removed projects.

### ISSUE THREAD

**Issue by erikh2000** [steelbrain/linter#1454]
After making an edit to a source file, this message appears in my developer log console:

/Users/erik.hermansen/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running ESLint Error: Cannot read config file: /my-home-dir/**some-old-project-of-mine**/index.js(…)

"some-old-project-of-mine" mentioned above is a project that _used_ to be added to the IDE, _but has been removed_. It is expected that the path that linter is complaining about would not be present, because that project has been removed. It's unexpected that linter would continue trying to find files within that removed project folder.

Maybe there is a configuration file someplace that linter looks at which needs to be updated?

I have the following installed:
- Atom 1.16.0 (MacOS)
- linter 2.1.4
- linter-eslint 8.1.7
- linter-ui-default 1.2.3 

Stack trace:

linter-registry.js [sm]:137 [Linter] Error running ESLint Error: Cannot read config file: /my-home-dir/some-old-project-of-mine/index.js(…)
- (anonymous function) @ linter-registry.js [sm]:137
- _tickCallback @ internal/process/next_tick.js:103

**Comment by steelbrain** [comment]
> /Users/erik.hermansen/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running ESLint Error: Cannot read config file: /my-home-dir/some-old-project-of-mine/index.js(…)


Hi @erikh2000

This is actually a linter-eslint related issue. Could you please open it in that repo?

Thanks!

**Comment by erikh2000** [comment]
Will do! Thanks for considering the bug.
