### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by richardbushell** [steelbrain/linter#1455]
FEATURE REQUEST:-
Linter's Status Bar function is incredibly useful.
Would it be possible to add a Visual confirmation that Linter is ENABLED here too?
For instance, there's no way to determine currently if:
Linter: Toggle Active Editor
has set Active or Inactive
(unless we then force an error to confirm)

It would also be great to add 3 shortcut buttons (or a quick access popup) in the Status Bar to the Linter commands, e.g:
Linter: Toggle Active Editor
Linter: Disable Linter
Linter: Enable Linter

**Comment by steelbrain** [comment]
Hi @richardbushell 

We have `linter:debug` command that shows list of linters matching current scope
<img src="https://cloud.githubusercontent.com/assets/4278113/25586517/14cf724c-2eb9-11e7-98a2-6296f6de5304.png">

Furthermore, you can hover the busy signal indicator to see which linter provider was executed where
<img src="https://cloud.githubusercontent.com/assets/4278113/25586561/4453c590-2eb9-11e7-8dfd-8f7d7b1bf035.png">



Does this take care of your usecase?

**Comment by richardbushell** [comment]
Not quite... in particular why not apply CSS to grey out Linter Status Bar digits (or red digits/underline, other visual indicator) when Linter: Toggle Active Editor is DISABLED? And maybe green digits/underline on non-grey out when ACTIVE? Knowing it's ON/OFF would be great. Beyond my current knowledge to submit a PR for this unfortunately.

**Comment by steelbrain** [comment]
Sounds like a fair request, can you reopen this on [linter-ui-default](https://github.com/steelbrain/linter-ui-default/issues/new) repo please?

Thank you!
