### ISSUE TITLE
Error running Unknown Error: Process execution timed out

### ISSUE THREAD

**Issue by JGH1000** [steelbrain/linter#1461]
Every 20 seconds I get an error popup saying to see console for more information. When I do, there are several messages all with this error:

[Linter] Error running Unknown Error: Process execution timed out(…)(anonymous function) @ /home/usr/.atom/packages/linter/lib/linter-registry.js:159

I have to turn off linter as it is unusable. Everything is up to date, both Atom and linter.

**Comment by joseluisch** [comment]
console.error(`[Linter] Error running ${linter.name}`, error)
linter-registry.js:137 [Linter] Error running PHP Error: Failed to spawn command `php`. Make sure `php` is installed and on your PATH(…)(anonymous function) @ linter-registry.js:137_tickCallback @ internal/process/next_tick.js:103

**Comment by JGH1000** [comment]
FYI, I have a Python and R kernels so not sure if this is the same type of error.

**Comment by Arcanemagus** [comment]
@JGH1000 What providers do you have installed?

@joseluisch Reading your error I'm _guessing_ that you have `linter-php` installed, but don't have `php` installed on your system. You should try fixing that first and if you are still having issues in there then please file an issue on `linter-php`.

**Comment by JGH1000** [comment]
@Arcanemagus By providers you mean linters? linter-pylama and linter-lintr. I disabled lintr and still get this message spam thought the linter itself seems to work fine.

**Comment by JGH1000** [comment]
Not sure if this matters but I did not install the busy-signal and the other optional dependency for linter-ui-default as I see no use for them.

**Comment by steelbrain** [comment]
Hi @JGH1000

If you could post a list of all community installed packages, that would be very helpful. From the error message it seems that the linter provider is not specify a name for itself, or this would've been relatively easy to resolve. That's why linter is showing that provider as the `Unknown` provider.

**Comment by JGH1000** [comment]
Hi @steelbrain sure, here it is. Happy to help in pinpointing the issue.

Hydrogen@1.12.1
MagicPython@1.0.10
Sublime-Style-Column-Selection@1.7.4
atom-material-ui@1.3.10
autocomplete-python@1.8.63
file-icons@2.1.4
highlight-line@0.12.0
highlight-selected@0.13.1
hydrogen-launcher@1.2.1
hyperclick@0.0.40
language-r@0.4.1
linter@2.1.4
linter-lintr@1.1.4
linter-pylama@0.8.19
linter-ui-default@1.2.4
minimap@4.28.2
minimap-cursorline@0.2.0
minimap-find-and-replace@4.5.2
minimap-highlight-selected@4.6.1
minimap-linter@2.0.0
minimap-selection@4.4.0
platformio-ide-terminal@2.5.0
python-tools@0.6.9
simple-drag-drop-text@0.3.4
sort-lines@0.14.0

**Comment by steelbrain** [comment]
I've dug up manifests of the listed packages and the only linter providers in them are `linter-lintr`, and `linter-pylama`, both using the Standard Linter API

@JGH1000 Can you disable `linter-pylama.isortOnSave` config and see if you still get the error?

**Comment by JGH1000** [comment]
It is already off. I tried disabling linter-pylama, linter-lintr and minimap-linter independently, but in all cases I still get the message.

**Comment by JGH1000** [comment]
@steelbrain turns out the lack of lintr package was causing the problem. I did not connect the issues as linter-lintr was disabled so I did not expect any R related components to be the cause.

Not sure if this is an issue or we can close it.

**Comment by JGH1000** [comment]
linter-registry.js [sm]:137 [Linter] Error running Unknown Error: Process execution timed out(…)(anonymous function) @ linter-registry.js [sm]:137
