### ISSUE TITLE
getLocationFromRangeIndex is not a function running ESLint + Prettier

### ISSUE THREAD

**Issue by christianalfoni** [steelbrain/linter#1464]
Hi there,

I just installed `prettier`, `eslint-plugin-prettier` and `eslint-config-prettier` to my project, and added eslintrc file as suggested in the docs of eslint-plugin-prettier. I also have the Atom packages `linter` and `linter-eslint`.

When I try to save a file I get: 

Error running ESLint Error: require(...).getLocationFromRangeIndex is not a function(…)

This does not happen when I remove prettier plugin though, so maybe I should rather create an issue there. :) But yeah, wanted to try here as well

**Comment by Arcanemagus** [comment]
`getLocationFromRangeIndex` looks like an internal ESLint function, it's not part of `linter-eslint` at least. If you can't find something related to it from Googling feel free to file an issue on `linter-eslint`, making sure you include the debugging information requested there.

**Comment by christianalfoni** [comment]
@Arcanemagus Thanks for the answer :)

If anyone comes by this issue for some reason, it was my global eslint messing it up. Made sure the "Use global eslint" config at the bottom of the linter-eslint plugin for Atom was turned off and installed eslint and eslint-plugin-react again to my local project.

**Comment by Arcanemagus** [comment]
> Made sure the "Use global eslint" config at the bottom of the linter-eslint package for Atom was turned off and installed eslint and eslint-plugin-react again to my local project.

That's the recommended configuration for many reasons, the primary one being that if anyone else is working on the project they get the same configuration you are using 😉.
