### ISSUE TITLE
Error running PHP

### ISSUE THREAD

**Issue by joseluisch** [steelbrain/linter#1466]
because this error
![index php cxampphtdocsmi pagina atom](https://cloud.githubusercontent.com/assets/28614760/25982437/80de126a-36aa-11e7-8dce-f0a3d7b17546.jpg)
![index php mi pagina cxampphtdocsmi pagina atom](https://cloud.githubusercontent.com/assets/28614760/25982439/81073f28-36aa-11e7-9f66-b8de4146a73f.jpg)

**Comment by Arcanemagus** [comment]
This has nothing to do with `linter` itself. The problem is described in the messages in the console, however if you are still having issues after fixing that please file a new issue on the `linter-php` repo.
