### ISSUE TITLE
Transparency problem on the error popup

### ISSUE THREAD

**Issue by sutrej** [steelbrain/linter#1468]
Hello,

Since last update (not sure though), the popup message when hovering warnings and errors is so transparent I cannot read it anymore. I've tried to look for it in the linter code but did not find any css to modify. Anybody have an idea ?

![image](https://cloud.githubusercontent.com/assets/25735231/26243913/e7b358b8-3c8d-11e7-80ad-77c5ca9340a8.png)
Mouse is hovering first line here.

**Comment by steelbrain** [comment]
You can expect the fix in a day or less.
Duplicate of https://github.com/steelbrain/linter-ui-default/issues/309
