### ISSUE TITLE
Linter is not linting Javascript or CSS files, but will lint HTML

### ISSUE THREAD

**Issue by grandslammer** [steelbrain/linter#1469]
I installed Atom yesterday, and noticed this issue today. All was working fine yesterday.

I had several javascript linters installed (JShint, JSlint, ternJS), and stylelint for CSS (I had csslint installed but that had an issue so I installed stylelint).

Initially I noticed the javascript wasn't working, and spend ages Googleing the issue but none of the solutions worked which mostly suggested going into the config.cson file.

I've tried reinstalling all the js linters and Linter itself, and only using one of the js linters.

HTML files are linting properly!

I have not tested other file types as I have not been working on them since installing.

I honestly didn't know what repo to put this issue on, but seeing as it's affecting all my js linters and css, it seems that the issue is not unique to one specific linter, so I'm putting it here on the main Linter repo.

Also initally the linters were not showing any issues/warnings in the linting panel at the bottom left, however right now after all my troubleshooting etc, I just have the ternjs linter installed (for Javascript), and htmlhint and stylelint. Now, however, I have a red warning symbol on the linting panel with one error, but when I open the linting panel there are no items in it! This is affecting both javascript files and CSS, and both files have plenty of errors in them (I literally created a new js and a new css file and typed lines of gibberish into them.

Can anybody help me please? I don't know what may have caused this, especially as it's a fresh installation of Atom! Maybe the different javascript linters have interfered or conflicted with each other? (Sidenote is it ok to have different javascript linters installed?)

Thanks!!!

**Comment by grandslammer** [comment]
Update:

So I did a full reinstall of Atom, and now the CSS files are linting but javascript files are not! I have tried everything, including different linters.

I've tried these instructions:

https://atom.io/packages/linter-eslint

https://github.com/AtomLinter/linter-eslint

http://devnull.guru/get-started-with-eslint/

https://atom.io/packages/linter-jshint

https://github.com/AtomLinter/linter-jshint

None of them worked! I don't know what is happening...

Can somebody please help!

**Comment by grandslammer** [comment]
Ok so I managed to get JSHint working by changing the file type from Babel to Javascript in the selector on the bottom right of Atom. ESLint is still not working however, and gives an error message upon file save or file open. I'll close the issue.

**Comment by Arcanemagus** [comment]
@grandslammer The providers by default only activate for Javascript, it looks like you have installed `language-babel` and for some bizarre reason the author of that package has decided to mark all Javascript files as "Babel" files, which isn't a recognized language so linting isn't triggered. I've tried filing issues about this before but the author of that package insists they know what they are doing, regardless of how many problems it causes for their users and other packages...

If you could file an issue on `linter-eslint` with the error message you are getting we can troubleshoot that further there. Make sure you include all the requested debugging information!

**Comment by grandslammer** [comment]
@Arcanemagus Thanks! Yeah I do have language-babel installed, and I am having issues with both jshint and eslint. I'll work around it for now.
