### ISSUE TITLE
Getting error message popup even theres no error

### ISSUE THREAD

**Issue by yawalkar** [steelbrain/linter#1470]
I just updated the atom to 1.17.0 and also the linter package to 2.1.4. Now while writing the code, each time I stop writing, I get the error message popup saying to check the console for errors even there's no error. I tried changing the option to link on change, and now, on every time I save the work, I get the same error prompt link in the following screenshot - 

https://cl.ly/1v2L3D1W051H

Even there's no error, I get this every time I save the work in Atom.

**Comment by Arcanemagus** [comment]
Please file this on [linter-phpcs](https://github.com/AtomLinter/linter-phpcs/issues/new) and include the information from the Console in the Developer Tools as without that this will be impossible to diagnose.
