### ISSUE TITLE
Linter not showing errors on OS X

### ISSUE THREAD

**Issue by sbking** [steelbrain/linter#1471]
Debug output:

    Platform: darwin
    Atom Version: 1.17.0
    Linter Version: 2.1.4
    All Linter Providers: 
      - TSLint
    Matching Linter Providers: 
      - TSLint
    Disabled Linter Providers; 
    Current File scopes: 
      - *
      - source.tsx

On my Arch Linux machine with identical `.atom` directory, it is working fine. On this mac, I just see a constant spinning circle, and when I hover over that I see:

    Current:
    tslint on foo.tsx

But no tslint errors are shown in any way. Oddly, if the "Fix errors on save" option is enabled, certain errors like whitespace issues are fixed on save but never shown in the editor.

If I disable the "Try using the local tslint package" option, the linter shows errors but only on save.

**Comment by steelbrain** [comment]
Hi @sbking 

This looks like an issue with TSLint because linter is matching it correctly with the grammar scopes and invoking it, but it never returns any response. Can you retry this with another linter provider and confirm that they work for you?

**Comment by steelbrain** [comment]
Closing as no reply received in more than a year.
