### ISSUE TITLE
tengo este error tiene es el linder o php?

### ISSUE THREAD

**Issue by juliobenavides2144** [steelbrain/linter#1475]
![hola](https://cloud.githubusercontent.com/assets/28970310/26478579/1ecdd942-419b-11e7-8759-77720fbc2a59.png)

**Comment by steelbrain** [comment]
Hi @juliobenavides2144

Can you follow the instructions and open the developer tools and show us what you see there?

**Comment by juliobenavides2144** [comment]
hihihi
![captura de pantalla de 2017-05-28 14-00-51](https://cloud.githubusercontent.com/assets/28970310/26531266/b30d989e-43b3-11e7-89fc-1b212281bad7.png)
esto es lo que aparece

**Comment by steelbrain** [comment]
Hi @juliobenavides2144 

The error is being thrown from another package `linter-phpmd`. While I'm not the maintainer of that package, could you make sure that you have the `php7` installed on your computer? and that it's available in your `PATH` environment variable?

**Comment by Arcanemagus** [comment]
Marking this as closed, this has nothing to do with `linter` itself and no further discussion ever resulted from this.
