### ISSUE TITLE
Message panel should have a sticky header

### ISSUE THREAD

**Issue by yoseldvp** [steelbrain/linter#1478]
When there are a lot of messages on the messages panel, if the user scrolls down, the header goes away with the rest of the content. 

![image](https://cloud.githubusercontent.com/assets/2691814/26642250/bee36c70-45f2-11e7-9db2-61d54048f361.png)

For these messages panel the title header should be sticky so the user can tell what is each column about every time. 

![image](https://cloud.githubusercontent.com/assets/2691814/26642203/856b9f80-45f2-11e7-9fb9-9fbc7531a96f.png)

I'm using:

```
Linter: 2.1.0
Atom: 1.17.2 x64
OS: Windows 10
```

**Comment by Arcanemagus** [comment]
Please re-file this on [linter-ui-default](https://github.com/steelbrain/linter-ui-default/issues), this package no longer has anything to do with the UI 😉.

**Comment by steelbrain** [comment]
As for the reason the panel does not have a sticky header, there's two reasons

1. It's pretty difficult to make it work with sticky header and still make the dock resizable 😛 
2. Sticky header wastes a lot of expensive screen real estate

**Comment by Arcanemagus** [comment]
Note: Re-filed as https://github.com/steelbrain/linter-ui-default/issues/340
