### ISSUE TITLE
Allow overriding `linterName` in messages?

### ISSUE THREAD

**Issue by hansonw** [steelbrain/linter#1485]
In the Language Service Protocol (https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md), diagnostics (`interface Diagnostic`) can specify dynamic sources.

One use case for this might be for a JavaScript language server, where diagnostics can come from both a typing system (Flow, TypeScript) and linters (ESLint); it makes sense to distinguish between them.

When bridging this with the Linter API (as https://github.com/atom/atom-languageclient is doing), this presents a slight issue as it's designed around registering fixed source names. It's certainly possible to dynamically register linters as diagnostics come in (especially with Indie v2), but that's rather heavyweight.

Would it be reasonable to allow for users to override `linterName` in the Message v2 API (from https://github.com/steelbrain/linter/blob/master/docs/types/linter-message-v2.md)? The semantics would be pretty straightforward - if you provide a custom `linterName` then Linter would use it, but otherwise it'd default to the name of the linter.

See: https://github.com/atom/atom-languageclient/issues/47

**Comment by steelbrain** [comment]
Sounds reasonable
