### ISSUE TITLE
Option to count errors, warnings & infos from current tab NOT all opened tabs

### ISSUE THREAD

**Issue by guizoxxv** [steelbrain/linter#1487]
Linter gutter shows counts of errors, warnings & infos from all opened tabs. I don't think this makes sense as if i expand the messages it only displays those from the current tab. I think it would be interesting to have the option to count and display all opened tabs errors, warnings & infos and be able to double click to navigate to target tab line OR count and display only current tab errors, warnings & infos.

**Comment by steelbrain** [comment]
You can actually change the status bar represents config to current file :)

**Comment by guizoxxv** [comment]
How can i do so? I did not see an option to do so in linter package settings.

**Comment by steelbrain** [comment]
See configuration for the `linter-ui-default` package
