### ISSUE TITLE
Linter closes bottom Dock on interaction

### ISSUE THREAD

**Issue by dmlux** [steelbrain/linter#1488]
Hi,

It seems that the Linter package causes the bottom dock of the workspace to close on clicking the Linter tab or the Linter content. If other packages use the bottom dock too it is very frustrating when you want to change to the Linter view to see Linter messages and the dock is hiding instead of showing some information.

It is also not possible to move the Linter view inside of the bottom dock.

![problem](https://user-images.githubusercontent.com/5197513/27036649-d3190b22-4f85-11e7-9314-e547ec10987e.gif)

**Comment by steelbrain** [comment]
Fixed in v1.6.1

Changed the default for `hidePanelWhenEmpty` to false because it was causing too much confusion

**Comment by Positive07** [comment]
I can still replicate this behaviour in 1.6.1 with `hidePanelWhenEmpty` disabled.

![atom-linter-ui-default-hide-issue](https://user-images.githubusercontent.com/1095969/27065048-4950109c-4fd1-11e7-89cf-91a2655e5031.gif)

**Comment by Positive07** [comment]
Fixed in linter-ui-default 1.6.2
