### ISSUE TITLE
Linter pane should close when 0 lints are found

### ISSUE THREAD

**Issue by macgyver** [steelbrain/linter#1491]
Hey there, this is more of a feature request, or maybe I'm just doing something wrong - I think the linter pane should close when there's no lint

1. linter pane is closed, file is good
2. make some lint in the file, so that the linter pane is displayed explaining the problem
3. fix the problem

expected: linter pane would go away
observed: linter pane persists

![linter-persistence](https://user-images.githubusercontent.com/1163/27134402-711e5990-50e3-11e7-9203-97f43f23aae0.gif)

**Comment by nobleach** [comment]
This indeed appears to be a regression. You may close the pane entirely (via the 'x' on the right-hand side) but it will no longer open automatically.

**Comment by Arcanemagus** [comment]
You just need to enable the "Hide when empty" option in the `linter-ui-default` settings.

It was disabled by default as it was confusing many users, and would hide the dock when other items were in it as well which was problematic.
