### ISSUE TITLE
Clicking linter panel makes messages dissappear

### ISSUE THREAD

**Issue by tayden** [steelbrain/linter#1495]
When I try to click the linter message in the linter panel, all the messages disappear as though I'm opening a new tab. I seem to remember being able to jump to the line the error was located on.

Before clicking:
![Before clicking](https://preview.ibb.co/edTeoQ/1.jpg)

After clicking:
![After clicking](https://image.ibb.co/eZ1zoQ/2.jpg)

Mac OSx: 10.12.5
Atom: 1.17.2
Electron: 1.3.15
Chrome: 52.0.2743.82
Node: 6.5.0

**Comment by steelbrain** [comment]
Change panel represents to Entire Project. This is an Atom issue, fix (atom/atom#14695) will be in next stable version hopefully
