### ISSUE TITLE
Linter bottom inspector always open

### ISSUE THREAD

**Issue by knzudgt** [steelbrain/linter#1496]
Linter bottom inspector can be toggled by clicking on the relative bottom arrow, like with the tree view and the Git tab (left and right arrows). However the Linter inspector is opened by default in every open document, so that, if the user is working on 10 documents, there are 10 open Linter inspectors. Also, after closing the current document's Linter inspector and switching to a different document, when returning to the former document the Linter inspector is back open. That's weird and annoying. I personally expect that if the user closes it it stays closed unless the user himself decides to toggle it .

![linter](https://user-images.githubusercontent.com/15718033/27259916-ae0a35d4-541e-11e7-99e3-e07685c941fc.png)

Atom version: 1.18.0
Linux Ubuntu 14.04 LTS
Community packages: busy-signal, file-icons, intentions, linter, linter-ruby, linter-ui-default

**Comment by steelbrain** [comment]
You can invoke the `Linter Ui Default: Toggle Panel` command to toggle it
