### ISSUE TITLE
linter@2.2.0 does not seem to lint on Arch

### ISSUE THREAD

**Issue by DeviaVir** [steelbrain/linter#1498]
```
$ atom --version
Atom    : 1.18.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0
```

Packages:

```
$ apm ls

[..snipped..]

Community Packages (35) /home/chase/.atom/packages
├── atom-ftp-editor@0.5.0 (disabled)
├── autocomplete-python@1.8.64
├── bliss-ui@0.4.1
├── busy-signal@1.4.3
├── editorconfig@2.2.2
├── intentions@1.1.2
├── language-docker@1.1.8
├── language-groovy@0.7.0
├── language-puppet@0.22.0
├── language-terraform@0.8.1
├── linter@2.2.0
├── linter-ansible-linting@1.3.0
├── linter-ansible-syntax@1.2.0 (disabled)
├── linter-csslint@1.3.4 (disabled)
├── linter-docker@0.2.0
├── linter-eslint@8.2.1
├── linter-json-lint@0.1.2
├── linter-markdown@4.0.1
├── linter-phpmd@1.5.3
├── linter-puppet-lint@0.8.2
├── linter-pycodestyle@2.0.2 (disabled)
├── linter-pyflakes@0.3.2 (disabled)
├── linter-python@3.1.2
├── linter-python-pep8@0.2.0 (disabled)
├── linter-sass-lint@1.7.4 (disabled)
├── linter-scss-lint@3.1.0 (disabled)
├── linter-terraform-syntax@1.2.0 (disabled)
├── linter-tidy@2.3.1 (disabled)
├── linter-travis-lint@1.0.0 (disabled)
├── linter-ui-default@1.6.1
├── loved-syntax@1.0.1
├── minimap@4.28.2
├── minimap-linter@2.0.0
├── pristine-ui@1.0.15
└── pure-syntax@0.2.1
```

`config.cson`:

```
linter: {}
  "linter-eslint":
    fixOnSave: false
    globalNodePath: "/home/chase/.nvm/versions/node/v7.3.0"
    useGlobalEslint: true
  "linter-phpmd": {}
  "linter-puppet-lint":
    executablePath: "/home/chase/.gem/ruby/2.4.0/bin/puppet-lint"
    oldVersion: false
  "linter-python":
    executablePath: "/home/chase/.local/bin/pylama"
    lintTrigger: "File saved or modified"
    withPep8: true
    withPyflakes: true
    withPylint: true
  "linter-scss-lint":
    executablePath: "/home/chase/.gem/ruby/2.4.0/bin/scss-lint"
  "linter-ui-default":
    hidePanelWhenEmpty: true
    panelHeight: 81
    showPanel: true
```

I verified all of the above paths work and their executables return the expected data.

There are no errors in the console, except for perhaps warnings:
![screenshot_2017-06-20_12-07-52](https://user-images.githubusercontent.com/777823/27328087-1b340020-55b1-11e7-8a1f-089e01a3b82c.png)

The main problem, is that when I write code I know is bad and should make a linter yell at me, it does not compute at all. I have tried different linters (eslint, pylint, json, scss), tried disabling everything and only have one linter and still it wouldn't lint. I have also tried rm'ing `~/.atom` and starting from scratch with the same result.

Is there anything else I can try? Is this a bug with versions I'm using?

Appreciate any pointers you can give me, thanks!

**Comment by DeviaVir** [comment]
Looks like installing an older version (i.e. `apm install linter@2.1.4`) also does not work.

**Comment by Arcanemagus** [comment]
Can you post the `Linter: Debug` command output from a file you are expecting linting output on?

**Comment by DeviaVir** [comment]
@Arcanemagus didn't know that was a thing, results:

```
Platform: linux
Atom Version: 1.18.0
Linter Version: 2.2.0
Opened file is ignored: Yes
Matching Linter Providers: 
  - Python Linter
Disabled Linter Providers: 
Standard Linter Providers: 
  - Ansible-Lint
  - dockerlint
  - ESLint
  - json-lint
  - PHPMD
  - Puppet-Lint
  - Python Linter
  - remark-lint
Indie Linter Providers: 
UI Providers: 
  - Linter
  - minimap-linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.python
  - meta.function-call.python
  - meta.function-call.arguments.python
  - meta.structure.dictionary.python
  - meta.structure.dictionary.key.python
  - string.quoted.single.single-line.python
  - punctuation.definition.string.begin.python
```

**Comment by Arcanemagus** [comment]
> Opened file is ignored: Yes

Looks like that file is being ignored, most likely because it is ignored by your VCS (`git`?). You can disable ignoring VCS ignored settings in Atom's main settings.

**Comment by kd8bny** [comment]
@Arcanemagus  Same issue here. Disabling "ignore VCS" does not repair

**Comment by DeviaVir** [comment]
@Arcanemagus so that is where that was hiding.. I was looking in the wrong place. Thank you, my linting is working again :+1:

@kd8bny I am closing this ticket as my issue is resolved, you may want to consider opening your own and providing all that I have provided above as well.
