### ISSUE TITLE
Apply solution to specific issue

### ISSUE THREAD

**Issue by janos-ss** [steelbrain/linter#1503]
Hi,

The [linter message v2 ](https://github.com/steelbrain/linter/blob/master/docs/types/linter-message-v2.md) has an optional `solutions` field. And there is an **Apply All Solutions** command, but how to apply the solution of one specific issue? And where to its title? Or the titles of the available solutions?

Version of Atom: 1.18
OS: Ubuntu 14.04

Thanks!
Janos

**Comment by steelbrain** [comment]
Hi @janos-ss 

You should see the title of the issue as well as be able to apply it individually if you place your cursor in the error area and invoke the Intentions shortcut (different based on OS, you can see Intentions package README for it)

**Comment by janos-ss** [comment]
That was not obvious, but it works great, thanks!
