### ISSUE TITLE
Update 2.2.0 failed

### ISSUE THREAD

**Issue by Eremiteb** [steelbrain/linter#1505]
Atom 1.18.0 x64 on Windows 7 x64.
Updating to “linter@2.2.0” failed.Hide output…
Unable to download https://www.atom.io/api/packages/linter/versions/2.2.0/tarball: unable to verify the first certificate.
The same in updating attempt linter-ui-default to 16.2

**Comment by steelbrain** [comment]
This is an APM issue because linter does not handle it's own installation. I'll try to be helpful tho, Are you behind a corporate proxy by any chance?

**Comment by Eremiteb** [comment]
I use NAT. What is APM?

**Comment by steelbrain** [comment]
APM is the package manager responsible for installing Atom packages, you can find it @ https://github.com/atom/apm

**Comment by Eremiteb** [comment]
Thanks for answers, I close a subject. It seems to me, it is Atom problem because she is identical to all packages. I will write to them.
