### ISSUE TITLE
Change background of the whole linted line

### ISSUE THREAD

**Issue by tuxmark5** [steelbrain/linter#1506]
I've been looking for a way to change the background color of the whole line when the line is linted with a build error. I'm using atom-build and it is very difficult to quickly see where the errors happen, as the puny red dot is not that visible. It that possible to do this with the current version of linter?

**Comment by Arcanemagus** [comment]
Can you re-file this on [linter-ui-default](https://github.com/steelbrain/linter-ui-default)? This project no longer deals with the interface you see.
