### ISSUE TITLE
Linter css not working?

### ISSUE THREAD

**Issue by Niichie** [steelbrain/linter#1508]
Hello, I am new to atom and when I am trying to install and use linter css on the latest atom beta it does not seem to work.

It was working on the stable build, but the beta seems to run much smoother so I would like to transfer my packages over.

These are the errors I am getting, along with the developer console, and my installed packages.

![error](https://user-images.githubusercontent.com/16381287/28030473-f26f5f1a-6571-11e7-9a43-5fa801dab7b5.JPG)
![linter](https://user-images.githubusercontent.com/16381287/28030474-f2719b36-6571-11e7-9e11-6903ca91297a.JPG)
![packages](https://user-images.githubusercontent.com/16381287/28030472-f26d9f0e-6571-11e7-82a4-3da06eec8d7b.JPG)

**Comment by Arcanemagus** [comment]
Please file this on `linter-csslint`, or even better do yourself a _major_ favor and move to using [stylelint](https://stylelint.io/) ([linter-stylelint](https://atom.io/packages/linter-stylelint)) as it is orders of magnitude better than the antiquated CSSLint 😉.
