### ISSUE TITLE
Closing a TextEditor wipes all messages for that file

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter#1510]
When you close a `TextEditor` instance it seems that `linter` is removing all messages associated with that `TextEditor` which is great if that was the only instance of that file open.

If however there are multiple `TextEditor`s open to a single file (`TextBuffer`), then the messages are cleared on the other `TextEditor`s and need another `lint()` call to recreate them.

Steps to reproduce:
1. Open a file, create some linter messages in it
2. Split the file into multiple editors
3. Close the second one of them

Expected:
The first instance on the file still shows the same messages it did before the second instance was closed.

Actual:
The messages are cleared from the first instance, requiring `lint` to re-run to recreate them.

Seen with:
* `linter-ui-default`
* `linter-ui-plus`
* `atom-minimap-linter`

**Comment by steelbrain** [comment]
This has been fixed in `master`
