### ISSUE TITLE
Provide option to toggle linter for specific files

### ISSUE THREAD

**Issue by lucasdf** [steelbrain/linter#1522]
Sometimes I just want to disable/toggle linting for an specific file, either permanently or temporarily. I am thinking something like right-click on the editor and then click on "toggle linter" or an option through the command palette.
Having the ability to pick which linter to disable would be nice, although just having a "toggle all" option would probably be enough most of the time. I would not care about having to do that each time I opened the file, although remembering that I ignored linters for the file would be nice.

I suppose that right now there is no simple way to do that and I am thinking how I could proceed to implement a plugin for that. Is there a way to intercept the call to `provideLinter` and decide whether to drop it or allow it to proceed according to the file? I think I could try to redefine whatever function does that inside the `linter` package, but that's too hacky. Maybe linter could provide a hook to be called before the linter is executed? Or linter could add this feature as part of the package? Or is there any other way to achieve what I am trying to do?

**Comment by steelbrain** [comment]
We have `linter:toggle-active-editor` command, and also a glob in linter config about which files to ignore

**Comment by lucasdf** [comment]
Oh, great! That will work.
