### ISSUE TITLE
Lint on Change blocks visual updates whilst checking?

### ISSUE THREAD

**Issue by DannyJJK** [steelbrain/linter#1523]
When typing and the lint takes a while to check, it seems to freeze the whole editor, so typing sometimes completely freezes. Surely it should just continue in the background or happen asynchronously in some way? On VS Code, similar linting-on-type doesn't cause this issue and you can type as normal.

I've seen it happen on a few different types of files, but the latest one I was using was a CoffeeScript file that's about 1200 lines, using the linter-coffeelint package.

I can somewhat mitigate the issue by increasing the Lint on Change Interval, but it doesn't really solve the problem.

Atom: 1.19.0 (I have seen it happen on previous versions)
macOS Sierra 10.12.6
MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by steelbrain** [comment]
You could change tooltip follows to mouse so it won't show up. Alternatively just disable lintOnFly and code in peace ☮️

**Comment by DannyJJK** [comment]
Changing the tooltips or even disabling the linter-ui-default package doesn't fix the issue, so I'll just have to disable lintOnFly for now

**Comment by steelbrain** [comment]
I misread your issue, if the issue is the editor **freezing** then it's because linter-coffeelint does all the calculations in the UI thread. You could open an issue on that repo asking to do the blocking calculations in a new thread like linter-eslint does.

**Comment by DannyJJK** [comment]
Ah sorry! I assumed it was a problem with the base package, I'll open an issue on that repo. Thanks!
