### ISSUE TITLE
Slow Linter 

### ISSUE THREAD

**Issue by fstagni** [steelbrain/linter#1529]
Hello,
I have a laptop and a desktop, both with Ubuntu 16.04, Atom 1.19.2 and on both the same list of packages, including linter, linter-ui-default, linter-pylint, linter-shellcheck and a small list of very common packages. 

On the laptop I see very similar timing results when running the actual linter (e.g. pylint) inside or outside atom. Let's say that, e.g., it takes ~4.5 seconds to lint a python file of ~1200 lines. 

On the desktop, running inside atom (on the same file) takes about 40 seconds, outside of atom (SAME command, according to ps) takes about 4 seconds.

If I try linting a shell script with shellchecker I get exactly the same behavior, with the atom linter taking 6 to 10 times the time it takes to run the linter alone.

I tried the usual (de-)installation, and disabling of plugins, without results. The config.cson has nothing fancy. Would you have any idea of where to look further?

Thanks and cheers,
Federico

**Comment by steelbrain** [comment]
Hi @fstagni 

The base linter is filetype agnostic and the linting is done by individual providers. The slowness comes from them and not the base linter. Could you please reopen this issue in the specific linters you're experiencing slowness on?

Also most (not all) of the linter providers are just proxies to the real CLI `pylint` or similar linters. So the slowness is actually originating from them 🙃 

Thanks again!
