### ISSUE TITLE
Linter-gcc Problem on Windows (linter-gcc: Executable not found)

### ISSUE THREAD

**Issue by mikemakeitso** [steelbrain/linter#1530]
Hi,

My gcc path (C:\MinGW\bin) is correct and compiles on command line and via Atom.

After installing Linter-gcc, it does provide ondemand sytax checking... 

But 

When compiling, i get a "inter-gcc: Executable not found" problem

**Comment by steelbrain** [comment]
Hi @mikemakeitso 

The `linter-gcc` package requires `g++` executable to be installed on your system to work. You could ask the package author for further information. Also this repository is a language-agnostic base, closing as external.

Cheers
