### ISSUE TITLE
[Linter] Error running pycodestyle Error.

### ISSUE THREAD

**Issue by Hanzhizheng** [steelbrain/linter#1533]
[Linter] Error running pycodestyle Error: Column start (125) greater than line length (107) for line 51(…)(anonymous function) @ /home/zzz/.atom/packages/linter/lib/linter-registry.js:159

[Linter] Error running pycodestyle Error: Column start (125) greater than line length (107) for line 51(…)(anonymous function) @ /home/zzz/.atom/packages/linter/lib/linter-registry.js:159

[Linter] Error running pycodestyle Error: Column start (125) greater than line length (107) for line 51(…)(anonymous function) @ /home/zzz/.atom/packages/linter/lib/linter-registry.js:159

[Linter] Error running pycodestyle Error: Column start (125) greater than line length (107) for line 51(…)(anonymous function) @ /home/zzz/.atom/packages/linter/lib/linter-registry.js:159

**Comment by steelbrain** [comment]
Please report provider errors in individual providers as the error is in them and not the base linter.

Closing as external, Thank You
