### ISSUE TITLE
Grammar detection does not work

### ISSUE THREAD

**Issue by BreederBai** [steelbrain/linter#1535]
In ardupilot project，Grammar detection does not work.I would like to know if this is the problem I set up, or should the project too much, too many documents

**Comment by steelbrain** [comment]
Hi @BreederBai 

Can you explain your issue further? Does Atom not show correct grammar in status bar or does the linter provider for that grammar not get triggered?

Either way, can you also attach results of `linter:debug` command?

**Comment by BreederBai** [comment]
Hello！ @steelbrain 

this is my configure

![image](https://user-images.githubusercontent.com/27894314/29696757-839d4b1c-897d-11e7-91e0-2fdc242a8bea.png)
![image](https://user-images.githubusercontent.com/27894314/29696811-d00ca0ec-897d-11e7-8c34-aca2268d8c4c.png)

![image](https://user-images.githubusercontent.com/27894314/29696834-e8f4e308-897d-11e7-9d8c-f166794c85f5.png)
![image](https://user-images.githubusercontent.com/27894314/29696862-18544850-897e-11e7-96e1-3e8910649c38.png)
This is the actual effect
![image](https://user-images.githubusercontent.com/27894314/29696972-d4abaf8e-897e-11e7-86b8-84a008b619e0.png)

**Comment by steelbrain** [comment]
Thank you for the additional information, can you open the file you're working on and press <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd>

You will get a list of commands, select the `Linter: Debug` command take screenshot or post contents of the popup

**Comment by BreederBai** [comment]
this is my Debug information
![image](https://user-images.githubusercontent.com/27894314/29697884-672ff284-8984-11e7-98bb-11411d006723.png)

**Comment by steelbrain** [comment]
Thank you @BreederBai 

It looks like grammar detection is working. Linter is detecting the scope correctly. You could try asking the `linter-clang` author what is going on. Also give the author link to this discussion as it has useful debugging information.

**Comment by BreederBai** [comment]
think you @steelbrain

**Comment by BreederBai** [comment]
Thank you  @steelbrain
