### ISSUE TITLE
Yoda condition alert even when both parts are equal

### ISSUE THREAD

**Issue by JoaoGFarias** [steelbrain/linter#1536]
When both parts of a expression are equal, the linter displays a [Yoda condition](https://en.wikipedia.org/wiki/Yoda_conditions) alert.

Since they are indistinguishable, the alert should not be displayed.

![screen shot 2017-08-25 at 3 40 35 pm](https://user-images.githubusercontent.com/1585655/29727920-422c4dde-89ac-11e7-9f37-61f37ba837be.png)
![screen shot 2017-08-25 at 3 43 44 pm](https://user-images.githubusercontent.com/1585655/29727921-422f4926-89ac-11e7-89f3-6f65e54b2cea.png)

**Atom version**: 1.19.3
**OS**: Mac OS Sierra 10.12.6

**Comment by Arcanemagus** [comment]
You'll need to determine which of your providers is giving you this message, determine which project they are providing a wrapper for, and file an issue on that.

Linter itself is just a "manager" of providers, who themselves are just wrappers around the actual program providing the messages. If you aren't sure which provider is generating that message the `Linter: Debug` command should be helpful.
