### ISSUE TITLE
show inline tooltip on a larger range

### ISSUE THREAD

**Issue by jhoogeboom** [steelbrain/linter#1539]
Ideally clicking on the error dot or anywhere along the line shows the inline error tooltip. Now it's only showing when the cursor is exactly at the place it has an error. 

![2017-09-02 12 13 39](https://user-images.githubusercontent.com/1828504/29994786-55af6b84-8fd8-11e7-875b-32ba0b729b72.gif)

redirected here from [https://github.com/steelbrain/linter-ui-default/issues/430](https://github.com/steelbrain/linter-ui-default/issues/430)

**Comment by steelbrain** [comment]
I might not have been clear enough but I actually meant whatever linter provider you're using (eg linter-clang) 😛 
My apologies
