### ISSUE TITLE
Get/Activate the old theme.

### ISSUE THREAD

**Issue by royalpinto** [steelbrain/linter#1541]
How do I get below theme ? Is it deprecated or  is there any way to activate it ?
![atom-liter-theme](https://user-images.githubusercontent.com/1013699/30046717-e2b88302-921d-11e7-939e-1cfe806d00eb.png)

**Comment by Arcanemagus** [comment]
That "theme" is the UI from Linter v1, there is no way to use it currently.

With Linter v2 one of hte major changes was the splitting out of the UI into a service that could be built on top of by anybody, so it's definitely _possible_ somebody could build a new UI that emulated that look, but to my knowledge nobody has taken on that yet. ([linter-ui-plus](https://github.com/mehcode/linter-ui-plus/) is the only start at an alternative UI so far, [minimap-linter](https://atom.io/packages/minimap-linter) also utilizes the service to get the messages.)

**Comment by royalpinto** [comment]
@Arcanemagus Thanks for the reply and suggestions. This was a cool theme. However, I will play around with above suggested libraries.
