### ISSUE TITLE
Use apply all

### ISSUE THREAD

**Issue by rpanai** [steelbrain/linter#1554]
On the animation you can type apply all to fix all the warnings. It seems I don't have this option how can I activate it?

**Comment by steelbrain** [comment]
Can you please post the result of `Linter: Debug` command?

**Comment by rpanai** [comment]
here it is
    Platform: linux
    Atom Version: 1.18.0
    Linter Version: 2.2.0
    Opened file is ignored: No
    Matching Linter Providers: 
    Disabled Linter Providers: 
    Standard Linter Providers: 
      - Flake8
    Indie Linter Providers: 
    UI Providers: 
      - Linter
    Ignore Glob: **/*.min.{js,css}
    VCS Ignored Paths are excluded: true
   Current File Scopes: 
     - *
     - text.plain.null-grammar

**Comment by steelbrain** [comment]
After clicking/focusing a valid text editor, invoke the command palette. Do you see anything like `Linter Ui Default: Apply All Solutions`?

**Comment by rpanai** [comment]
Yes I do

**Comment by steelbrain** [comment]
That's the one in the animation. It works with providers that provide a `fix` along with the linter results. Most famous one I know of is ESLint.

Have fun! Feel free to continue discussing. Closing as answered

**Comment by Arcanemagus** [comment]
Just a note: Flake8 doesn't provide fixes 😉.

**Comment by rpanai** [comment]
@Arcanemagus I noticed. Do you know a package that will work with python? So far I didn't have luck

**Comment by Arcanemagus** [comment]
I don't think any Python linter supports fix suggestions. It seems that ecosystem has focused their efforts into external tools such as `autopep8` instead of bundling it into the linter like other languages.
