### ISSUE TITLE
linter is not showing

### ISSUE THREAD

**Issue by aliburhankeskin** [steelbrain/linter#1555]
![ekran alintisi](https://user-images.githubusercontent.com/32386753/31742523-8a4f8b9c-b460-11e7-96a2-275524ed0fd4.PNG)

**Comment by Arcanemagus** [comment]
The status bar by default represents _all_ files in your project, while the panel only shows the current file. You can change this in the settings.

**Comment by aliburhankeskin** [comment]
my current file is also an error, but I can not see the details of this error in the notification bar 
sorry for my bad english

**Comment by Arcanemagus** [comment]
Change the panel to display all messages in the project, it's possible your provider is buggy and not reporting the correct path so `linter` can't associate the message with the editor.

**Comment by aliburhankeskin** [comment]
problem solved thank you very much
