### ISSUE TITLE
 error font is too small

### ISSUE THREAD

**Issue by 2236529177** [steelbrain/linter#1556]
I do no know whether you think the error font is too small

- [ ]

**Comment by Arcanemagus** [comment]
`linter` actually no longer has a UI in this codebase, the "stock" UI was moved over into [linter-ui-default](https://github.com/steelbrain/linter-ui-default). That being said, the font size used comes from Atom and your theme, so you should fix this with either a custom override in your `styles.less`, or by changing your font size in Atom.
