### ISSUE TITLE
Linter not resolving my absolute paths from TypeScript imports

### ISSUE THREAD

**Issue by peturh** [steelbrain/linter#1557]
I'm getting errors when using absolute path in my typescript files. I'm able to build it and run it, but these errors are weird. What can I do to make them go away? Or why is absolute path not supported?

![image](https://user-images.githubusercontent.com/3379947/32314404-0da0ef84-bfa8-11e7-9522-2b1b3661edb7.png)

![image](https://user-images.githubusercontent.com/3379947/32314439-312d1d10-bfa8-11e7-9253-7a4441f30e05.png)

**Comment by Arcanemagus** [comment]
You'll need to file that on whichever provider is giving you those messages (`atom-typescript`?), `linter` _just_ manages when most providers are triggered and routing the messages.
