### ISSUE TITLE
Does not work when the file path includes Chinese.

### ISSUE THREAD

**Issue by coffee-sgr** [steelbrain/linter#1559]
With linter-gcc.
Linter only works when both the file name and the file path are in English. Hope we can get better language support.

**Comment by steelbrain** [comment]
Hi @coffee-sgr

Thank you for taking the time to report this issue. I can understand this must be very fraustrating, but this package is actually just the base linter. It's language and program agnostic, Linter relies on different providers to feed it info on different filetype. In your case it is `linter-gcc`.

The problem that you're experiencing comes from `linter-gcc`, please open an issue there

Thanks!
