### ISSUE TITLE
xo/linter causes atom to hang if it's linting a file that moves

### ISSUE THREAD

**Issue by OmgImAlexis** [steelbrain/linter#1561]
If the linter starts linting a file and then I move it the linter never finishes instead Atom's RAM just keep climbing until Atom crashes or I kill the process.

> I've noticed if I move a file while xo is still linting it that xo never finishes and Atom's RAM keeps climbing until it hits around 1.5GB and then hangs.

Ref: https://github.com/sindresorhus/atom-linter-xo/issues/83#issuecomment-346893956

**Comment by Arcanemagus** [comment]
This has nothing to do with `linter`, this project simply triggers the `lint()` method of the enabled providers and waits for a result from each of them.
