### ISSUE TITLE
Type definition incorrect in docs

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter#1565]
As discovered in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22904, the [type definition](https://github.com/steelbrain/linter/blame/master/docs/types/standard-linter-v2.md#L21) in the Linter v2 API type documentation uses a [Maybe Type](https://flow.org/en/docs/types/maybe/) which allows the possibility of `undefined` as "valid" when it is actually an error to return that. The documentation should be clarified to reflect that.

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/linter/commit/7d7e52625da118f51df73b5083d751a047effd44
