### ISSUE TITLE
[Linter] Error running PHP Error: spawn EACCES

### ISSUE THREAD

**Issue by S-O-D** [steelbrain/linter#1568]
Hi all, when I open atom I have a red windows who signal me an error to look with the developper tools and when I open it I can read this:
```
/Users/me/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running PHP Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at /Users/me/.atom/packages/linter-php/node_modules/sb-exec/lib/index.js:24:53
    at /Users/me/.atom/packages/linter-php/node_modules/sb-exec/lib/index.js:23:12
    at Generator.next (<anonymous>)
    at step (/Users/fredericgouygou/.atom/packages/linter-php/node_modules/sb-exec/lib/index.js:146:191)
    at /Users/me/.atom/packages/linter-php/node_modules/sb-exec/lib/index.js:146:361
```
I have uninstall and re-install few times all linter packages and atom too but this message come back again and I don't find a solution anywhere.
If someone know the solution it will be wonderfull...

**Comment by steelbrain** [comment]
It sounds like you are trying to execute a `php` executable that doesn't have `+x` permissions

Can you please send your path to php? Also it's permissions?

**Comment by S-O-D** [comment]
Thank's for yours replies guys! Indeed Iwrote the PHP Path thinking well. I'm a french beginner and I have some difficulties with english and some praticals!!!
Thank's a lot for all!!!
