### ISSUE TITLE
Need to have ability to run linter command inside docker container

### ISSUE THREAD

**Issue by artempartos** [steelbrain/linter#1570]
Need to have ability to run linter command inside docker container

**Comment by Arcanemagus** [comment]
This is a package for Atom that manages other packages, I'm not entirely sure what you are asking here, but it makes _no_ sense in the context of this repository.

**Comment by Arcanemagus** [comment]
Closing as a duplicate of https://github.com/AtomLinter/linter-eslint/issues/1110, since I'm guessing that's what you actually meant by this.
