### ISSUE TITLE
Let linter know that project files are connected

### ISSUE THREAD

**Issue by chrispahm** [steelbrain/linter#1571]
Hi, first of all thanks for your awesome base linter!
I just created a linter provider for the GAMS programming language and have the following issue: In multi file models it can often happen that changing something in File A creates an error in File B. At first, I naively told the linter-ui in which file the error occured so it showed up corretcly in that file. However, removing the mistake (in File A) that caused the error in File B would not remove the message being shown. Obviously what happens is that the message is correctly removed by the linter-ui from its invocation in File A, but as linting File B resulted in the same error it is still shown there. I would now have to go into file B, re-lint and then finally the error would not be shown anymore. 
So the question I have is: can I somehow tell the base-linter that some files are connected (so treated as one file), so that messages are correctly revoked? Or, if that is not possible can I force re-linting every open file of a certain scope so that no false error messages are shown?

Thanks a lot for your advise!

**Comment by steelbrain** [comment]
Hi @chrispahm 

We have a `scope` attribute on the linter provider, you can set it to `project` and handle the per-file messages in your own provider, see https://steelbrain.me/linter/types/standard-linter-v2.html

If you want to go a bit more advanced than that, you can take full control of the linting with the Indie API, see https://steelbrain.me/linter/types/indie-linter-v2.html

**Comment by chrispahm** [comment]
Thanks a lot for your quick reply! The `project` scope seems to be all I need for now
