### ISSUE TITLE
Documentation clarification: can you return legacy messages from standard V2 provider?

### ISSUE THREAD

**Issue by lierdakil** [steelbrain/linter#1572]
Looking at the [source code](https://github.com/steelbrain/linter/blob/7d7e52625da118f51df73b5083d751a047effd44/lib/linter-registry.js#L126) I'm convinced you can't and everything will break horribly if you try. But the [documentation](https://steelbrain.me/linter/types/standard-linter-v2.html) says `lint` can return `Array<Message | MessageLegacy>`.

So... either I'm misunderstanding the code, or documentation might need fixing.

**Comment by Arcanemagus** [comment]
I _think_ that is a remnant from when that documentation was trying to do double duty for both v1 and v2, before I split the v1 documentation off into the [v1 branch](https://github.com/steelbrain/linter/blob/v1/docs/types/standard-linter-v1.md).

As you guess, at least to my knowledge, if a provider specifies itself as v2 it will be treated as such and expected to give back v2 messages. A PR fixing that would be great!
