### ISSUE TITLE
Incorrect tooltip positioning

### ISSUE THREAD

**Issue by alexwhitman** [steelbrain/linter#1576]
See screenshot:
![atom-linter](https://user-images.githubusercontent.com/422013/37099783-2a7e4d6c-2219-11e8-9d34-a4d8fee22db9.png)

The tooltip is positioned far to the right and below the actual position of the error.

Running atom 1.24.0 on Ubuntu 18.04 (beta) with linter 2.2.0 and linter-eslint 8.4.1.

**Comment by steelbrain** [comment]
This issue belongs to the `linter-ui-default` repository, and looks very much like https://github.com/steelbrain/linter-ui-default/issues/489

Can you try the fix in the comment at https://github.com/steelbrain/linter-ui-default/issues/489#issuecomment-370867497?

**Comment by alexwhitman** [comment]
Apologies for the wrong repo.  I tried the fix but it didn't have any effect.

**Comment by steelbrain** [comment]
Can you try opening the devtools console and see if you have an error message there?

**Comment by alexwhitman** [comment]
No errors in the dev console.

**Comment by Arcanemagus** [comment]
How are you triggering the tooltip? Keyboard or mouse?

I notice the tooltip is _much_ larger than the text, do you have any DPI scaling going on?

**Comment by skylize** [comment]
Could also be a custom styling problem. Does this still happen if you remove all custom styles and use one of the default themes?

**Comment by Arcanemagus** [comment]
Thanks for reporting back! Closing this as it isn't an issue here 😉.
