### ISSUE TITLE
Error running clang

### ISSUE THREAD

**Issue by Dydypotra** [steelbrain/linter#1577]
I have just installed version 2.2.0 of linter, and version 4.1.2 of linter-clang. Every time I write some text, the error of: "[Linter] Error running clang" appears. Consequently the package does anything

**Comment by steelbrain** [comment]
Can you check your dev console to see what you have there?

**Comment by Dydypotra** [comment]
The terminal shows the following:
![captura de pantalla de 2018-04-22 10-58-17](https://user-images.githubusercontent.com/38585463/39093221-4ace9b0e-461c-11e8-95a8-fd97c55233c9.png)

**Comment by steelbrain** [comment]
So do you have `clang` installed and in your `$PATH`?

**Comment by Dydypotra** [comment]
Now it works. I did not had clang installed haha. Than kyou

**Comment by steelbrain** [comment]
Glad you figured it out!
