### ISSUE TITLE
Get "Cannot run Undefined" Error 

### ISSUE THREAD

**Issue by miketuk** [steelbrain/linter#1579]
Get this each time Linter runs - package version is 2.2.0

apm -v gives

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.12
git 2.7.4

All packages in atom are reporting as up-to-date 

Mike

**Comment by Arcanemagus** [comment]
This would be a bug in whatever provider you have configured for that file type. You can see a list of active providers for the file by running `Linter: Debug` from the Command Palette.

**Comment by Arcanemagus** [comment]
I would guess that it is [linter-puppet-parser](https://github.com/asquelt/linter-puppet-parser) as that code hasn't been touched in 3 years, you might want to file an issue there and see if anyone is still maintaining it.

Thanks for reporting back!
