### ISSUE TITLE
[question] What do the different linter APIs do?

### ISSUE THREAD

**Issue by Aerijo** [steelbrain/linter#1586]
I've decided to write a linter package, but there seems to be two different options. I searched for `indie` project wide and in the docs, but all I can find is references to upgrading from V1 to V2, or how to consume/provide the service.

I would greatly appreciate if someone could (briefly?) explain the difference between the regular linter and indie linter, as well as which one I should choose when. I think the difference is that the indie linter can "push" notifications, but would like some clarification on it's benefits, limitations, etc.

(also explaining where the name `indie` comes from might help; I assumed it was like `indie developer` and meant for small packages)

**Comment by steelbrain** [comment]
Hi @Aerijo 

To make it simpler for providers, Linter provides an abstraction on top of Atom APIs. So while linter providers have to provide results for each file, they don't have to worry about clearing them when the editor closes or watching for saves or keypresses so they could provide live linting results.

That's what "Standard Linter" API is. You provide the grammars you want to listen for, and you provide your linting callback. It's called automatically on tab open, it's results are discarded on tab close and if the provide allows, it's called for each typing so user can see the feedback live.

Indie has been popularized in our industry by terms like Indie Developer but what it stands for is Independent. So an Indie Linter is an independent linter and does not need to depend on lifecycles of the editor. An Indie Linter can say have a daemon running in the background and can update the "issues" in Atom independent of what goes on in the editor, from just the results of the daemon. This is not possible with Standard Linters as they require user action to be invoked.

We have "types" definitions of each component of the ecosystem in the same documentation areas as the upgrading ones. Link: https://steelbrain.me/linter/

You can goto the examples there, copy/paste what you like and then keep extending it to make your own.

**Comment by aviatesk** [comment]
I guess this issue might be better to be pinned instead of just being closed, no ?
@steelbrain 's answer really clarified my question on the difference between those two APIs.
