### ISSUE TITLE
Linter is open in another Atom window

### ISSUE THREAD

**Issue by rafaeltovar** [steelbrain/linter#1592]
If I have two Atom windows opened, when I click in Linter in window number 1, Linter is open in window number 2.

![screen shot 2018-09-05 at 10 24 49](https://user-images.githubusercontent.com/791726/45081047-9d29b600-b0f6-11e8-8b78-bf78ff421c54.png)

Atom: 1.30.0 x64
MacOS: 10.13.6
Linter: 2.2.0 
Linter-ui-default: 1.7.1

**Comment by steelbrain** [comment]
Hi

`linter-ui-default` in the newest version registers itself as a Dock. You can drag it (like a tab) and put it at the bottom dock to get the "default" behavior back.

Closing as answered but feel free to continue discussing
