### ISSUE TITLE
Linter does not show errors in other files than the active

### ISSUE THREAD

**Issue by ArmandoAA** [steelbrain/linter#1594]
I've been trying to fix this problem for some time, but to no avail.
Linter only shows me the error of the current file, it accuses errors in other files but it does not tell me what file it is or what error.

![screenshot_5](https://user-images.githubusercontent.com/37708752/45323922-fba1ca80-b522-11e8-9e53-eca33b6f4615.png)

**Comment by steelbrain** [comment]
Hi

You can change this in `linter-ui-default`'s setting. You can make the panel and status bar show items from whatever scope you prefer.

Closing but feel free to continue discussing
