### ISSUE TITLE
Not linting, no errors

### ISSUE THREAD

**Issue by svbeon** [steelbrain/linter#1595]
Hi,

Since a few weeks back the linter has just stopped linting, without errors in the console or anything.
I'm using `busy-signal (1.4.3)`, `intentions (1.1.5)` , `linter (2.2.0)`, `linter-ui-default (1.7.1)`, `linter-js-standard (5.1.0)` on `atom (1.30.0)` 

I've opened an issue in ricardofbarros/linter-js-standard#222 as well, as i have no idea what the issue actually is

The Linter UI displays fine but remains empty, I've tried disabling all other packages without luck, I've tried removing and reinstalling the packages and resetting all their settings to default. I've also tried `linter-eslint (8.4.1)` without luck. Running the `Linter: Lint` command gives no console output, nothing at all happens. running `Linter: Debug`  yields

```
Platform: win32
Atom Version: 1.30.0
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
  - js-standard
Disabled Linter Providers: 
Standard Linter Providers: 
  - js-standard
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.js
  - meta.function-call.js
  - meta.arguments.js
  - meta.brace.round.js
```

Linter is set as follows:
  - [x] Lint preview tabs
  - [x] Lint on open
  - [x] Lint on change
  - Lint on change interval: `300` (default)
  - Ignore files matching this glob: `**/*.min.{js,css}` (default)
  - Disabled providers: `` (default)

linter-js standard is set as follows:
  - [ ] Disable if the project uses ESLint
  - [ ] Check for standard
  - [ ] Honor style settings
  - [ ] Lint HTML Files
  - [ ] Lint Markdown Files
  - [ ] Show ESLint rules
  - Style: `standard`

linter-ui-default is set as follows:
  - [ ] Always take minimum space
  - [x] Hide panel when empty
  - [x] Show decorations
  - [x] Show panel
  - [ ] Show provider name
  - [x] Show status bar
  - [x] Show tooltip
  - [x] Use busy signal
  - Decorate on Tree View: `Files`
  - Gutter Highlights position: `High` 
  - Panel Represents: `Current file`
  - Statusbar click behaviour: `Toggle panel`
  - Statusbar position: `Left`
  - Statusbar represents: `Entire Project`
  - Tooltip follows: `Both`
  - Panel Height: `162` 

I haven't included any screenshots because there isn't much to screenshot really as *noting* happens

**Comment by Arcanemagus** [comment]
Are you seeing any errors in the console?

According to the debug output you posted it _should_ be running, so the next step I would take personally would be to open Atom's Developer Tools, find the code for `linter-js-standard` and put a breakpoint within its `lint()` function to see if it is being called.

**Comment by svbeon** [comment]
@Arcanemagus nope that's the first place i looked :) 

Will take a look at the code and report back, thanks!

**Comment by svbeon** [comment]
okay seems to be a permission error, and now `linter-eslint` suddenly works, so definetly an issue with `linter-js-standard` and not with liner itself. so I'll close the issue over here
