### ISSUE TITLE
Wrong indentation warning for nested JS templates

### ISSUE THREAD

**Issue by mercmobily** [steelbrain/linter#1596]
Hi,

I am not sure if this belongs to linter-js-standard or here.
This is a small example to show the problem:
(I realise the code doesn't do much, it was working code butchered for brevity)

    function render () {
      const {html, _items} = this;
      return html`
        <style>
          :host { display: block; }
        </style>
        <p ?hidden="${_items.length !== 0}">Please add some products to cart.</p>
        ${_items.map((item) => {
          console.log('aaa')
        })}
      `;
    }
    render();

The `console.log` line gives a warning: `expected indentation of 4 spaces but found 6
The following line has the same problem.

Help?

**Comment by Arcanemagus** [comment]
`linter` just acts as an intermediary between the data providers (`linter-js-standard` here) and the interface (`linter-ui-standard`).

You should re-file this on linter-js-standard, although this is likely to be an issue with `standard` itself.
