### ISSUE TITLE
Installing “linter@2.2.0” failed.

### ISSUE THREAD

**Issue by srikanthmatheesh** [steelbrain/linter#1600]
npm ERR! Unexpected end of JSON input while parsing near '...st":{"shasum":"6e02e7'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/srikanthmatheesh/.atom/.apm/_logs/2018-10-25T16_50_09_461Z-debug.log
[2018-10-25T16_50_49_076Z-debug.log](https://github.com/steelbrain/linter/files/2515975/2018-10-25T16_50_49_076Z-debug.log)

**Comment by steelbrain** [comment]
It could be a corporate proxy messing with the http responses that give you this error. If that's not it, see if you're having any http injection issues with any other app, if you're only having this with APM. I'd recommend contacting APM maintainers and try to see what they suggest.

Linter does not control it's own installation, so sorry can't recommend much there.

**Comment by ahmedgadit** [comment]
i am having the same issue did you any solution @srikanthmatheesh
