### ISSUE TITLE
--jobs option error with v2.3.0 and v2.2.1 

### ISSUE THREAD

**Issue by NeuroticTumbleweed** [steelbrain/linter#1601]
I'm having an issue when using `linter-flake8@2.3.0` or `linter-flake8@2.2.1`
when saving the file (and triggering the linter) the linting fails and I get the error:
```
linter-flake8:: Flake8 threw an error related to: WARNING:flake8.checker:The --jobs option is not compatible with supplying input using - . Ignoring --jobs arguments.
```
If i downgrade and use `linter-flake8@2.2.0` it works as expected.

System details:

| Component | Version |
| :---- |----: | 
| Atom version | 1.25.0 |
| OS | Fedora 28 |
| linter-flake8 version | 2.3.0 |
| Python version | 3.6.6 |
| flake8 version | 3.4.1 |

![screenshot from 2018-10-28 16-53-49](https://user-images.githubusercontent.com/11734934/47617666-1ed40980-dad2-11e8-9618-f92101941979.png)

**Comment by Arcanemagus** [comment]
You'll need to file this on `linter-flake8`, `linter` itself has nothing to do with this.
