### ISSUE TITLE
Unable to work with xmllint

### ISSUE THREAD

**Issue by emilisev** [steelbrain/linter#1602]
Hi

I am unable to get errors from xmllint package. It is correctly installed though, and in the console I can run 
`atom.packages.loadedPackages['linter-xmllint'].mainModule.lintOpenFile(atom.workspace.getActiveTextEditor())`
and I see the errors. But when editing a file it doesn't seem to get called at call (I placed breakpoints, they are not reached)
It works with other packages such as linter-php.

I'm not sure what I should do next to investigate the issue.

Thanks

Émi

**Comment by Lavenderloved** [comment]
My linter-gcc does not work.I sincerely need your help.Much thanks. My e-mail at 1610553022@qq.com, I am waiting for your reply ,thanks.

**Comment by Arcanemagus** [comment]
What is the output of the `Linter: Debug` command when you have a file open that you expect output on?

**Comment by emilisev** [comment]
Here it is 

```
Platform: win32
Atom Version: 1.33.0
Linter Version: 2.2.0
Opened file is ignored: Yes
Matching Linter Providers: 
  - xmllint
Disabled Linter Providers: 
Standard Linter Providers: 
  - PHP
  - xmllint
Indie Linter Providers: 
  - Code Actions
  - PHP (FelixFBecker)
UI Providers: 
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - text.xml
  - meta.tag.xml
  - entity.name.tag.localname.xml
```

**Comment by Arcanemagus** [comment]
> Opened file is ignored: Yes

It seems the file you have open is ignored by your VCS (e.g. `git`). You'll either need to disable the core Atom setting to ignore VCS ignored files, or move that file somewhere that is handled by your version control software.
