### ISSUE TITLE
linter doesn't lint after update to 2.3.0

### ISSUE THREAD

**Issue by Krotera** [steelbrain/linter#1608]
Right after the update, it stopped linting for Rust and C++. linter was the only package updated.
I can't seem to provoke any related dev tool console errors (e.g., after writing and saving a file).

Versions, including providers:
```
Atom 1.33.1 x64
Manjaro 18.0.2
linter-gcc 0.7.1
linter-rust 0.9.0
```

Screenie (C++):
![Cpp](https://i.imgur.com/4NVdYGs.png)

Screenie (Rust):
![Rust](https://i.imgur.com/m3vLeFP.png)

**Comment by Arcanemagus** [comment]
This is an issue with the providers still using the v1 API. Please see the linked issues for when it will be resolved by them, as well as a workaround until it is:

* For `linter-gcc` please follow https://github.com/hebaishi/linter-gcc/issues/199
* For `linter-rust` please follow https://github.com/AtomLinter/linter-rust/issues/142
