### ISSUE TITLE
Non of the linter working

### ISSUE THREAD

**Issue by Rabin016** [steelbrain/linter#1629]
I installed all dependencies that it ask for and still its not working.
It not showing any warning or error for wrong tag or any kind of mistake.
I uploaded screenshot and show what other packages that I have now so clarify things
<a href="https://ibb.co/XDz4b4d"><img src="https://i.ibb.co/XDz4b4d/Capture-2.png" alt="Capture-2" border="0"></a> <a href="https://ibb.co/TKDSGcH"><img src="https://i.ibb.co/TKDSGcH/Capture-3.png" alt="Capture-3" border="0"></a> <a href="https://ibb.co/JrycpYj"><img src="https://i.ibb.co/JrycpYj/Capture-4.png" alt="Capture-4" border="0"></a> <a href="https://ibb.co/zG48wLD"><img src="https://i.ibb.co/zG48wLD/Capture.png" alt="Capture" border="0"></a>
Plz let me know what is the prob here?

**Comment by Rabin016** [comment]
Neverminded I just fixed it by unchecked this option
<img src="https://i.ibb.co/WGk9d5r/Capture-5.png" alt="Capture-5" border="0">

**Comment by Arcanemagus** [comment]
The two providers you show in your screenshot both require external applications to be installed, it looks like you haven't completed that step yet. In any case this doesn't look to be an issue with `linter` itself so I'm closing this.

If you have problems with a specific provider please search the existing issues to see if it has already been opened, and file a new one if you can't find an existing one.

**Comment by Owyn** [comment]
Ok I have the same issue after installing linter for Atom io - it just shows 0 errors 0 warnings all the time and does nothing

I have every package it required me to installed and node.js too
