### ISSUE TITLE
Ability to disable gutter markers

### ISSUE THREAD

**Issue by brettz9** [steelbrain/linter#1656]
I have enabled `atom-ide-ui` so as to be able to get tooltips in the package [ide-typescript](https://github.com/atom/ide-typescript/) and I incidentally also like the gutter option it provides in allowing fixes from the gutter as per this screenshot:

![image](https://user-images.githubusercontent.com/20234/64938734-75d10180-d891-11e9-91c7-d6db061328f1.png)

Yet I still like the Linter table you provide in the bottom dock.

But as also per the above screenshot, an extra red dot ends up showing when both `linter` and `atom-ide-ui` are enabled (since each is marking the line where linting errors occur) and was wondering if you could provide an option to disable that.

**Comment by Arcanemagus** [comment]
All settings (including the one you are asking for) related to how information is displayed live in `linter-ui-default` as we long ago abstracted the visual interface out of `linter`.
