### ISSUE TITLE
One package, can provide more than one linter?

### ISSUE THREAD

**Issue by elarivie** [steelbrain/linter#1670]
Hello,

Is it possible for a Package to provide more than one Linter?

When writing the package.json we can (I think) only provide one function name "provideLinter".

		"linter": {
			"versions": {
				"2.0.0": "provideLinter"
			}
		}
	}

Also... when writing the "provideLinter" method it can only (I think) return one linter object.

**Note:** - The provided linters would have a different names but could have different/same: scope, lintsOnChange, grammarScopes

**Question # 1** - Is it currently possible to provide more than one "provideLinter" method in the package.json?
**Question # 2** Is it currently possible for the "provideLinter" method to return an array of linter?

**Question # 3** can it currently be done by another way?

Thanks

**Comment by Arcanemagus** [comment]
> Question # 1 - Is it currently possible to provide more than one "provideLinter" method in the package.json?

No, that's not how services work in Atom.

> Question # 2 Is it currently possible for the "provideLinter" method to return an array of linter?

Apparently it **is** possible, I didn't know that 😮
https://github.com/steelbrain/linter/blob/2175cfc22e590e7744eb04c49524bb4aa778ed18/lib/index.js#L26-L30

> Question # 3 can it currently be done by another way?

See #2 😉.

**Comment by elarivie** [comment]
@Arcanemagus  Great, thanks

**Comment by elarivie** [comment]
@Arcanemagus 

FYI

I published a new atom linter package: [python-linters](https://atom.io/packages/python-linters) which is using this hidden feature and it works pretty well.

It is also successfully setting different lint-trigger for each sub-linter part of the package ([currently 4](https://github.com/elarivie/atom-python-linters/blob/25e39c55acc13c72dcadff130af3c6d5ed56e035/lib/lint.js#L670)).
