### ISSUE TITLE
ModuleNotFoundError: No module named 'flake8'

### ISSUE THREAD

**Issue by cevs89** [steelbrain/linter#1672]
ModuleNotFoundError: No module named 'flake8'

**Comment by cevs89** [comment]
[Linter] Error running Flake8

**Comment by steelbrain** [comment]
Hi @cevs89 

While I appreciate the time you took to report this issue, it would be great if you could include like a screenshot or stack trace of the error next time :)

Also, this package is just the base linter, you might wanna post some info around the error into the [`linter-flake8` repository](https://atom.io/packages/linter-flake8)
