### ISSUE TITLE
Pass file argument to solutions.apply

### ISSUE THREAD

**Issue by danielbayley** [steelbrain/linter#1680]
It would be useful if some kind of `file` (absolute path) argument was passed into the function defined in `solutions.apply`, to make use of.

**Comment by steelbrain** [comment]
`solutions.apply` already gets `textEditor, solution` as the two arguments, you can probably call `textEditor.getPath()` and have what you're looking for

**Comment by danielbayley** [comment]
@steelbrain Looks like the problem is, using atom-ide, that callback-based solutions is an unimplemented feature: https://github.com/facebookarchive/atom-ide-ui/blob/master/docs/diagnostics.md#service-apis
