### ISSUE TITLE
Can't install linter in the Atom

### ISSUE THREAD

**Issue by timmy61109** [steelbrain/linter#1683]
I installed your IDE interface on Atom, but the following error message prevented me from installing your package.

```
Installing “linter@2.3.1” failed.Hide output…
undefined
```

and the info:

```
These packages were not installed, check your console
for more info.
  • linter
```

Ubuntu 18.04
Atom 1.44.0

If there is a way to let me know more ways to get the error message, please tell me, because I find that many packages cannot be installed.

**Comment by Arcanemagus** [comment]
Unfortunately that `undefined` _should_ be the error message. You might get more information by running `apm install linter` from a terminal.

> I find that many packages cannot be installed

This makes me suspect you might have a permissions issue.

**Comment by timmy61109** [comment]
Yes, I found that `sudo` is required to install, thank you for your reply.

**Comment by Arcanemagus** [comment]
If `sudo` was "required", then you had done that once before and already messed up the permissions 😉.

You'll want to fix the permissions on your `~/.atom` folder:
```sh
chown -R user:group ~/.atom
```

**Comment by timmy61109** [comment]
@Arcanemagus Thank you for the solution. If I can't use Atom to delete the files under the open directory, is it also a permission problem?
