### ISSUE TITLE
No Linting UI

### ISSUE THREAD

**Issue by GC-3** [steelbrain/linter#1686]
I've recently downloaded this linter, but I cannot see any UI, in other screenshots I can see the UI in the bottom left of the window, but this is not appearing for me.

![image](https://user-images.githubusercontent.com/61598548/75834698-c9c19b00-5d8a-11ea-9aeb-3014237c9b97.png)

I have [`linter`](https://atom.io/packages/linter), [`linter-javac`](https://atom.io/packages/linter-javac), [`linter-ui-default`](https://atom.io/packages/linter-ui-default), [`intentions`](https://atom.io/packages/intentions), and[ `busy-signal`](https://atom.io/packages/busy-signal) installed. Am I missing anything?

My apologies if I am missing something obvious, I am fairly inexperienced in regards to programming in general.

**Comment by GC-3** [comment]
I will note that it does still compile the java files.

**Comment by steelbrain** [comment]
Thanks for opening (and then closing) this issue @GC-3! Can you please share what worked for you?
