### ISSUE TITLE
How to disable the linting of python files?

### ISSUE THREAD

**Issue by bassamanator** [steelbrain/linter#1708]
I went to settings and in 'Ignore files matching this glob' I added *.py. So that setting now looks like this:
```**/*.min.{js,css}, *.py```
but my python files keep getting linted.

How do I disable the linter for python files?

**Comment by goi42** [comment]
It seems to expect a single Glob, so you cannot just provide a comma-separated list. Moreover, if you want to ignore _all_ python files, you need to tell it to descend the directory tree. Try:
```
{**/*.min.{js,css},**/*.py}
```
or
```
**/{*.min.{js,css},*.py}
```
