### ISSUE TITLE
Linter showing errors/warnings from all providers even when linter-flake8 is installed.

### ISSUE THREAD

**Issue by SHUR1K-N** [steelbrain/linter#1711]
Even though I have the linter-flake8 provider installed, the base linter seems to be marking errors and warnings from _all_ other providers (such as pycodestyle, pyflakes, etc. which are _not_ installed) as well as my _installed_ flake8 provider's errors.

Things I have tried:
- Adding "pycodestyle" and "pyflakes" to the "Disabled providers" section in base linter's settings
- Re-installing the **linter**, **linter-flake8** and **linter-ui-default** packages
- Installing linter-pycodestyle and linter-pyflakes and _then_ disabling those providers from base linter's settings (in a desperate attempt)

Variables between this state change:
- A clean Windows re-install
- A clean Atom re-install

**Comment by aminya** [comment]
This is not related to linter package (this repository). Linter package will show the errors from every other linter package you have installed.

Do you have ide-python installed?

**Comment by SHUR1K-N** [comment]
I only have **linter-flake8** installed, not **pycodestyle** and **pyflakes** which linter is still showing me.

Yes, I do have ide-python installed.

**Comment by aminya** [comment]
ide-python provides all the linter messages. You can disable those you don't want from its package.

I would suggest uninstalling linter-flake8 and use ide-python (which provides more features). Simply disable the linters from its settings.

**Comment by aminya** [comment]
Let me know if you had other problems

**Comment by SHUR1K-N** [comment]
This worked perfectly! Thank you, comrade! **[Closed]**
