### ISSUE TITLE
Error on linter 3.1.1

### ISSUE THREAD

**Issue by ponghissimo** [steelbrain/linter#1714]
I have this error after installing linter on Atom and xampp
![errore linter](https://user-images.githubusercontent.com/26579656/95021790-7cd0da80-0673-11eb-99d6-b923fb72a70a.PNG)

**Comment by aminya** [comment]
This does not seem to be related to this repository. It is from linter-php. Can you open an issue there?

**Comment by aminya** [comment]
Closing due to lack of a response.
