### ISSUE TITLE
 release span

### ISSUE THREAD

**Issue by bties-ogawa** [steelbrain/linter#1725]
thanks for your nice extensions.

so far at least There ware some updates every everyday.
I need to restart ATOM each time.

It's very annoying, so if possible, I'd like you to update it about once a month.
you possible?

**Comment by aminya** [comment]
Sorry about that. Atom does not force you to update or restart. You can continue working on your project without restarting. 

The recent releases of the linter involved a complete redesign of the tooltip and the UI framework. 

See the changelog to learn more:
https://github.com/steelbrain/linter-ui-default/blob/master/CHANGELOG.md
https://github.com/steelbrain/linter/blob/master/CHANGELOG.md

The rest of the releases were based on the issues that the users send. So, we have no other solution than to fix those. See these as an example:
- https://github.com/steelbrain/linter-ui-default/issues/624
- https://github.com/steelbrain/linter-ui-default/issues/617
- https://github.com/steelbrain/linter-ui-default/issues/609

So, if you are bothered by the updates, you can just delay your updating. But keep in mind that some of these releases include the critical fixes that can improve your workflow

**Comment by steelbrain** [comment]
@aminya I think the user does raise an important issue here. We've released 3 times in a day in the not too distant past

![image](https://user-images.githubusercontent.com/4278113/107318650-0fb8d000-6abf-11eb-9274-195bdf7c0b72.png)

Thoughts on having a release every-other day if we really do want to do frequent updates (or once a week if it's not a lot of changes)? Also critical IMHO shouldn't be associated with improvements, it's a slippery slope. It'd be critical if people can't open Atom because editor crashes on open because of this plugin. It's high priority but not critical if they cannot use the clipboard for a day (IMHO).

I'll defer the decision to you

**Comment by ogaaaan** [comment]
ok, so far it is NOT fix.

I UNINSTALLED YOUR EXTENSIONS.
I NEVER USE THOSE.

thx.

**Comment by bties-ogawa** [comment]
@aminya 

That's your personal convenience and a very selfish reason.
We are very annoying.

and, You made other issue.
It doesn't seem like a good idea for you close this issue by yourself with selfish. You should be aware that you are creating the problem yourself.

It seems that other users have also uninstalled it, I decided uninstall them.

**Comment by aminya** [comment]
I am shocked by your comments.

First of all, I don't earn anything from maintaining and updating this package. I am just spending my **free time** to service you the users for **free** without asking anything in return. 

Secondly, the fixes are requested by real users (see the issues I linked, or join our chat server in Discord), and they expect us to fix those. I don't understand if I am being selfish, or those who want everyone else's workflow to suffer from the bugs.

Thirdly, I don't expect to release any new version from now on, given the behavior of the users. It seems nobody appreciates the time I have spent for you.

**Comment by OgreThorn** [comment]
@aminya 

**It's annoying to update many times a day.**

**Comment by steelbrain** [comment]
@OgreThorn Your tone certainly does NOT help the discussion here. While there is a good idea here at its core. As you said, it certainly is annoying to update many times a day. But there are also people, users, just like yourself, who want the features that are to be released.

The ideal outcome is a balance between the two, not shouting at people, who are working on open source in their free time, without getting paid. Please be mindful. [Remember the human](https://laulima.hawaii.edu/access/content/user/shamilto/web100_laulima_F08/introduction/netiquette/Rule1.pdf)

**Comment by OgreThorn** [comment]
@steelbrain 
Thank you for your advice.

We don't have to argue, but we don't have to force ourselves to get along. I just want to solve the problem in front of me. If a group of minority opinions were fun, friendly, and entertaining, the developers would probably ignore them. Therefore, the opinions of small groups always grow strongly. It will appear in the comments.

This sentence uses Google Translate. I apologize if the expression is strange. But please complain to Google as well.

**Comment by ogaaaan** [comment]
this is my opinion.
that is very simple.

we have 2 choices.
- love spam notice
- uninstall this

**Comment by bties-ogawa** [comment]
I usually develop using VS Code. And when I want to take notes, I use ATOM. That's why my ATOM doesn't require Linter. However, I think that the kind of Linter is important for those who are developing with ATOM.

Updates and bugfixes aren't bad. Rather, it is welcome. The problem is that it is released many times a day. But he commented on the importance of updates and bug fixes. The topic has slipped.

It's a disappointing conclusion on this conversation, but we have to wait for him to understand the issue correctly.

I expect a monthly release. Some would expect a weekly release.

**Comment by aminya** [comment]
As stated, there will be no new releases for a foreseeable future, so your problem is solved.

Please respect the code of conduct, or I have to delete the messages that violate that.

https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct

**Comment by ogaaaan** [comment]
@aminya 

hey, I don't know at all. The "resolved" you say came about because you have not enything to fix now, and it's quite possible that the same problem will occur in the future.

What is your solution? is it to delete someone's comment? it is not. you may continue to release so many times in a day again. The problem is there. Don't change the story. If you change the story without permission, the comments will be rough.

we need comment "i never spam" if you understand our opinions. this is true "solved".

**Comment by bties-ogawa** [comment]
@aminya 
Just because you happen to have no  need to bugfix to do does not mean that this problem has been resolved.

**Comment by aminya** [comment]
I am adding a button to the update notification that allows explicitly to skip restarting.
https://github.com/atom/settings-view/pull/1175/files

I will also check to see if it is easy to add an option to the package updater which allows setting a weekly time interval for the updates.

This issue has served its purpose, I am closing it.
