### ISSUE TITLE
I HATE LINTER!!! NOW I CAN DELETE THIS IN ATOM OR DISABLED???

### ISSUE THREAD

**Issue by kingtelepuz5** [steelbrain/linter#1739]
he every time on or dowloand, i ma hate this packegs. This don't take me work fck red line, mu code WORK, NOT ONE BREAK, it's sheet packegs take ME RED LINE ALL MU PROJECT!!!
I don't want to repair the display i want to delete it forever !

**Comment by kingtelepuz5** [comment]
He constantly complains about my comments, which use different stickers, which I, in turn, specially put in order to make the comments convenient for me to read !!

**Comment by kingtelepuz5** [comment]
okay after i uninstalled it 5 times and turned it off 6 times it stopped SCREAMING AT ME IN RED UNDERLINKS

**Comment by aminya** [comment]
https://github.com/atom-community/atom/blob/master/CODE_OF_CONDUCT.md

```
apm uninstall linter
apm uninstall linter-ui-default
apm uninstall atom-ide-base
# any package that depends on the linter
```
