### ISSUE TITLE
Gutters marks not showing

### ISSUE THREAD

**Issue by lmartins** [steelbrain/linter#54]
Im not a huge fan of how "Show Highlighting" marks the errors, so i prefer to keep just the gutter marks active. Currently though, the plugin isn't showing anything in the gutter area.

**Comment by jmurphyau** [comment]
I ran into this issue and worked out how to replicate it.. Install two linter for one file type (e.g. `linter-jshint` and `linter-jscs` then disable once.. 

The config for the disabled one remains in you `config.son` resulting in the disabled linter still in `@linters` (coming from `@allLinters`)  - but the linter never runs and the following never gets executed

    processMessage: (messages, tempFileInfo, linter) =>
    ...
    if tempFileInfo.completedLinters == @linters.length
    ....

**Comment by jmurphyau** [comment]
This issue is very old so I will open a new one

**Comment by kevhill** [comment]
Hey, just started using atom and linter and having the same problem. 

No gutter marks showing up
![screen shot 2016-12-15 at 10 57 48 am](https://cloud.githubusercontent.com/assets/2395550/21235783/7ef569c6-c2b5-11e6-8426-6f0b0327dbd5.png)

but gutter marks enabled
![screen shot 2016-12-15 at 10 56 12 am](https://cloud.githubusercontent.com/assets/2395550/21235819/9dfd249e-c2b5-11e6-97d7-56305f54eaa7.png)

no extra community packages, osx, atom 1.12.7, linter 1.11.21

**Comment by steelbrain** [comment]
@kevhill Can you try the good ol' uninstall and re-install? and can we discuss this in a new issue please :)

**Comment by kevhill** [comment]
*sigh* of course that did work. Sorry for the spam.
