### ISSUE TITLE
`Linter: Next Error` jumps to seemingly random error

### ISSUE THREAD

**Issue by AsaAyers** [steelbrain/linter#833]
"next" should be relative to the cursor, but I think it's jumping based on some internal ordering or internal caching.

**Comment by steelbrain** [comment]
It should be super-easy to keep track of last error once we land https://github.com/atom-community/linter/pull/827

**Comment by AsaAyers** [comment]
It should be super-easy to look at where the cursor is and find the next error. Keeping track of it after you land is definitely the wrong approach.

I literally want to jump to the first lint error in my file, so I jump to the top of the file, then trigger `Linter: Next Error`. As it currently is, I go to some random lint error in the middle of the file.

**Comment by steelbrain** [comment]
Right, our current sort function could be the problem. We could sort using the ranges.

**Comment by AsaAyers** [comment]
https://github.com/atom-community/linter/blob/master/lib/commands.coffee#L71-L75

It isn't even looking at where the cursor is. It assumes the first time you call it you want the first error, and every time after that you want the next index no matter what has changed.

**Comment by wmayner** [comment]
+1

**Comment by steelbrain** [comment]
This will be fixed in https://github.com/atom-community/linter/issues/865

**Comment by AsaAyers** [comment]
Actually this is fixed in #851

**Comment by steelbrain** [comment]
Agree that it fixes it, but #865 fixes it throughout the package.
If we do that, we won't have to sort anything in commands.
