### ISSUE TITLE
status line display can be misleading

### ISSUE THREAD

**Issue by devoncarew** [steelbrain/linter#878]
When the `dartlang` plugin creates lints, it can (optionally) create 'info' level lints, as well as errors and warnings. These are things like todo comments, or suggestions to correct for best practices. We map this to the lint `Trace` type. If only info lints exist on a project, the status line UI makes the lints appear more series than they are:

<img width="77" alt="screen shot 2015-09-07 at 10 35 05 am" src="https://cloud.githubusercontent.com/assets/1269969/9721261/742141a0-554c-11e5-8dcc-fc0c94b7c8db.png">

If there are no issues at all, the status line shows as green w/ a check mark and the text `No Issues`. W/ info level lints, it shows as red, with an X, and the text `N Issues`.

It would be great to either give users a way to turn off the status line contribution (like the error panel), and/or to only have the status line contribution turn red iff there are errors or warnings.

**Comment by steelbrain** [comment]
Well. We could have a field like `isIssue` in the message object in the next provider API. then we would only could those `isIssue`s in that. How does that sound?

**Comment by ketamin** [comment]
I often use this information provided by the status line. Only thing I won't fix are "info" from jshint. So maybe particular settings, which allow to specify which should be treated as issue (for me: "error,warning") in the plugin (linter-jshint for me) would be perfect. Since I do not really know, if that's already covered with the proposal from @steelbrain, I hope you understand this as one more use-case.

**Comment by steelbrain** [comment]
@ketamin Yes the solution I provided would work for your scenario as the provider would know if it's an `info` type message and they can just set `isIssue:false` in that particular kind-of messages

**Comment by devoncarew** [comment]
@steelbrain, adding a field like `isIssue` would work for us. Thanks!

**Comment by Arcanemagus** [comment]
I would go the opposite method: have a field of `isIgnorable` or something, so the default is to show it. That way we won't require another update of every single linter to have their messages show up.

That or just have `linter` default `isIssue` to true if not defined.

**Comment by devoncarew** [comment]
With https://github.com/atom-community/linter/pull/884 landing, this issue is less critical for us. It might still be nice from a UX perspective, but feel free to close.

**Comment by steelbrain** [comment]
@devoncarew well, this is still a problem, info messages are not issues. We could mark this a low priority

**Comment by steelbrain** [comment]
@devoncarew I have thought about this again and have another approach in mind, currently we have a `type` attribute that can be anything, how about an extra `severity` attribute that has only three possible values `error`, `warning` and `info`? So then we can have `Syntax Error` as `type` and `error` as `severity`

**Comment by devoncarew** [comment]
Just for clarity, I think this is the struct you're talking about:

```
export type Linter$Message = {
  type: string,
  text?: string,
  html?: string,
  name?: ?string,
  filePath?: string,
  range?: Atom$Range,
  trace?: Array<Linter$Message>,
  key: string
}
```

Adding a `severity` field w/ a restricted set of values makes sense. The `type` would then be used as a human readable name; you could make decisions about how to present the issues based on `severity`.

**Comment by steelbrain** [comment]
@devoncarew Yep, that's exactly what I am suggesting, do you like the idea?

**Comment by devoncarew** [comment]
yup, :+1: :)

**Comment by steelbrain** [comment]
Gonna open an issue in `linter-ui-default` to use this new attribute

**Comment by GrahamHannington** [comment]
@steelbrain,

Thank you for Linter.

I have developed, but have not yet published (I'll do that in the next week or so), an on-the-fly Linter provider that uses [v.Nu](http://validator.github.io/validator/) to validate HTML5 or XHTML5 documents.

This might be contrary to a "no news is good news" (or "silence is golden") linter mindset, but when a document is valid, I want to display the corresponding messages from v.Nu. Not just "success", but also details of the validation rules used:

![image](https://cloud.githubusercontent.com/assets/8519708/14045939/e1be4eea-f2d8-11e5-8d8a-75876a4c48cf.png)

I am using the `severity` attribute: all three of the messages in this screen capture have a `severity` value of `"info"`. I would like the corresponding status to show "No Issues".

Will your forthcoming work in `linter-ui-default` (or here) do that? (I don't want to selectively hide messages.)

While I'm asking: I'd be interested in your thoughts on how I've formatted the "summary" message in the example screen capture:

```html
<span class="linter-highlight status-success icon icon-check">The document validates according to the specified schema(s).</span>
```

**Comment by steelbrain** [comment]
@GrahamHannington Yes, exactly. The new status icon in `linter-ui-default` is not going to count `Info` messages as issues. It even has a config to ignore certain message types in the panel, so you'll be able to see `Info` types highlighted in the editor but hidden in the panel.

Please let me know if you have any other request.
