### ISSUE TITLE
Expand link to line/column to work with clicks on all error text

### ISSUE THREAD

**Issue by brettz9** [steelbrain/linter#963]
I'd like to request an option so that the links which lead one to a specified problematic line and column be expanded so that clicking anywhere on that line, such as the name of the error, explanation of the error, etc. would also go to that same line. I'm used to Notepad++'s JSLint plug-in, and it is very convenient not to have to fine tune one's cursor  specifically toward the text such as "at line 504 col 1" but click anywhere on that line.

**Comment by Arcanemagus** [comment]
The only potential issue I see with this is losing the ability to copy error text off of the message panel.

**Comment by steelbrain** [comment]
It also conflicts with the ability to copy error messages.

**Comment by brettz9** [comment]
How about as just an option though? Even with the option on, I am guessing one could at least copy the whole line, as I see, for example, that I can still copy paste the "at line..." text as long as I start dragging after it (excepting the first line which apparently conflicts with the invisible gripper).

**Comment by brettz9** [comment]
Nevermind, sorry--I guess I can highlight the text, but for whatever reason, the actual copying doesn't work.

**Comment by brettz9** [comment]
Still, the ability to have the whole link as a link would definitely be worth it to me, even to need to go the preferences and toggle it, if there was no way around the copying issue.

**Comment by blakeembrey** [comment]
Note that this also conflicts with multi-line error message toggling.

**Comment by brettz9** [comment]
Could it be implemented as a toggle button mode? If not, even with the multi-line message logging, it'd still be important enough to me at least.

**Comment by steelbrain** [comment]
@brettz9 Just a side question: How difficult it is to fine tune your cursor at `at line x in x`?

**Comment by brettz9** [comment]
Given how much I deal with linting and errors, and how much I prefer to rest my wrists by avoiding fine movements with the mouse, it really is quite an issue for me... If it is the whole line, I can, while reading a message, immediately move the cursor to what I am reading (and when reading messages, I'm not really interested in reading the line number anyways).

**Comment by steelbrain** [comment]
No longer relevant in the upcoming UI, stay tuned
